DATA LIST FILE='C:\COUNTRIES\GU71\GUMR71FL.DAT' RECORDS=1
  /
  MCASEID     1-15   (A)
  MV000      16-18   (A)
  MV001      19-26  
  MV002      27-30  
  MV003      31-33  
  MV004      34-37  
  MV005      38-45  
  MV006      46-47  
  MV007      48-51  
  MV008      52-55  
  MV009      56-57  
  MV010      58-61  
  MV011      62-65  
  MV012      66-67  
  MV013      68-69  
  MV014      70-70  
  MV015      71-71  
  MV016      72-73  
  MV021      74-77  
  MV022      78-81  
  MV023      82-83  
  MV024      84-85  
  MV025      86-86  
  MV026      87-87  
  MV027      88-88  
  MV028      89-91  
  MV029      92-93  
  MV030      94-96  
  MV031      97-99  
  MV032     100-101 
  MV034$1   102-103 
  MV034$2   104-105 
  MV034$3   106-107 
  MV034$4   108-109 
  MV034$5   110-111 
  MV034$6   112-113 
  MV034$7   114-115 
  MV034$8   116-117 
  MV034A$1  118-118 
  MV034A$2  119-119 
  MV034A$3  120-120 
  MV034A$4  121-121 
  MV034A$5  122-122 
  MV034A$6  123-123 
  MV034A$7  124-124 
  MV034A$8  125-125 
  MV034B$1  126-127 
  MV034B$2  128-129 
  MV034B$3  130-131 
  MV034B$4  132-133 
  MV034B$5  134-135 
  MV034B$6  136-137 
  MV034B$7  138-139 
  MV034B$8  140-141 
  MV035     142-142 
  MV801     143-146 
  MV802     147-150 
  MV803     151-152 
  MV101     153-154 
  MV102     155-155 
  MV103     156-156 
  MV104     157-158 
  MV105     159-159 
  MV106     160-160 
  MV107     161-162 
  MV130     163-164 
  MV131     165-167 
  MV133     168-169 
  MV134     170-170 
  MV135     171-171 
  MV136     172-173 
  MV138     174-175 
  MV149     176-176 
  MV150     177-178 
  MV151     179-179 
  MV152     180-181 
  MV155     182-182 
  MV156     183-183 
  MV157     184-184 
  MV158     185-185 
  MV159     186-186 
  MV167     187-188 
  MV168     189-189 
  MV190     190-190 
  MV191     191-198 
  MV201     199-200 
  MV202     201-202 
  MV203     203-204 
  MV204     205-206 
  MV205     207-208 
  MV206     209-210 
  MV207     211-212 
  MV212     213-214 
  MV213     215-215 
  MV217     216-216 
  MV218     217-218 
  MV225     219-219 
  MV245     220-221 
  MV246     222-222 
  MV247     223-224 
  MV248     225-225 
  MV249     226-226 
  MV250     227-227 
  MV251     228-229 
  MV252     230-230 
  MV301     231-231 
  MV302     232-232 
  M304A$01  233-233 
  M304A$02  234-234 
  M304A$03  235-235 
  M304A$04  236-236 
  M304A$05  237-237 
  M304A$06  238-238 
  M304A$07  239-239 
  M304A$08  240-240 
  M304A$09  241-241 
  M304A$10  242-242 
  M304A$11  243-243 
  M304A$12  244-244 
  M304A$13  245-245 
  M304A$14  246-246 
  M304A$15  247-247 
  M304A$16  248-248 
  M304A$17  249-249 
  M304A$18  250-250 
  M304A$19  251-251 
  M304A$20  252-252 
  MV304$01  253-253 
  MV304$02  254-254 
  MV304$03  255-255 
  MV304$04  256-256 
  MV304$05  257-257 
  MV304$06  258-258 
  MV304$07  259-259 
  MV304$08  260-260 
  MV304$09  261-261 
  MV304$10  262-262 
  MV304$11  263-263 
  MV304$12  264-264 
  MV304$13  265-265 
  MV304$14  266-266 
  MV304$15  267-267 
  MV304$16  268-268 
  MV304$17  269-269 
  MV304$18  270-270 
  MV304$19  271-271 
  MV304$20  272-272 
  MV305$01  273-273 
  MV305$02  274-274 
  MV305$03  275-275 
  MV305$04  276-276 
  MV305$05  277-277 
  MV305$06  278-278 
  MV305$07  279-279 
  MV305$08  280-280 
  MV305$09  281-281 
  MV305$10  282-282 
  MV305$11  283-283 
  MV305$12  284-284 
  MV305$13  285-285 
  MV305$14  286-286 
  MV305$15  287-287 
  MV305$16  288-288 
  MV305$17  289-289 
  MV305$18  290-290 
  MV305$19  291-291 
  MV305$20  292-292 
  MV307$01  293-293 
  MV307$02  294-294 
  MV307$03  295-295 
  MV307$04  296-296 
  MV307$05  297-297 
  MV307$06  298-298 
  MV307$07  299-299 
  MV307$08  300-300 
  MV307$09  301-301 
  MV307$10  302-302 
  MV307$11  303-303 
  MV307$12  304-304 
  MV307$13  305-305 
  MV307$14  306-306 
  MV307$15  307-307 
  MV307$16  308-308 
  MV307$17  309-309 
  MV307$18  310-310 
  MV307$19  311-311 
  MV307$20  312-312 
  MV312     313-314 
  MV313     315-315 
  MV323A    316-317 
  MV325B    318-324 
  MV372A    325-325 
  MV384A    326-326 
  MV384B    327-327 
  MV384C    328-328 
  MV395     329-329 
  MV396     330-330 
  MV3A09B   331-333 
  MV3B17    334-335 
  MV3B25A   336-336 
  MV3B25B   337-337 
  MV463A    338-338 
  MV463B    339-339 
  MV463C    340-340 
  MV463D    341-341 
  MV463E    342-342 
  MV463F    343-343 
  MV463G    344-344 
  MV463X    345-345 
  MV463Z    346-346 
  MV464     347-348 
  MV474     349-349 
  MV474A    350-350 
  MV474B    351-351 
  MV474C    352-352 
  MV474D    353-353 
  MV474E    354-354 
  MV474F    355-355 
  MV474G    356-356 
  MV474H    357-357 
  MV474I    358-358 
  MV474J    359-359 
  MV474X    360-360 
  MV474Z    361-361 
  MV475     362-362 
  MV476     363-363 
  MV477     364-365 
  MV478     366-367 
  MV479     368-369 
  MV480     370-370 
  MV481     371-371 
  MV481A    372-372 
  MV481B    373-373 
  MV481C    374-374 
  MV481D    375-375 
  MV481E    376-376 
  MV481F    377-377 
  MV481G    378-378 
  MV481H    379-379 
  MV481X    380-380 
  MV482A    381-381 
  MV482B    382-382 
  MV482C    383-383 
  MV483     384-384 
  MV483A    385-386 
  MV483B    387-388 
  MV483C    389-390 
  MV501     391-391 
  MV502     392-392 
  MV503     393-393 
  MV504     394-394 
  MV505     395-396 
  MV507     397-398 
  MV508     399-402 
  MV509     403-406 
  MV510     407-407 
  MV511     408-409 
  MV512     410-411 
  MV513     412-412 
  MV525     413-414 
  MV527     415-417 
  MV528     418-419 
  MV529     420-422 
  MV531     423-424 
  MV532     425-425 
  MV535     426-426 
  MV536     427-427 
  MV541     428-428 
  MV602     429-429 
  MV603     430-432 
  MV604     433-433 
  MV605     434-434 
  MV613     435-436 
  MV614     437-437 
  MV616     438-440 
  MV621     441-441 
  MV627     442-443 
  MV628     444-445 
  MV629     446-447 
  MV631     448-448 
  MV633A    449-449 
  MV633B    450-450 
  MV633C    451-451 
  MV633D    452-452 
  MV633E    453-453 
  MV633F    454-454 
  MV633G    455-455 
  MV634A    456-456 
  MV634B    457-457 
  MV634C    458-458 
  MV634D    459-459 
  MV714     460-460 
  MV714A    461-461 
  MV716     462-464 
  MV717     465-466 
  MV719     467-467 
  MV721     468-468 
  MV731     469-469 
  MV732     470-470 
  MV739     471-471 
  MV740     472-472 
  MV741     473-473 
  MV743A    474-474 
  MV743B    475-475 
  MV743C    476-476 
  MV743D    477-477 
  MV743E    478-478 
  MV743F    479-479 
  MV743G    480-480 
  MV744A    481-481 
  MV744B    482-482 
  MV744C    483-483 
  MV744D    484-484 
  MV744E    485-485 
  MV745A    486-486 
  MV745B    487-487 
  MV747A    488-488 
  MV747B    489-489 
  MV750     490-490 
  MV751     491-491 
  MV754BP   492-492 
  MV754CP   493-493 
  MV754DP   494-494 
  MV754JP   495-495 
  MV754WP   496-496 
  MV756     497-497 
  MV761     498-498 
  MV761B    499-499 
  MV761C    500-500 
  MV762AA   501-501 
  MV762AB   502-502 
  MV762AC   503-503 
  MV762AD   504-504 
  MV762AE   505-505 
  MV762AF   506-506 
  MV762AG   507-507 
  MV762AH   508-508 
  MV762AI   509-509 
  MV762AJ   510-510 
  MV762AK   511-511 
  MV762AL   512-512 
  MV762AM   513-513 
  MV762AN   514-514 
  MV762AO   515-515 
  MV762AP   516-516 
  MV762AQ   517-517 
  MV762AR   518-518 
  MV762AS   519-519 
  MV762AT   520-520 
  MV762AU   521-521 
  MV762AV   522-522 
  MV762AW   523-523 
  MV762AX   524-524 
  MV762AZ   525-525 
  MV762BA   526-526 
  MV762BB   527-527 
  MV762BC   528-528 
  MV762BD   529-529 
  MV762BE   530-530 
  MV762BF   531-531 
  MV762BG   532-532 
  MV762BH   533-533 
  MV762BI   534-534 
  MV762BJ   535-535 
  MV762BK   536-536 
  MV762BL   537-537 
  MV762BM   538-538 
  MV762BN   539-539 
  MV762BO   540-540 
  MV762BP   541-541 
  MV762BQ   542-542 
  MV762BR   543-543 
  MV762BS   544-544 
  MV762BT   545-545 
  MV762BU   546-546 
  MV762BV   547-547 
  MV762BW   548-548 
  MV762BX   549-549 
  MV762BZ   550-550 
  MV763A    551-551 
  MV763B    552-552 
  MV763C    553-553 
  MV763D    554-554 
  MV763E    555-555 
  MV763F    556-556 
  MV763G    557-557 
  MV766A    558-559 
  MV766B    560-561 
  MV767A    562-563 
  MV767B    564-565 
  MV767C    566-567 
  MV768A    568-570 
  MV768B    571-573 
  MV768C    574-576 
  MV769     577-577 
  MV769A    578-578 
  MV770     579-579 
  MV770A    580-580 
  MV770B    581-581 
  MV770C    582-582 
  MV770D    583-583 
  MV770E    584-584 
  MV770F    585-585 
  MV770G    586-586 
  MV770H    587-587 
  MV770I    588-588 
  MV770J    589-589 
  MV770K    590-590 
  MV770L    591-591 
  MV770M    592-592 
  MV770N    593-593 
  MV770O    594-594 
  MV770P    595-595 
  MV770Q    596-596 
  MV770R    597-597 
  MV770S    598-598 
  MV770T    599-599 
  MV770U    600-600 
  MV770V    601-601 
  MV770W    602-602 
  MV770X    603-603 
  MV774A    604-604 
  MV774B    605-605 
  MV774C    606-606 
  MV775     607-607 
  MV777     608-608 
  MV778     609-609 
  MV779     610-610 
  MV780     611-611 
  MV781     612-612 
  MV783     613-613 
  MV784A    614-614 
  MV784B    615-615 
  MV784C    616-616 
  MV784D    617-617 
  MV784E    618-618 
  MV784F    619-619 
  MV784G    620-620 
  MV784H    621-621 
  MV784I    622-622 
  MV784J    623-623 
  MV784K    624-624 
  MV784L    625-625 
  MV784M    626-626 
  MV784N    627-627 
  MV784O    628-628 
  MV784P    629-629 
  MV784Q    630-630 
  MV784R    631-631 
  MV784S    632-632 
  MV784T    633-633 
  MV784U    634-634 
  MV784V    635-635 
  MV784X    636-636 
  MV785     637-637 
  MV791     638-638 
  MV793     639-639 
  MV793A    640-640 
  MV793B    641-641 
  MV820     642-642 
  MV822     643-643 
  MV823     644-644 
  MV824     645-645 
  MV825     646-646 
  MV826     647-647 
  MV826A    648-649 
  MV827     650-650 
  MV828     651-651 
  MV829     652-653 
  MV832B    654-656 
  MV832C    657-659 
  MV833A    660-660 
  MV833B    661-661 
  MV833C    662-662 
  MV834A    663-664 
  MV834B    665-666 
  MV834C    667-668 
  MV835A    669-669 
  MV835B    670-670 
  MV835C    671-671 
  MV836     672-673 
  MV837     674-674 
  MV844     675-675 
  MV845     676-676 
  MV846     677-677 
  MV847     678-678 
  MV848     679-679 
  MV849     680-680 
  MV851A    681-681 
  MV851B    682-682 
  MV851C    683-683 
  MV851D    684-684 
  MV851E    685-685 
  MV851F    686-686 
  MV851G    687-687 
  MV851H    688-688 
  MV851I    689-689 
  MV851J    690-690 
  MV851K    691-691 
  MV851L    692-692 
  MV852A    693-695 
  MV852B    696-698 
  MV852C    699-701 
  MV853A    702-703 
  MV853B    704-705 
  MV853C    706-707 
  MV854A    708-708 
  MV854B    709-709 
  SMDEPTO   710-711 
  SMDEPTO2  712-713 
  SMOEDIT   714-716 
  SMKEYER   717-719 
  SMKEYER2  720-722 
  SMILANG   723-724 
  SMQLANG   725-726 
  SMTRANS   727-727 
  MV044     728-728 
  SMEDUC    729-729 
  SMETID    730-730 
  SMETOB    731-731 
  SM105     732-732 
  SM106     733-734 
  SM114     735-736 
  SM115     737-738 
  SM116     739-739 
  SM117A    740-740 
  SM117B    741-741 
  SM117C    742-742 
  SM117D    743-743 
  SM117E    744-744 
  SM117F    745-745 
  SM117G    746-746 
  SM117H    747-747 
  SM117I    748-748 
  SM117J    749-749 
  SM117K    750-750 
  SM117L    751-751 
  SM117M    752-752 
  SM117N    753-753 
  SM117O    754-754 
  SM117P    755-755 
  SM117Q    756-756 
  SM117R    757-757 
  SM117S    758-758 
  SM117T    759-759 
  SM117U    760-760 
  SM117V    761-761 
  SM117W    762-762 
  SM117X    763-763 
  SM119     764-765 
  SM120     766-766 
  SM219     767-767 
  SM222     768-769 
  SM303D    770-770 
  SM308L    771-771 
  SM308M    772-772 
  SM308N    773-773 
  SM308O    774-774 
  SM308P    775-775 
  SM308Q    776-776 
  SM308R    777-777 
  SM308S    778-778 
  SM308T    779-779 
  SM423     780-780 
  SM433     781-782 
  SM616A    783-783 
  SM616B    784-784 
  SM616C    785-785 
  SM616D    786-786 
  SM708K    787-787 
  SM708L    788-788 
  SM708M    789-789 
  SM708N    790-790 
  SM708O    791-791 
  SM708P    792-792 
  SM708Q    793-793 
  SM708R    794-794 
  SM708S    795-795 
  SM708T    796-796 
  SM708X    797-797 
  SM708JJ   798-798 
  SM711     799-799 
  SM726     800-800 
  SM727     801-801 
  SM728     802-803 
  SM730K    804-804 
  SM730L    805-805 
  SM730M    806-806 
  SM730N    807-807 
  SM730O    808-808 
  SM730P    809-809 
  SM730Q    810-810 
  SM730R    811-811 
  SM730S    812-812 
  SM730T    813-813 
  SM730X    814-814 
  SM730JJ   815-815 
  SM737     816-816 
  SM738     817-819 
  SM739     820-820 
  SM807     821-821 
  SM812     822-822 
  SM813     823-824 
  SM814     825-825 
  SM815     826-827 
  SM816AA   828-828 
  SM816AB   829-829 
  SM816AC   830-830 
  SM816AD   831-831 
  SM816AE   832-832 
  SM816AF   833-833 
  SM816AG   834-834 
  SM816AH   835-835 
  SM816AI   836-836 
  SM816AJ   837-837 
  SM816AK   838-838 
  SM816AL   839-839 
  SM816AM   840-840 
  SM816AN   841-841 
  SM816AO   842-842 
  SM816AP   843-843 
  SM816AQ   844-844 
  SM816AR   845-845 
  SM816AS   846-846 
  SM816AT   847-847 
  SM816AU   848-848 
  SM816AV   849-849 
  SM816AW   850-850 
  SM816AX   851-851 
  SM816BA   852-852 
  SM816BB   853-853 
  SM816BC   854-854 
  SM816BD   855-855 
  SM816BE   856-856 
  SM816BF   857-857 
  SM816BG   858-858 
  SM816BH   859-859 
  SM816BI   860-860 
  SM816BJ   861-861 
  SM816BK   862-862 
  SM816BL   863-863 
  SM816BM   864-864 
  SM816BN   865-865 
  SM816BO   866-866 
  SM816BP   867-867 
  SM816BQ   868-868 
  SM816BR   869-869 
  SM816BS   870-870 
  SM816BT   871-871 
  SM816BU   872-872 
  SM816BV   873-873 
  SM816BW   874-874 
  SM816BX   875-875 
  SM819A    876-876 
  SM819B    877-877 
  SM819C    878-878 
  SM905A2   879-879 
  SM905B2   880-880 
  SM905C2   881-881 
  SM906A2   882-882 
  SM906B2   883-883 
  SM906C2   884-884 
  SM906D2   885-885 
  SM906E2   886-886 
  SM906F2   887-887 
  SM906G2   888-888 
  SM906H2   889-889 
  SM906I2   890-890 
  SM911     891-891 
  SM916B    892-892 
  SM916C    893-893 
  SM919     894-894 
  SM921A    895-895 
  SM921B    896-896 
  SM922A    897-897 
  SM922B    898-898 
  SM922C    899-899 
  SM922D    900-900 
  SM922E    901-901 
  SM922F    902-902 
  SM922G    903-903 
  SM922H    904-904 
  SM922I    905-905 
  SM922K    906-906 
  SM922L    907-907 
  SM922M    908-908 
  SM922N    909-909 
  SM922O    910-910 
  SM922P    911-911 
  SM922Q    912-912 
  SM922X    913-913 
  SM928AA   914-914 
  SM928BB   915-915 
  SM928CC   916-916 
  SM929     917-917 
  SM932D    918-918 
  MD005     919-926 
  MD101A    927-927 
  MD101B    928-928 
  MD101C    929-929 
  MD101D    930-930 
  MD101E    931-931 
  MD101F    932-932 
  MD101G    933-933 
  MD101H    934-934 
  MD101I    935-935 
  MD101J    936-936 
  MD102     937-938 
  MD103A    939-939 
  MD103B    940-940 
  MD103C    941-941 
  MD103D    942-942 
  MD103E    943-943 
  MD103F    944-944 
  MD104     945-945 
  MD105A    946-946 
  MD105B    947-947 
  MD105C    948-948 
  MD105D    949-949 
  MD105E    950-950 
  MD105F    951-951 
  MD105G    952-952 
  MD105H    953-953 
  MD105I    954-954 
  MD105J    955-955 
  MD105K    956-956 
  MD105L    957-957 
  MD105M    958-958 
  MD105N    959-959 
  MD106     960-960 
  MD107     961-961 
  MD108     962-962 
  MD109     963-964 
  MD110A    965-965 
  MD110B    966-966 
  MD110D    967-967 
  MD110C    968-968 
  MD110E    969-969 
  MD110F    970-970 
  MD110G    971-971 
  MD110H    972-972 
  MD111     973-973 
  MD112     974-974 
  MD112A    975-975 
  MD113     976-976 
  MD114     977-977 
  MD115B    978-978 
  MD115C    979-979 
  MD115D    980-980 
  MD115E    981-981 
  MD115F    982-982 
  MD115G    983-983 
  MD115H    984-984 
  MD115I    985-985 
  MD115J    986-986 
  MD115K    987-987 
  MD115L    988-988 
  MD115M    989-989 
  MD115N    990-990 
  MD115O    991-991 
  MD115P    992-992 
  MD115Q    993-993 
  MD115R    994-994 
  MD115S    995-995 
  MD115T    996-996 
  MD115U    997-997 
  MD115V    998-998 
  MD115W    999-999 
  MD115X   1000-1000
  MD115Y   1001-1001
  MD115XA  1002-1002
  MD115XB  1003-1003
  MD115XC  1004-1004
  MD115XD  1005-1005
  MD115XE  1006-1006
  MD115XF  1007-1007
  MD115XG  1008-1008
  MD115XH  1009-1009
  MD115XI  1010-1010
  MD115XJ  1011-1011
  MD115XK  1012-1012
  MD117A   1013-1013
  MD119A   1014-1014
  MD119B   1015-1015
  MD119C   1016-1016
  MD119D   1017-1017
  MD119E   1018-1018
  MD119F   1019-1019
  MD119G   1020-1020
  MD119H   1021-1021
  MD119I   1022-1022
  MD119J   1023-1023
  MD119K   1024-1024
  MD119L   1025-1025
  MD119M   1026-1026
  MD119N   1027-1027
  MD119O   1028-1028
  MD119P   1029-1029
  MD119Q   1030-1030
  MD119R   1031-1031
  MD119S   1032-1032
  MD119T   1033-1033
  MD119U   1034-1034
  MD119V   1035-1035
  MD119W   1036-1036
  MD119X   1037-1037
  MD119Y   1038-1038
  MD119XA  1039-1039
  MD119XB  1040-1040
  MD119XC  1041-1041
  MD119XD  1042-1042
  MD119XE  1043-1043
  MD119XF  1044-1044
  MD119XG  1045-1045
  MD119XH  1046-1046
  MD119XI  1047-1047
  MD119XJ  1048-1048
  MD119XK  1049-1049
  MD116    1050-1051
  MD120    1052-1053
  MD121    1054-1054
  MD122A   1055-1055
  MD122B   1056-1056
  MD122C   1057-1057
  MD123    1058-1058
  MD124    1059-1059
  MD125    1060-1060
  MD126    1061-1062
  MD127    1063-1064
  MD128    1065-1065
  MD129    1066-1066
  MD130A   1067-1067
  MD130B   1068-1068
 .
VARIABLE LABELS
   MCASEID  "Case Identification"
  /MV000    "Country code and phase"
  /MV001    "Cluster number"
  /MV002    "Household number"
  /MV003    "Respondent's line number"
  /MV004    "Ultimate area unit"
  /MV005    "Men's sample weight (6 decimals)"
  /MV006    "Month of interview"
  /MV007    "Year of interview"
  /MV008    "Date of interview (CMC)"
  /MV009    "Month of birth"
  /MV010    "Year of birth"
  /MV011    "Date of birth (CMC)"
  /MV012    "Current age"
  /MV013    "Age in 5-year groups"
  /MV014    "Completeness of age information"
  /MV015    "Result of interview"
  /MV016    "Day of interview"
  /MV021    "Primary sampling unit"
  /MV022    "Sample stratum number"
  /MV023    "Sample domain"
  /MV024    "Region"
  /MV025    "Type of place of residence"
  /MV026    "NA - De facto place of residence"
  /MV027    "Number of visits"
  /MV028    "Interviewer identification"
  /MV029    "Keyer identification"
  /MV030    "Field supervisor"
  /MV031    "Field editor"
  /MV032    "Office editor"
  /MV034$1  "NA - Line number of wife/partner"
  /MV034$2  "NA - Line number of wife/partner"
  /MV034$3  "NA - Line number of wife/partner"
  /MV034$4  "NA - Line number of wife/partner"
  /MV034$5  "NA - Line number of wife/partner"
  /MV034$6  "NA - Line number of wife/partner"
  /MV034$7  "NA - Line number of wife/partner"
  /MV034$8  "NA - Line number of wife/partner"
  /MV034A$1 "NA - Wife or partner"
  /MV034A$2 "NA - Wife or partner"
  /MV034A$3 "NA - Wife or partner"
  /MV034A$4 "NA - Wife or partner"
  /MV034A$5 "NA - Wife or partner"
  /MV034A$6 "NA - Wife or partner"
  /MV034A$7 "NA - Wife or partner"
  /MV034A$8 "NA - Wife or partner"
  /MV034B$1 "NA - Age of wife/partner"
  /MV034B$2 "NA - Age of wife/partner"
  /MV034B$3 "NA - Age of wife/partner"
  /MV034B$4 "NA - Age of wife/partner"
  /MV034B$5 "NA - Age of wife/partner"
  /MV034B$6 "NA - Age of wife/partner"
  /MV034B$7 "NA - Age of wife/partner"
  /MV034B$8 "NA - Age of wife/partner"
  /MV035    "NA - Number of wives/partners"
  /MV801    "Time interview started (hhmm - 24 hour clock)"
  /MV802    "Time interview ended (hhmm - 24 hour clock)"
  /MV803    "Length of interview in minutes"
  /MV101    "Region"
  /MV102    "Type of place of residence"
  /MV103    "NA - Childhood place of residence"
  /MV104    "NA - Years lived in place of residence"
  /MV105    "NA - Type of place of previous residence"
  /MV106    "Educational level"
  /MV107    "Highest year of education (at level in MV106)"
  /MV130    "Religion"
  /MV131    "Ethnicity"
  /MV133    "Total number of years of education"
  /MV134    "NA - De facto place of residence"
  /MV135    "Usual resident or visitor"
  /MV136    "Number of household members (total listed)"
  /MV138    "Number of eligible men in household (de facto)"
  /MV149    "Educational attainment"
  /MV150    "Relationship to household head"
  /MV151    "Sex of household head"
  /MV152    "Age of household head"
  /MV155    "Literacy"
  /MV156    "NA - Ever participated in a literacy program (excluding primary school)"
  /MV157    "Frequency of reading newspaper or magazine"
  /MV158    "Frequency of listening to radio"
  /MV159    "Frequency of watching television"
  /MV167    "NA - Times away from home in last 12 months"
  /MV168    "NA - Away for more than one month in last 12 months"
  /MV190    "Wealth index"
  /MV191    "Wealth index factor score (5 decimals)"
  /MV201    "Total children ever born"
  /MV202    "Sons at home"
  /MV203    "Daughters at home"
  /MV204    "Sons elsewhere"
  /MV205    "Daughters elsewhere"
  /MV206    "Sons who have died"
  /MV207    "Daughters who have died"
  /MV212    "Age of respondent at 1st birth"
  /MV213    "Partner currently pregnant"
  /MV217    "Knowledge of ovulatory cycle"
  /MV218    "Number of living children"
  /MV225    "NA - Most recent pregnancy wanted"
  /MV245    "Number of women fathered children with"
  /MV246    "NA - Married to mother when first child was born"
  /MV247    "Age of most recent child"
  /MV248    "Antenatal check-ups for the mother of most recent child"
  /MV249    "Respondent present during check-ups for most recent child"
  /MV250    "Place of birth of most recent child"
  /MV251    "NA - Reason for not delivering most recent child in health facility"
  /MV252    "Amount a child should drink, when that child has diarrhea"
  /MV301    "Knowledge of any contraceptive method"
  /MV302    "NA - Ever use of any contraceptive method"
  /M304A$01 "Type of contraceptive method"
  /M304A$02 "Type of contraceptive method"
  /M304A$03 "Type of contraceptive method"
  /M304A$04 "Type of contraceptive method"
  /M304A$05 "Type of contraceptive method"
  /M304A$06 "Type of contraceptive method"
  /M304A$07 "Type of contraceptive method"
  /M304A$08 "Type of contraceptive method"
  /M304A$09 "Type of contraceptive method"
  /M304A$10 "Type of contraceptive method"
  /M304A$11 "Type of contraceptive method"
  /M304A$12 "Type of contraceptive method"
  /M304A$13 "Type of contraceptive method"
  /M304A$14 "Type of contraceptive method"
  /M304A$15 "Type of contraceptive method"
  /M304A$16 "Type of contraceptive method"
  /M304A$17 "Type of contraceptive method"
  /M304A$18 "Type of contraceptive method"
  /M304A$19 "Type of contraceptive method"
  /M304A$20 "Type of contraceptive method"
  /MV304$01 "Knows contraceptive method"
  /MV304$02 "Knows contraceptive method"
  /MV304$03 "Knows contraceptive method"
  /MV304$04 "Knows contraceptive method"
  /MV304$05 "Knows contraceptive method"
  /MV304$06 "Knows contraceptive method"
  /MV304$07 "Knows contraceptive method"
  /MV304$08 "Knows contraceptive method"
  /MV304$09 "Knows contraceptive method"
  /MV304$10 "Knows contraceptive method"
  /MV304$11 "Knows contraceptive method"
  /MV304$12 "Knows contraceptive method"
  /MV304$13 "Knows contraceptive method"
  /MV304$14 "Knows contraceptive method"
  /MV304$15 "Knows contraceptive method"
  /MV304$16 "Knows contraceptive method"
  /MV304$17 "Knows contraceptive method"
  /MV304$18 "Knows contraceptive method"
  /MV304$19 "Knows contraceptive method"
  /MV304$20 "Knows contraceptive method"
  /MV305$01 "NA - Ever used contraceptive method"
  /MV305$02 "NA - Ever used contraceptive method"
  /MV305$03 "NA - Ever used contraceptive method"
  /MV305$04 "NA - Ever used contraceptive method"
  /MV305$05 "NA - Ever used contraceptive method"
  /MV305$06 "NA - Ever used contraceptive method"
  /MV305$07 "NA - Ever used contraceptive method"
  /MV305$08 "NA - Ever used contraceptive method"
  /MV305$09 "NA - Ever used contraceptive method"
  /MV305$10 "NA - Ever used contraceptive method"
  /MV305$11 "NA - Ever used contraceptive method"
  /MV305$12 "NA - Ever used contraceptive method"
  /MV305$13 "NA - Ever used contraceptive method"
  /MV305$14 "NA - Ever used contraceptive method"
  /MV305$15 "NA - Ever used contraceptive method"
  /MV305$16 "NA - Ever used contraceptive method"
  /MV305$17 "NA - Ever used contraceptive method"
  /MV305$18 "NA - Ever used contraceptive method"
  /MV305$19 "NA - Ever used contraceptive method"
  /MV305$20 "NA - Ever used contraceptive method"
  /MV307$01 "Contraceptive method currently used"
  /MV307$02 "Contraceptive method currently used"
  /MV307$03 "Contraceptive method currently used"
  /MV307$04 "Contraceptive method currently used"
  /MV307$05 "Contraceptive method currently used"
  /MV307$06 "Contraceptive method currently used"
  /MV307$07 "Contraceptive method currently used"
  /MV307$08 "Contraceptive method currently used"
  /MV307$09 "Contraceptive method currently used"
  /MV307$10 "Contraceptive method currently used"
  /MV307$11 "Contraceptive method currently used"
  /MV307$12 "Contraceptive method currently used"
  /MV307$13 "Contraceptive method currently used"
  /MV307$14 "Contraceptive method currently used"
  /MV307$15 "Contraceptive method currently used"
  /MV307$16 "Contraceptive method currently used"
  /MV307$17 "Contraceptive method currently used"
  /MV307$18 "Contraceptive method currently used"
  /MV307$19 "Contraceptive method currently used"
  /MV307$20 "Contraceptive method currently used"
  /MV312    "Current contraceptive method"
  /MV313    "Current contraceptive by method type"
  /MV323A   "Brand of condom used"
  /MV325B   "NA - Cost of condoms (in CURRENCY) last time obtained"
  /MV372A   "NA - Interviewer shown condom package"
  /MV384A   "On radio heard about Family Planning in the last few months"
  /MV384B   "On TV saw about Family Planning in the last few months"
  /MV384C   "In newspaper read about Family Planning in the last few months"
  /MV395    "Discussed Family Planning with health worker in last few months"
  /MV396    "NA - Possible for a breastfeeding woman to get pregnant"
  /MV3A09B  "NA - Number of condoms did get last time"
  /MV3B17   "Source of condoms"
  /MV3B25A  "Contraception is woman's business, man should not worry"
  /MV3B25B  "Women who use contraception become promiscuous"
  /MV463A   "Smokes cigarettes"
  /MV463B   "Smokes pipe"
  /MV463C   "Uses chewing tobacco"
  /MV463D   "Uses snuff"
  /MV463E   "NA - Smokes CS"
  /MV463F   "NA - Smokes CS"
  /MV463G   "NA - Smokes CS"
  /MV463X   "Smokes other"
  /MV463Z   "Smokes nothing"
  /MV464    "Number of cigarettes in last 24 hours"
  /MV474    "NA - Heard of tuberculosis or TB"
  /MV474A   "NA - Tuberculosis spread by: air through coughing or sneezing"
  /MV474B   "NA - Tuberculosis spread by: sharing utensils"
  /MV474C   "NA - Tuberculosis spread by: touching a person with TB"
  /MV474D   "NA - Tuberculosis spread by: food"
  /MV474E   "NA - Tuberculosis spread by: sexual contact"
  /MV474F   "NA - Tuberculosis spread by: mosquito bites"
  /MV474G   "NA - Tuberculosis spread by: CS"
  /MV474H   "NA - Tuberculosis spread by: CS"
  /MV474I   "NA - Tuberculosis spread by: CS"
  /MV474J   "NA - Tuberculosis spread by: CS"
  /MV474X   "NA - Tuberculosis spread by: other"
  /MV474Z   "NA - Don't know how tuberculosis is spread"
  /MV475    "NA - Tuberculosis can be cured"
  /MV476    "NA - Would want tuberculosis infection in family to remain secret"
  /MV477    "Number of injections in last 12 months"
  /MV478    "Number of injections administered by a health worker"
  /MV479    "NA - Place where given injection by health worker"
  /MV480    "Syringe and needle from new, unopened package"
  /MV481    "Covered by health insurance"
  /MV481A   "Health insurance type: mutual/community organization"
  /MV481B   "Health insurance type: provided by employer"
  /MV481C   "Health insurance type: social security"
  /MV481D   "Health insurance type: private/commercially purchased"
  /MV481E   "NA - Health insurance type: CS"
  /MV481F   "NA - Health insurance type: CS"
  /MV481G   "NA - Health insurance type: CS"
  /MV481H   "NA - Health insurance type: CS"
  /MV481X   "Health insurance type: other"
  /MV482A   "NA - Arrange care of biological children under age 18"
  /MV482B   "NA - Primary caregiver of children under age 18"
  /MV482C   "NA - Arrange care of non-biological children < 18"
  /MV483    "Respondent circumcised"
  /MV483A   "Age at circumcision"
  /MV483B   "Who performed the circumcision"
  /MV483C   "Place where circumcision was done"
  /MV501    "Current marital status"
  /MV502    "Currently/formerly/never in union"
  /MV503    "Number of unions"
  /MV504    "Currently residing with wife/partner"
  /MV505    "NA - Number of wives/partners"
  /MV507    "Month of first cohabitation"
  /MV508    "Year of first cohabitation"
  /MV509    "Date of first cohabitation (CMC)"
  /MV510    "Completeness of date information in MV509"
  /MV511    "Age at first cohabitation"
  /MV512    "Years since first cohabitation"
  /MV513    "Cohabitation duration (grouped)"
  /MV525    "Age at first sex"
  /MV527    "Time since last sex"
  /MV528    "Time since last sex (in days)"
  /MV529    "Time since last sex (in months)"
  /MV531    "Age at first sex (imputed)"
  /MV532    "Flag for MV531"
  /MV535    "Ever been married or in union"
  /MV536    "Recent sexual activity"
  /MV541    "NA - Intends to wait until marriage to have sex"
  /MV602    "Fertility preference"
  /MV603    "Preferred waiting time for birth of a/another child"
  /MV604    "Preferred waiting time for birth of a/another child (grouped)"
  /MV605    "Desire for more children"
  /MV613    "Ideal number of children"
  /MV614    "Ideal number of children (grouped)"
  /MV616    "Desired time for future birth"
  /MV621    "NA - Wife's desire for children"
  /MV627    "Ideal number of boys"
  /MV628    "Ideal number of girls"
  /MV629    "Ideal number of either sex"
  /MV631    "NA - Problem if wife became pregnant"
  /MV633A   "NA - Wife justified refusing sex: husband has STI"
  /MV633B   "Wife justified refusing sex: husband has other women"
  /MV633C   "NA - Wife justified refusing sex: recent birth"
  /MV633D   "NA - Wife justified refusing sex: tired, not in mood"
  /MV633E   "NA - Wife justified refusing sex: CS reason"
  /MV633F   "NA - Wife justified refusing sex: CS reason"
  /MV633G   "NA - Wife justified refusing sex: CS reason"
  /MV634A   "NA - Wife refuses to have sex, husband has right to: get angry"
  /MV634B   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
  /MV634C   "NA - Wife refuses to have sex, husband has right to: use force for sex"
  /MV634D   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
  /MV714    "Currently working"
  /MV714A   "Have a job, but currently absent"
  /MV716    "Occupation"
  /MV717    "Occupation (grouped)"
  /MV719    "Works for family, others, self"
  /MV721    "NA - Works at home or away"
  /MV731    "Worked in last 12 months"
  /MV732    "Employment all year/seasonal"
  /MV739    "Person who usually decides how to spend respondent's earnings"
  /MV740    "NA - Type of land where respondent works"
  /MV741    "Type of earnings from respondent's work"
  /MV743A   "Person who should have greater say: respondent's health care"
  /MV743B   "Person who should have greater say: large household purchases"
  /MV743C   "NA - Person who should have greater say: daily household purchases"
  /MV743D   "NA - Person who should have greater say: visits to family or relatives"
  /MV743E   "NA - Person who should have greater say: food to be cooked each day"
  /MV743F   "Person who should have greater say: deciding what to do with money wife earns"
  /MV743G   "NA - Person who should have greater say: deciding how many children to have"
  /MV744A   "Beating justified: wife goes out without telling husband"
  /MV744B   "Beating justified: wife neglects the children"
  /MV744C   "Beating justified: wife argues with husband"
  /MV744D   "Beating justified: wife refuses to have sex with husband"
  /MV744E   "Beating justified: wife burns food"
  /MV745A   "Owns a house alone or jointly"
  /MV745B   "Owns land alone or jointly"
  /MV747A   "NA - Childbearing is a woman's concern"
  /MV747B   "NA - Important for mother/child health to get assistance at delivery"
  /MV750    "Ever heard of a Sexually Transmitted Infection (STI)"
  /MV751    "Ever heard of AIDS"
  /MV754BP  "NA - Reduce risk of getting HIV: do not have sex at all"
  /MV754CP  "Reduce risk of getting HIV: always use condoms during sex"
  /MV754DP  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
  /MV754JP  "Can get HIV from mosquito bites"
  /MV754WP  "Can get HIV by sharing food with person who has AIDS"
  /MV756    "A healthy looking person can have HIV"
  /MV761    "Condom used during last sex with most recent partner"
  /MV761B   "Condom used during last sex with 2nd to most recent partner"
  /MV761C   "Condom used during last sex with 3rd to most recent partner"
  /MV762AA  "Source for condoms: government hospital"
  /MV762AB  "Source for condoms: health center"
  /MV762AC  "Source for condoms: health center type A"
  /MV762AD  "Source for condoms: health center type B"
  /MV762AE  "Source for condoms: health stand (open)"
  /MV762AF  "Source for condoms: health stand (closed)"
  /MV762AG  "Source for condoms: health stand strengthened (PSF)"
  /MV762AH  "Source for condoms: convergence center"
  /MV762AI  "Source for condoms: other public and rest of public sector"
  /MV762AJ  "Source for condoms: private hospital/clinic"
  /MV762AK  "Source for condoms: pharmacy"
  /MV762AL  "Source for condoms: private doctor"
  /MV762AM  "Source for condoms: Family protection association (APROFAM)"
  /MV762AN  "Source for condoms: Social Security (IGSS)"
  /MV762AO  "Source for condoms: Other private sector"
  /MV762AP  "NA - Source for condoms: CS private"
  /MV762AQ  "NA - Source for condoms: CS private"
  /MV762AR  "NA - Source for condoms: CS private"
  /MV762AS  "Source for condoms: Midwife/healer/traditional birth attendant"
  /MV762AT  "Source for condoms: Convenience store"
  /MV762AU  "Source for condoms: health promoter"
  /MV762AV  "Source for condoms: health guardian"
  /MV762AW  "NA - Source for condoms: CS other"
  /MV762AX  "Source for condoms: other"
  /MV762AZ  "Don't know any source for condoms"
  /MV762BA  "NA - Source for female condoms: government hospital"
  /MV762BB  "NA - Source for female condoms: CS public"
  /MV762BC  "NA - Source for female condoms: CS public"
  /MV762BD  "NA - Source for female condoms: CS public"
  /MV762BE  "NA - Source for female condoms: CS public"
  /MV762BF  "NA - Source for female condoms: CS public"
  /MV762BG  "NA - Source for female condoms: CS public"
  /MV762BH  "NA - Source for female condoms: CS public"
  /MV762BI  "NA - Source for female condoms: CS public"
  /MV762BJ  "NA - Source for female condoms: private hospital/clinic"
  /MV762BK  "NA - Source for female condoms: pharmacy"
  /MV762BL  "NA - Source for female condoms: private doctor"
  /MV762BM  "NA - Source for female condoms: CS private"
  /MV762BN  "NA - Source for female condoms: CS private"
  /MV762BO  "NA - Source for female condoms: CS private"
  /MV762BP  "NA - Source for female condoms: CS private"
  /MV762BQ  "NA - Source for female condoms: CS private"
  /MV762BR  "NA - Source for female condoms: CS private"
  /MV762BS  "NA - Source for female condoms: CS other"
  /MV762BT  "NA - Source for female condoms: CS other"
  /MV762BU  "NA - Source for female condoms: CS other"
  /MV762BV  "NA - Source for female condoms: CS other"
  /MV762BW  "NA - Source for female condoms: CS other"
  /MV762BX  "NA - Source for female condoms: other"
  /MV762BZ  "NA - Don't know any source for female condoms"
  /MV763A   "Had any STI in last 12 months"
  /MV763B   "Had genital sore/ulcer in last 12 months"
  /MV763C   "Had genital discharge in last 12 months"
  /MV763D   "NA - Had CS STI in last 12 months"
  /MV763E   "NA - Had CS STI in last 12 months"
  /MV763F   "NA - Had CS STI in last 12 months"
  /MV763G   "NA - Had CS STI in last 12 months"
  /MV766A   "Number of sex partners, excluding spouse, in last 12 months"
  /MV766B   "Number of sex partners, including spouse, in last 12 months"
  /MV767A   "Relationship with most recent sex partner"
  /MV767B   "Relationship with 2nd to most recent sex partner"
  /MV767C   "Relationship with 3rd to most recent sex partner"
  /MV768A   "Length of time had sex relations with most recent partner"
  /MV768B   "Length of time had sex relations with 2nd to most recent partner"
  /MV768C   "Length of time had sex relations with 3rd to most recent partner"
  /MV769    "Can get a condom"
  /MV769A   "NA - Can get a female condom"
  /MV770    "Sought advice/treatment for last STI infection"
  /MV770A   "Sought STI advice/treatment from: government hospital"
  /MV770B   "Sought STI advice/treatment from: health center"
  /MV770C   "Sought STI advice/treatment from: health center type A"
  /MV770D   "Sought STI advice/treatment from: health center type B"
  /MV770E   "NA - Sought STI advice/treatment from: health stand open"
  /MV770F   "NA - Sought STI advice/treatment from: health stand closed"
  /MV770G   "NA - Sought STI advice/treatment from: health strengthened"
  /MV770H   "NA - Sought STI advice/treatment from: convergence center"
  /MV770I   "Sought STI advice/treatment from: other public and rest of public sector"
  /MV770J   "Sought STI advice/treatment from: private hospital/clinic"
  /MV770K   "Sought STI advice/treatment from: pharmacy"
  /MV770L   "Sought STI advice/treatment from: doctor's office"
  /MV770M   "Sought STI advice/treatment from: Family protection association (APROFAM)"
  /MV770N   "Sought STI advice/treatment from: IGSS"
  /MV770O   "Sought STI advice/treatment from: Other private sector"
  /MV770P   "NA - Sought STI advice/treatment from: CS private"
  /MV770Q   "NA - Sought STI advice/treatment from: CS private"
  /MV770R   "NA - Sought STI advice/treatment from: CS private"
  /MV770S   "NA - Sought STI advice/treatment from: CS private"
  /MV770T   "NA - Sought STI advice/treatment from: CS private"
  /MV770U   "NA - Sought STI advice/treatment from: CS other"
  /MV770V   "NA - Sought STI advice/treatment from: CS other"
  /MV770W   "NA - Sought STI advice/treatment from: CS other"
  /MV770X   "Sought STI advice/treatment from: Other and correctional institution"
  /MV774A   "HIV transmitted during pregnancy"
  /MV774B   "HIV transmitted during delivery"
  /MV774C   "HIV transmitted by breastfeeding"
  /MV775    "NA - Knows someone who has, or is suspected of having, HIV"
  /MV777    "Would want HIV infection in family to remain secret"
  /MV778    "Willing to care for relative with AIDS"
  /MV779    "A female teacher infected with HIV, but is not sick, should be allowed to continue teaching"
  /MV780    "Children should be taught about condoms to avoid AIDS"
  /MV781    "Ever been tested for HIV"
  /MV783    "Know a place to get HIV test"
  /MV784A   "Place for HIV test: government hospital"
  /MV784B   "Place for HIV test: health center"
  /MV784C   "Place for HIV test: health center type A"
  /MV784D   "Place for HIV test: health center type B"
  /MV784E   "NA - Place for HIV test: CS public"
  /MV784F   "NA - Place for HIV test: CS public"
  /MV784G   "NA - Place for HIV test: CS public"
  /MV784H   "NA - Place for HIV test: CS public"
  /MV784I   "Place for HIV test: other public and rest of public sector"
  /MV784J   "Place for HIV test: private hospital/clinic"
  /MV784K   "NA - Place for HIV test: CS private"
  /MV784L   "Place for HIV test: doctor's office"
  /MV784M   "Place for HIV test: Family protection association (APROFAM)"
  /MV784N   "Place for HIV test: Social Security (IGSS)"
  /MV784O   "Place for HIV test: Other private"
  /MV784P   "NA - Place for HIV test: CS private"
  /MV784Q   "NA - Place for HIV test: CS private"
  /MV784R   "NA - Place for HIV test: CS private"
  /MV784S   "NA - Place for HIV test: CS other"
  /MV784T   "NA - Place for HIV test: CS other"
  /MV784U   "NA - Place for HIV test: CS other"
  /MV784V   "NA - Place for HIV test: CS other"
  /MV784X   "Place for HIV test: other and correctional institution"
  /MV785    "Heard about other STIs"
  /MV791    "Have ever paid anyone in exchange for sex"
  /MV793    "Paid for sex in last 12 months"
  /MV793A   "Condom used last time paid for sex in last 12 months"
  /MV793B   "Condom used every time paid for sex in last 12 months"
  /MV820    "NA - Condom used at first sex"
  /MV822    "Wife justified asking husband to use condom if he has STI"
  /MV823    "Can get HIV by witchcraft or supernatural means"
  /MV824    "Drugs to avoid HIV transmission to baby during pregnancy"
  /MV825    "Would buy vegetables from vendor with HIV"
  /MV826    "NA - Last time tested for HIV"
  /MV826A   "Months ago most recent HIV test"
  /MV827    "NA - Last HIV test: on your own, offered or required"
  /MV828    "Received result from last HIV test"
  /MV829    "Place where last HIV test was taken"
  /MV832B   "Time since last sex with 2nd to most recent partner"
  /MV832C   "Time since last sex with 3rd to most recent partner"
  /MV833A   "Used condom every time had sex with most recent partner in last 12 months"
  /MV833B   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
  /MV833C   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
  /MV834A   "Age of most recent partner"
  /MV834B   "Age of 2nd to most recent partner"
  /MV834C   "Age of 3rd to most recent partner"
  /MV835A   "NA - Alcohol consumption at last sex with most recent partner"
  /MV835B   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
  /MV835C   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
  /MV836    "Total lifetime number of sex partners"
  /MV837    "NA - Heard of drugs to help HIV infected people live longer"
  /MV844    "NA - Knows someone denied health services for having, or suspected of having, HIV; in last 12 months"
  /MV845    "NA - Knows someone denied social event for having, or suspected of having, HIV; in last 12 months"
  /MV846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in last 12 months"
  /MV847    "NA - People with HIV should be ashamed of themselves"
  /MV848    "NA - People with HIV should be blamed for bringing disease to community"
  /MV849    "NA - Children 12-14 should be taught to wait for sex until marriage"
  /MV851A   "NA - Young men should wait for sex until marriage"
  /MV851B   "NA - Most young men wait for sex until marriage"
  /MV851C   "NA - Unmarried sexually active men should have only one partner"
  /MV851D   "NA - Most unmarried sexually active men have only one partner"
  /MV851E   "NA - Married men should only have sex with their wives"
  /MV851F   "NA - Most married men only have sex with their wives"
  /MV851G   "NA - Young women should wait for sex until marriage"
  /MV851H   "NA - Most young women wait for sex until marriage"
  /MV851I   "NA - Unmarried sexually active women should have only one partner"
  /MV851J   "NA - Most unmarried sexually active women have only one partner"
  /MV851K   "NA - Married women should only have sex with their husbands"
  /MV851L   "NA - Most married women only have sex with their husbands"
  /MV852A   "How long ago first had sex with most recent partner"
  /MV852B   "How long ago first had sex with 2nd most recent partner"
  /MV852C   "How long ago first had sex with 3rd most recent partner"
  /MV853A   "Times in last 12 months had sex with most recent partner"
  /MV853B   "Times in last 12 months had sex with 2nd most recent partner"
  /MV853C   "Times in last 12 months had sex with 3rd most recent partner"
  /MV854A   "Concurrent sexual partners"
  /MV854B   "Cumulative concurrent sexual partners"
  /SMDEPTO  "Department"
  /SMDEPTO2 "Department"
  /SMOEDIT  "Office editor"
  /SMKEYER  "Keyer"
  /SMKEYER2 "Verification keyer"
  /SMILANG  "Interview language"
  /SMQLANG  "Questionnaire language"
  /SMTRANS  "Translator used"
  /MV044    "Selected for Domestic Violence module"
  /SMEDUC   "Highest education level attended"
  /SMETID   "Ethnicity by auto-identification"
  /SMETOB   "Ethnicity by observation"
  /SM105    "Highest level attended"
  /SM106    "Highest grade completed"
  /SM114    "Language learned to speak"
  /SM115    "Language speaks at home"
  /SM116    "Any HH member speaks another language"
  /SM117A   "Language spoken by other HH member: Spanish"
  /SM117B   "Language spoken by other HH member: Kaqchikel"
  /SM117C   "Language spoken by other HH member: Q'eqchi'"
  /SM117D   "Language spoken by other HH member: K'iche'"
  /SM117E   "Language spoken by other HH member: Mam"
  /SM117F   "Language spoken by other HH member: Poqomchi'"
  /SM117G   "Language spoken by other HH member: Tzu'utujil"
  /SM117H   "Language spoken by other HH member: Q'anjob'al"
  /SM117I   "Language spoken by other HH member: Ch'orti'"
  /SM117J   "Language spoken by other HH member: Poqomam"
  /SM117K   "Language spoken by other HH member: Achi"
  /SM117L   "Language spoken by other HH member: Akateko"
  /SM117M   "Language spoken by other HH member: Awakateko"
  /SM117N   "Language spoken by other HH member: Chalchiteko"
  /SM117O   "Language spoken by other HH member: Chuj"
  /SM117P   "Language spoken by other HH member: Itza'"
  /SM117Q   "Language spoken by other HH member: Ixil"
  /SM117R   "Language spoken by other HH member: Jakalteko (popti')"
  /SM117S   "Language spoken by other HH member: Mopan"
  /SM117T   "Language spoken by other HH member: Sakapulteko"
  /SM117U   "Language spoken by other HH member: Sipakapense"
  /SM117V   "Language spoken by other HH member: Tektiteko"
  /SM117W   "Language spoken by other HH member: Uspanteko"
  /SM117X   "Language spoken by other HH member: Other"
  /SM119    "Maya linguistic community"
  /SM120    "Considered as Indian"
  /SM219    "Place of birth of youngest son"
  /SM222    "Knowledge of ovulatory cycle"
  /SM303D   "In Internet read about Family Planning in the last few months"
  /SM308L   "Source of condoms: Outpatient care center (CENAPA)"
  /SM308M   "Source of condoms: Permanent care center (CAP)"
  /SM308N   "Source of condoms: Maternity"
  /SM308O   "Source of condoms: Mobile clinic"
  /SM308P   "Source of condoms: Minimum emergency center (CUM)"
  /SM308Q   "Source of condoms: Peripheral clinic"
  /SM308R   "Source of condoms: Neurological rehabilitation center (CRN)"
  /SM308S   "Source of condoms: Minimum unit"
  /SM308T   "Source of condoms: Other public place"
  /SM423    "Knows if there are men who have more than one woman in the community"
  /SM433    "Source of condoms"
  /SM616A   "Presence of children < 10 for 'husband beating justified' questions"
  /SM616B   "Presence of wife/partner for 'husband beating justified' questions"
  /SM616C   "Presence of other males for 'husband beating justified' questions"
  /SM616D   "Presence of other females for 'husband beating justified' questions"
  /SM708K   "Sought STI advice/treatment from: Maternal/child care center (CAIMI)"
  /SM708L   "Sought STI advice/treatment from: Outpatient care center (CENAPA)"
  /SM708M   "Sought STI advice/treatment from: Permanent care center (CAP)"
  /SM708N   "Sought STI advice/treatment from: Maternity"
  /SM708O   "Sought STI advice/treatment from: Mobile clinic"
  /SM708P   "Sought STI advice/treatment from: Minimum emergency center (CUM)"
  /SM708Q   "Sought STI advice/treatment from: Peripheral clinic"
  /SM708R   "Sought STI advice/treatment from: Neurological rehabilitation center (CRN)"
  /SM708S   "Sought STI advice/treatment from: Minimum unit"
  /SM708T   "Sought STI advice/treatment from: Other public place"
  /SM708X   "Sought STI advice/treatment from: Other"
  /SM708JJ  "Sought STI advice/treatment from: Correctional institution"
  /SM711    "Heard about the infection through HIV"
  /SM726    "Received counseling before being tested"
  /SM727    "Received counseling after being tested"
  /SM728    "Place where last HIV test was taken"
  /SM730K   "Place for HIV test: Maternal/child care center (CAIMI)"
  /SM730L   "Place for HIV test: Outpatient care center (CENAPA)"
  /SM730M   "Place for HIV test: Permanent care center (CAP)"
  /SM730N   "Place for HIV test: Maternity"
  /SM730O   "Place for HIV test: Mobile clinic"
  /SM730P   "Place for HIV test: Minimum emergency center (CUM)"
  /SM730Q   "Place for HIV test: Peripheral clinic"
  /SM730R   "Place for HIV test: Neurological rehabilitation center (CRN)"
  /SM730S   "Place for HIV test: Minimum unit"
  /SM730T   "Place for HIV test: Other public place"
  /SM730X   "Place for HIV test: Other"
  /SM730JJ  "Place for HIV test: Correctional institution"
  /SM737    "Ever had sexual intercourse with a man"
  /SM738    "Time since last sexual intercourse with a man"
  /SM739    "Condom used during sexual intercourse with a man in last 12 months"
  /SM807    "Place where circumcision was done"
  /SM812    "Drank alcohol in last 30 days"
  /SM813    "Times drank alcohol in last 30 days"
  /SM814    "Got drunk in last 30 days"
  /SM815    "Times got drunk in last 30 days"
  /SM816AA  "Language spoken by doctors in hospital/health center: Spanish"
  /SM816AB  "Language spoken by doctors in hospital/health center: Kaqchikel"
  /SM816AC  "Language spoken by doctors in hospital/health center: Q'eqchi'"
  /SM816AD  "Language spoken by doctors in hospital/health center: K'iche'"
  /SM816AE  "Language spoken by doctors in hospital/health center: Mam"
  /SM816AF  "Language spoken by doctors in hospital/health center: Poqomchi'"
  /SM816AG  "Language spoken by doctors in hospital/health center: Tzu'utujil"
  /SM816AH  "Language spoken by doctors in hospital/health center: Q'anjob'al"
  /SM816AI  "Language spoken by doctors in hospital/health center: Ch'orti'"
  /SM816AJ  "Language spoken by doctors in hospital/health center: Poqomam"
  /SM816AK  "Language spoken by doctors in hospital/health center: Achi"
  /SM816AL  "Language spoken by doctors in hospital/health center: Akateko"
  /SM816AM  "Language spoken by doctors in hospital/health center: Awakateko"
  /SM816AN  "Language spoken by doctors in hospital/health center: Chalchiteko"
  /SM816AO  "Language spoken by doctors in hospital/health center: Chuj"
  /SM816AP  "Language spoken by doctors in hospital/health center: Itza'"
  /SM816AQ  "Language spoken by doctors in hospital/health center: Ixil"
  /SM816AR  "Language spoken by doctors in hospital/health center: Jakalteko (popti')"
  /SM816AS  "Language spoken by doctors in hospital/health center: Mopan"
  /SM816AT  "Language spoken by doctors in hospital/health center: Sakapulteko"
  /SM816AU  "Language spoken by doctors in hospital/health center: Sipakapense"
  /SM816AV  "Language spoken by doctors in hospital/health center: Tektiteko"
  /SM816AW  "Language spoken by doctors in hospital/health center: Uspanteko"
  /SM816AX  "Language spoken by doctors in hospital/health center: Other"
  /SM816BA  "Language spoken by nurses in hospital/health center: Spanish"
  /SM816BB  "Language spoken by nurses in hospital/health center: Kaqchikel"
  /SM816BC  "Language spoken by nurses in hospital/health center: Q'eqchi'"
  /SM816BD  "Language spoken by nurses in hospital/health center: K'iche'"
  /SM816BE  "Language spoken by nurses in hospital/health center: Mam"
  /SM816BF  "Language spoken by nurses in hospital/health center: Poqomchi'"
  /SM816BG  "Language spoken by nurses in hospital/health center: Tzu'utujil"
  /SM816BH  "Language spoken by nurses in hospital/health center: Q'anjob'al"
  /SM816BI  "Language spoken by nurses in hospital/health center: Ch'orti'"
  /SM816BJ  "Language spoken by nurses in hospital/health center: Poqomam"
  /SM816BK  "Language spoken by nurses in hospital/health center: Achi"
  /SM816BL  "Language spoken by nurses in hospital/health center: Akateko"
  /SM816BM  "Language spoken by nurses in hospital/health center: Awakateko"
  /SM816BN  "Language spoken by nurses in hospital/health center: Chalchiteko"
  /SM816BO  "Language spoken by nurses in hospital/health center: Chuj"
  /SM816BP  "Language spoken by nurses in hospital/health center: Itza'"
  /SM816BQ  "Language spoken by nurses in hospital/health center: Ixil"
  /SM816BR  "Language spoken by nurses in hospital/health center: Jakalteko (popti')"
  /SM816BS  "Language spoken by nurses in hospital/health center: Mopan"
  /SM816BT  "Language spoken by nurses in hospital/health center: Sakapulteko"
  /SM816BU  "Language spoken by nurses in hospital/health center: Sipakapense"
  /SM816BV  "Language spoken by nurses in hospital/health center: Tektiteko"
  /SM816BW  "Language spoken by nurses in hospital/health center: Uspanteko"
  /SM816BX  "Language spoken by nurses in hospital/health center: Other"
  /SM819A   "Wears typical costume"
  /SM819B   "Translator used"
  /SM819C   "Speaks Maya language"
  /SM905A2  "Number of times was humiliated by wife/partner in the last 12 months"
  /SM905B2  "Number of times was threatened with harm by wife/partner in the last 12 months"
  /SM905C2  "Number of times was insulted or made to feel bad by wife/partner in the last 12 months"
  /SM906A2  "Number of times was pushed, shook or had something thrown by wife/partner in the last 12 months"
  /SM906B2  "Number of times was slapped by wife/partner in the last 12 months"
  /SM906C2  "Number of times had arm twisted or hair pulled by wife/partner in the last 12 months"
  /SM906D2  "Number of times was punched with fist or hit by something harmful by wife/partner in the last 12 months"
  /SM906E2  "Number of times was kicked or dragged by wife/partner in the last 12 months"
  /SM906F2  "Number of times was strangled or burnt by wife/partner in the last 12 months"
  /SM906G2  "Number of times was threatened with knife/gun or other weapon by wife/partner in the last 12 months"
  /SM906H2  "Number of times was physically forced into unwanted sex by wife/partner in the last 12 months"
  /SM906I2  "Number of times was physically forced to perform sexual acts respondent didn't want to by wife/partner in the last 12 months"
  /SM911    "Frequency of physically hurting wife/partner in last 12 months"
  /SM916B   "Previous wife: ever obliged him to have intercourse or perform some sexual acts"
  /SM916C   "Previous wife: ever obliged or forced him to perform some sexual acts"
  /SM919    "Frequency of being hit in last 12 months by other than wife/partner"
  /SM921A   "Anyone (besides partner) ever forced respondent to have intercourse"
  /SM921B   "Anyone ever forced respondent to have intercourse"
  /SM922A   "Person who forced respondent into sexual act: Current wife/partner"
  /SM922B   "Person who forced respondent into sexual act: Former wife/partner"
  /SM922C   "Person who forced respondent into sexual act: Mother/step mother"
  /SM922D   "Person who forced respondent into sexual act: Father/step father"
  /SM922E   "Person who forced respondent into sexual act: Sister/brother"
  /SM922F   "Person who forced respondent into sexual act: Daughter/son"
  /SM922G   "Person who forced respondent into sexual act: Other relative"
  /SM922H   "Person who forced respondent into sexual act: Current girlfriend"
  /SM922I   "Person who forced respondent into sexual act: Former girlfriend"
  /SM922K   "Person who forced respondent into sexual act: Mother/father in law"
  /SM922L   "Person who forced respondent into sexual act: Partner's relative"
  /SM922M   "Person who forced respondent into sexual act: Teacher"
  /SM922N   "Person who forced respondent into sexual act: Employer/co-worker"
  /SM922O   "Person who forced respondent into sexual act: Police/soldier"
  /SM922P   "Person who forced respondent into sexual act: Priest/Religious leader"
  /SM922Q   "Person who forced respondent into sexual act: Strange"
  /SM922X   "Person who forced respondent into sexual act: Other"
  /SM928AA  "Person respondent went to seek help: General attorney"
  /SM928BB  "Person respondent went to seek help: Human rights attorney"
  /SM928CC  "Person respondent went to seek help: Popular buffet"
  /SM929    "Ever made a complaint for the violence"
  /SM932D   "Interview interrupted: other persons' presence"
  /MD005    "Weight for Domestic Violence (6 decimals)"
  /MD101A   "Wife/partner jealous if respondent talks with other women"
  /MD101B   "Wife/partner accuses respondent of unfaithfulness"
  /MD101C   "Wife/partner does not permit respondent to meet male friends"
  /MD101D   "Wife/partner tries to limit respondent's contact with family"
  /MD101E   "Wife/partner insists on knowing where respondent is"
  /MD101F   "Wife/partner doesn't trust respondent with money"
  /MD101G   "NA - CS control issue"
  /MD101H   "NA - CS control issue"
  /MD101I   "NA - CS control issue"
  /MD101J   "NA - CS control issue"
  /MD102    "Number of control issues answered 'Yes'  (MD101x = 1)"
  /MD103A   "Ever been humiliated by wife/partner"
  /MD103B   "Ever been threatened with harm by wife/partner"
  /MD103C   "Ever been insulted or made to feel bad by wife/partner"
  /MD103D   "NA - Ever CS emotional abuse by wife/partner"
  /MD103E   "NA - Ever CS emotional abuse by wife/partner"
  /MD103F   "NA - Ever CS emotional abuse by wife/partner"
  /MD104    "Experienced any emotional violence (MD103x series)"
  /MD105A   "Ever been pushed, shook or had something thrown by wife/partner"
  /MD105B   "Ever been slapped by wife/partner"
  /MD105C   "Ever been punched with fist or hit by something harmful by wife/partner"
  /MD105D   "Ever been kicked or dragged by wife/partner"
  /MD105E   "Ever been strangled or burnt by wife/partner"
  /MD105F   "Ever been threatened with knife/gun or other weapon by wife/partner"
  /MD105G   "NA - Ever CS physical violence by wife/partner"
  /MD105H   "Ever been physically forced into unwanted sex by wife/partner"
  /MD105I   "NA - Ever been forced into other unwanted sexual acts by wife/partner"
  /MD105J   "Ever had arm twisted or hair pulled by wife/partner"
  /MD105K   "Ever been physically forced to perform sexual acts respondent didn't want to"
  /MD105L   "NA - Ever CS physical violence by wife/partner"
  /MD105M   "NA - Ever CS physical violence by wife/partner"
  /MD105N   "NA - Ever CS physical violence by wife/partner"
  /MD106    "Experienced any less severe violence (MD105A-C,J) by wife/partner"
  /MD107    "Experienced any severe violence (MD105D-F) by wife/partner"
  /MD108    "Experienced any sexual violence (MD105H,K) by wife/partner"
  /MD109    "Timing of first event (from MD105 series) in years after marriage"
  /MD110A   "Ever had bruises because of wife/partner's actions"
  /MD110B   "Ever had eye injuries, sprains, dislocations or burns because of wife/partner's actions"
  /MD110D   "Ever had wounds, broken bones, broken teeth or other serious injury because of wife/partner's actions"
  /MD110C   "NA - Ever went to health facility because of wife/partner's actions"
  /MD110E   "NA - CS because of wife/partner's actions"
  /MD110F   "NA - CS because of wife/partner's actions"
  /MD110G   "NA - CS because of wife/partner's actions"
  /MD110H   "NA - CS because of wife/partner's actions"
  /MD111    "Experienced any of listed wife/partner's actions (MD110x series)"
  /MD112    "Respondent ever physically hurt wife/partner when she was not hurting him"
  /MD112A   "Frequency of physically hurting wife/partner in last 12 months"
  /MD113    "Wife/partner drinks alcohol"
  /MD114    "Frequency of wife/partner being drunk"
  /MD115B   "Mother/step-mother: Person who has ever physically hurt respondent"
  /MD115C   "Father/step-father: Person who has ever physically hurt respondent"
  /MD115D   "Daughter/son: Person who has ever physically hurt respondent"
  /MD115E   "NA - Son: Person who has ever physically hurt respondent"
  /MD115F   "Sister/brother: Person who has ever physically hurt respondent"
  /MD115G   "Other relative: Person who has ever physically hurt respondent"
  /MD115H   "NA - Other female family: Person who has ever physically hurt respondent"
  /MD115I   "NA - Other male family: Person who has ever physically hurt respondent"
  /MD115J   "NA - Former partner: Person who has ever physically hurt respondent"
  /MD115K   "Current girlfriend: Person who has ever physically hurt respondent"
  /MD115L   "Former girlfriend: Person who has ever physically hurt respondent"
  /MD115M   "NA - Step-mother: Person who has ever physically hurt respondent"
  /MD115N   "NA - Step-father: Person who has ever physically hurt respondent"
  /MD115O   "Mother/father-in-law: Person who has ever physically hurt respondent"
  /MD115P   "NA - Father-in-law: Person who has ever physically hurt respondent"
  /MD115Q   "NA - Other in-law: Person who has ever physically hurt respondent"
  /MD115R   "NA - Other male in-law: Person who has ever physically hurt respondent"
  /MD115S   "NA - Female friend: Person who has ever physically hurt respondent"
  /MD115T   "NA - Male friend: Person who has ever physically hurt respondent"
  /MD115U   "NA - Neighbor: Person who has ever physically hurt respondent"
  /MD115V   "Teacher: Person who has ever physically hurt respondent"
  /MD115W   "Employer/co-worker: Person who has ever physically hurt respondent"
  /MD115X   "Other: Person who has ever physically hurt respondent"
  /MD115Y   "No person other than wife/partner ever physically hurt respondent"
  /MD115XA  "Stranger: Person who has ever physically hurt respondent"
  /MD115XB  "NA - Other female in-law/family: Person who has ever physically hurt respondent"
  /MD115XC  "NA - Other male in-law/family: Person who has ever physically hurt respondent"
  /MD115XD  "Friend: Person who has ever physically hurt respondent"
  /MD115XE  "Police/soldier: Person who has ever physically hurt respondent"
  /MD115XF  "NA - Religious leader: Person who has ever physically hurt respondent"
  /MD115XG  "NA - Lawyer: Person who has ever physically hurt respondent"
  /MD115XH  "NA - Doctor: Person who has ever physically hurt respondent"
  /MD115XI  "Former in-love: Person who has ever physically hurt respondent"
  /MD115XJ  "Partner relative: Person who has ever physically hurt respondent"
  /MD115XK  "NA - CS: Person who has ever physically hurt respondent"
  /MD117A   "Frequency of being hit in last 12 months by other than wife/partner"
  /MD119A   "Wife/partner: Person respondent went to seek help"
  /MD119B   "NA - Mother: Person respondent went to seek help"
  /MD119C   "NA - Father: Person respondent went to seek help"
  /MD119D   "NA - Daughter: Person respondent went to seek help"
  /MD119E   "NA - Son: Person respondent went to seek help"
  /MD119F   "NA - Sister: Person respondent went to seek help"
  /MD119G   "NA - Brother: Person respondent went to seek help"
  /MD119H   "Own family: Person respondent went to seek help"
  /MD119I   "Wife/partner family: Person respondent went to seek help"
  /MD119J   "Former wife/partner: Person respondent went to seek help"
  /MD119K   "Current girlfriend: Person respondent went to seek help"
  /MD119L   "Former girlfriend alone: Person respondent went to seek help"
  /MD119M   "NA - Step-mother: Person respondent went to seek help"
  /MD119N   "NA - Step-father: Person respondent went to seek help"
  /MD119O   "Mother/father-in-law: Person respondent went to seek help"
  /MD119P   "NA - Father-in-law: Person respondent went to seek help"
  /MD119Q   "NA - Other female in-law: Person respondent went to seek help"
  /MD119R   "NA - Other male in-law: Person respondent went to seek help"
  /MD119S   "NA - Female friend: Person respondent went to seek help"
  /MD119T   "NA - Male friend: Person respondent went to seek help"
  /MD119U   "NA - Neighbor: Person respondent went to seek help"
  /MD119V   "NA - Teacher: Person respondent went to seek help"
  /MD119W   "NA - Employer: Person respondent went to seek help"
  /MD119X   "Other: Person respondent went to seek help"
  /MD119Y   "Respondent did not seek help from anyone"
  /MD119XA  "NA - Stranger: Person respondent went to seek help"
  /MD119XB  "Social service organization: Person respondent went to seek help"
  /MD119XC  "Peace court: Person respondent went to seek help"
  /MD119XD  "Friend: Person respondent went to seek help"
  /MD119XE  "Police/soldier: Person respondent went to seek help"
  /MD119XF  "Religious leader: Person respondent went to seek help"
  /MD119XG  "Lawyer: Person respondent went to seek help"
  /MD119XH  "NA - Doctor: Person respondent went to seek help"
  /MD119XI  "Co-worker: Person respondent went to seek help"
  /MD119XJ  "Medical personnel: Person respondent went to seek help"
  /MD119XK  "Family court: Person respondent went to seek help"
  /MD116    "NA - Person who hurt respondent most often"
  /MD120    "NA - Main reason never sought help"
  /MD121    "Respondent's father ever beat his mother"
  /MD122A   "Interview interrupted: wife's presence"
  /MD122B   "Interview interrupted: other adult female's presence"
  /MD122C   "Interview interrupted: adult male's presence"
  /MD123    "NA - First sex was wanted or forced"
  /MD124    "Ever forced to have sex by anyone other than wife/partner in last 12 months"
  /MD125    "Ever forced to perform unwanted sexual acts"
  /MD126    "Age at first forced sexual act"
  /MD127    "NA - Person who forced respondent into first sexual act"
  /MD128    "Ever told anyone else about violence"
  /MD129    "Respondent afraid of wife/partner most of the time, sometimes or never"
  /MD130A   "Previous wife: ever hit, slap, kick or physically hurt respondent"
  /MD130B   "Previous wife: physically forced to have sex or to perform sexual acts"
 .
MISSING VALUE
   MV015    (9)
  /MV026    (9)
  /MV027    (9)
  /MV028    (999)
  /MV029    (99)
  /MV030    (999)
  /MV031    (999)
  /MV032    (99)
  /MV034$1  (99)
  /MV034$2  (99)
  /MV034$3  (99)
  /MV034$4  (99)
  /MV034$5  (99)
  /MV034$6  (99)
  /MV034$7  (99)
  /MV034$8  (99)
  /MV034A$1 (9)
  /MV034A$2 (9)
  /MV034A$3 (9)
  /MV034A$4 (9)
  /MV034A$5 (9)
  /MV034A$6 (9)
  /MV034A$7 (9)
  /MV034A$8 (9)
  /MV034B$1 (99)
  /MV034B$2 (99)
  /MV034B$3 (99)
  /MV034B$4 (99)
  /MV034B$5 (99)
  /MV034B$6 (99)
  /MV034B$7 (99)
  /MV034B$8 (99)
  /MV035    (9)
  /MV801    (9999)
  /MV802    (9999)
  /MV803    (99)
  /MV103    (9)
  /MV104    (99)
  /MV105    (9)
  /MV106    (9)
  /MV107    (99)
  /MV130    (99)
  /MV131    (999)
  /MV133    (99)
  /MV134    (9)
  /MV135    (9)
  /MV149    (9)
  /MV150    (99)
  /MV152    (99)
  /MV155    (9)
  /MV156    (9)
  /MV157    (9)
  /MV158    (9)
  /MV159    (9)
  /MV167    (99)
  /MV168    (9)
  /MV212    (99)
  /MV213    (9)
  /MV217    (9)
  /MV225    (9)
  /MV245    (99)
  /MV246    (9)
  /MV247    (99)
  /MV248    (9)
  /MV249    (9)
  /MV250    (9)
  /MV251    (99)
  /MV252    (9)
  /MV304$01 (9)
  /MV304$02 (9)
  /MV304$03 (9)
  /MV304$04 (9)
  /MV304$05 (9)
  /MV304$06 (9)
  /MV304$07 (9)
  /MV304$08 (9)
  /MV304$09 (9)
  /MV304$10 (9)
  /MV304$11 (9)
  /MV304$12 (9)
  /MV304$13 (9)
  /MV304$14 (9)
  /MV304$15 (9)
  /MV304$16 (9)
  /MV304$17 (9)
  /MV304$18 (9)
  /MV304$19 (9)
  /MV304$20 (9)
  /MV305$01 (9)
  /MV305$02 (9)
  /MV305$03 (9)
  /MV305$04 (9)
  /MV305$05 (9)
  /MV305$06 (9)
  /MV305$07 (9)
  /MV305$08 (9)
  /MV305$09 (9)
  /MV305$10 (9)
  /MV305$11 (9)
  /MV305$12 (9)
  /MV305$13 (9)
  /MV305$14 (9)
  /MV305$15 (9)
  /MV305$16 (9)
  /MV305$17 (9)
  /MV305$18 (9)
  /MV305$19 (9)
  /MV305$20 (9)
  /MV307$01 (9)
  /MV307$02 (9)
  /MV307$03 (9)
  /MV307$04 (9)
  /MV307$05 (9)
  /MV307$06 (9)
  /MV307$07 (9)
  /MV307$08 (9)
  /MV307$09 (9)
  /MV307$10 (9)
  /MV307$11 (9)
  /MV307$12 (9)
  /MV307$13 (9)
  /MV307$14 (9)
  /MV307$15 (9)
  /MV307$16 (9)
  /MV307$17 (9)
  /MV307$18 (9)
  /MV307$19 (9)
  /MV307$20 (9)
  /MV312    (99)
  /MV313    (9)
  /MV323A   (99)
  /MV325B   (9999999)
  /MV372A   (9)
  /MV384A   (9)
  /MV384B   (9)
  /MV384C   (9)
  /MV395    (9)
  /MV396    (9)
  /MV3A09B  (999)
  /MV3B17   (99)
  /MV3B25A  (9)
  /MV3B25B  (9)
  /MV463A   (9)
  /MV463B   (9)
  /MV463C   (9)
  /MV463D   (9)
  /MV463E   (9)
  /MV463F   (9)
  /MV463G   (9)
  /MV463X   (9)
  /MV463Z   (9)
  /MV464    (99)
  /MV474    (9)
  /MV474A   (9)
  /MV474B   (9)
  /MV474C   (9)
  /MV474D   (9)
  /MV474E   (9)
  /MV474F   (9)
  /MV474G   (9)
  /MV474H   (9)
  /MV474I   (9)
  /MV474J   (9)
  /MV474X   (9)
  /MV474Z   (9)
  /MV475    (9)
  /MV476    (9)
  /MV477    (99)
  /MV478    (99)
  /MV479    (99)
  /MV480    (9)
  /MV481    (9)
  /MV481A   (9)
  /MV481B   (9)
  /MV481C   (9)
  /MV481D   (9)
  /MV481E   (9)
  /MV481F   (9)
  /MV481G   (9)
  /MV481H   (9)
  /MV481X   (9)
  /MV482A   (9)
  /MV482B   (9)
  /MV482C   (9)
  /MV483    (9)
  /MV483A   (99)
  /MV483B   (99)
  /MV483C   (99)
  /MV501    (9)
  /MV502    (9)
  /MV503    (9)
  /MV504    (9)
  /MV505    (99)
  /MV525    (99)
  /MV527    (999)
  /MV528    (99)
  /MV529    (999)
  /MV531    (99)
  /MV535    (9)
  /MV536    (9)
  /MV541    (9)
  /MV602    (9)
  /MV603    (999)
  /MV604    (9)
  /MV605    (9)
  /MV613    (99)
  /MV616    (999)
  /MV621    (9)
  /MV627    (99)
  /MV628    (99)
  /MV629    (99)
  /MV631    (9)
  /MV633A   (9)
  /MV633B   (9)
  /MV633C   (9)
  /MV633D   (9)
  /MV633E   (9)
  /MV633F   (9)
  /MV633G   (9)
  /MV634A   (9)
  /MV634B   (9)
  /MV634C   (9)
  /MV634D   (9)
  /MV714    (9)
  /MV714A   (9)
  /MV716    (999)
  /MV717    (99)
  /MV719    (9)
  /MV721    (9)
  /MV731    (9)
  /MV732    (9)
  /MV739    (9)
  /MV740    (9)
  /MV741    (9)
  /MV743A   (9)
  /MV743B   (9)
  /MV743C   (9)
  /MV743D   (9)
  /MV743E   (9)
  /MV743F   (9)
  /MV743G   (9)
  /MV744A   (9)
  /MV744B   (9)
  /MV744C   (9)
  /MV744D   (9)
  /MV744E   (9)
  /MV745A   (9)
  /MV745B   (9)
  /MV747A   (9)
  /MV747B   (9)
  /MV750    (9)
  /MV751    (9)
  /MV754BP  (9)
  /MV754CP  (9)
  /MV754DP  (9)
  /MV754JP  (9)
  /MV754WP  (9)
  /MV756    (9)
  /MV761    (9)
  /MV761B   (9)
  /MV761C   (9)
  /MV762AA  (9)
  /MV762AB  (9)
  /MV762AC  (9)
  /MV762AD  (9)
  /MV762AE  (9)
  /MV762AF  (9)
  /MV762AG  (9)
  /MV762AH  (9)
  /MV762AI  (9)
  /MV762AJ  (9)
  /MV762AK  (9)
  /MV762AL  (9)
  /MV762AM  (9)
  /MV762AN  (9)
  /MV762AO  (9)
  /MV762AP  (9)
  /MV762AQ  (9)
  /MV762AR  (9)
  /MV762AS  (9)
  /MV762AT  (9)
  /MV762AU  (9)
  /MV762AV  (9)
  /MV762AW  (9)
  /MV762AX  (9)
  /MV762AZ  (9)
  /MV762BA  (9)
  /MV762BB  (9)
  /MV762BC  (9)
  /MV762BD  (9)
  /MV762BE  (9)
  /MV762BF  (9)
  /MV762BG  (9)
  /MV762BH  (9)
  /MV762BI  (9)
  /MV762BJ  (9)
  /MV762BK  (9)
  /MV762BL  (9)
  /MV762BM  (9)
  /MV762BN  (9)
  /MV762BO  (9)
  /MV762BP  (9)
  /MV762BQ  (9)
  /MV762BR  (9)
  /MV762BS  (9)
  /MV762BT  (9)
  /MV762BU  (9)
  /MV762BV  (9)
  /MV762BW  (9)
  /MV762BX  (9)
  /MV762BZ  (9)
  /MV763A   (9)
  /MV763B   (9)
  /MV763C   (9)
  /MV763D   (9)
  /MV763E   (9)
  /MV763F   (9)
  /MV763G   (9)
  /MV766A   (99)
  /MV766B   (99)
  /MV767A   (99)
  /MV767B   (99)
  /MV767C   (99)
  /MV768A   (999)
  /MV768B   (999)
  /MV768C   (999)
  /MV769    (9)
  /MV769A   (9)
  /MV770    (9)
  /MV770A   (9)
  /MV770B   (9)
  /MV770C   (9)
  /MV770D   (9)
  /MV770E   (9)
  /MV770F   (9)
  /MV770G   (9)
  /MV770H   (9)
  /MV770I   (9)
  /MV770J   (9)
  /MV770K   (9)
  /MV770L   (9)
  /MV770M   (9)
  /MV770N   (9)
  /MV770O   (9)
  /MV770P   (9)
  /MV770Q   (9)
  /MV770R   (9)
  /MV770S   (9)
  /MV770T   (9)
  /MV770U   (9)
  /MV770V   (9)
  /MV770W   (9)
  /MV770X   (9)
  /MV774A   (9)
  /MV774B   (9)
  /MV774C   (9)
  /MV775    (9)
  /MV777    (9)
  /MV778    (9)
  /MV779    (9)
  /MV780    (9)
  /MV781    (9)
  /MV783    (9)
  /MV784A   (9)
  /MV784B   (9)
  /MV784C   (9)
  /MV784D   (9)
  /MV784E   (9)
  /MV784F   (9)
  /MV784G   (9)
  /MV784H   (9)
  /MV784I   (9)
  /MV784J   (9)
  /MV784K   (9)
  /MV784L   (9)
  /MV784M   (9)
  /MV784N   (9)
  /MV784O   (9)
  /MV784P   (9)
  /MV784Q   (9)
  /MV784R   (9)
  /MV784S   (9)
  /MV784T   (9)
  /MV784U   (9)
  /MV784V   (9)
  /MV784X   (9)
  /MV785    (9)
  /MV791    (9)
  /MV793    (9)
  /MV793A   (9)
  /MV793B   (9)
  /MV820    (9)
  /MV822    (9)
  /MV823    (9)
  /MV824    (9)
  /MV825    (9)
  /MV826    (9)
  /MV826A   (99)
  /MV827    (9)
  /MV828    (9)
  /MV829    (99)
  /MV832B   (999)
  /MV832C   (999)
  /MV833A   (9)
  /MV833B   (9)
  /MV833C   (9)
  /MV834A   (99)
  /MV834B   (99)
  /MV834C   (99)
  /MV835A   (9)
  /MV835B   (9)
  /MV835C   (9)
  /MV836    (99)
  /MV837    (9)
  /MV844    (9)
  /MV845    (9)
  /MV846    (9)
  /MV847    (9)
  /MV848    (9)
  /MV849    (9)
  /MV851A   (9)
  /MV851B   (9)
  /MV851C   (9)
  /MV851D   (9)
  /MV851E   (9)
  /MV851F   (9)
  /MV851G   (9)
  /MV851H   (9)
  /MV851I   (9)
  /MV851J   (9)
  /MV851K   (9)
  /MV851L   (9)
  /MV852A   (999)
  /MV852B   (999)
  /MV852C   (999)
  /MV853A   (99)
  /MV853B   (99)
  /MV853C   (99)
  /MV854A   (9)
  /MV854B   (9)
  /SMILANG  (99)
  /SMQLANG  (99)
  /SMEDUC   (9)
  /SMETID   (9)
  /SMETOB   (9)
  /SM105    (9)
  /SM106    (99)
  /SM114    (99)
  /SM115    (99)
  /SM116    (9)
  /SM117A   (9)
  /SM117B   (9)
  /SM117C   (9)
  /SM117D   (9)
  /SM117E   (9)
  /SM117F   (9)
  /SM117G   (9)
  /SM117H   (9)
  /SM117I   (9)
  /SM117J   (9)
  /SM117K   (9)
  /SM117L   (9)
  /SM117M   (9)
  /SM117N   (9)
  /SM117O   (9)
  /SM117P   (9)
  /SM117Q   (9)
  /SM117R   (9)
  /SM117S   (9)
  /SM117T   (9)
  /SM117U   (9)
  /SM117V   (9)
  /SM117W   (9)
  /SM117X   (9)
  /SM119    (99)
  /SM120    (9)
  /SM219    (9)
  /SM222    (99)
  /SM303D   (9)
  /SM308L   (9)
  /SM308M   (9)
  /SM308N   (9)
  /SM308O   (9)
  /SM308P   (9)
  /SM308Q   (9)
  /SM308R   (9)
  /SM308S   (9)
  /SM308T   (9)
  /SM423    (9)
  /SM433    (99)
  /SM616A   (9)
  /SM616B   (9)
  /SM616C   (9)
  /SM616D   (9)
  /SM708K   (9)
  /SM708L   (9)
  /SM708M   (9)
  /SM708N   (9)
  /SM708O   (9)
  /SM708P   (9)
  /SM708Q   (9)
  /SM708R   (9)
  /SM708S   (9)
  /SM708T   (9)
  /SM708X   (9)
  /SM708JJ  (9)
  /SM711    (9)
  /SM726    (9)
  /SM727    (9)
  /SM728    (99)
  /SM730K   (9)
  /SM730L   (9)
  /SM730M   (9)
  /SM730N   (9)
  /SM730O   (9)
  /SM730P   (9)
  /SM730Q   (9)
  /SM730R   (9)
  /SM730S   (9)
  /SM730T   (9)
  /SM730X   (9)
  /SM730JJ  (9)
  /SM737    (9)
  /SM738    (999)
  /SM739    (9)
  /SM807    (9)
  /SM812    (9)
  /SM813    (99)
  /SM814    (9)
  /SM815    (99)
  /SM816AA  (9)
  /SM816AB  (9)
  /SM816AC  (9)
  /SM816AD  (9)
  /SM816AE  (9)
  /SM816AF  (9)
  /SM816AG  (9)
  /SM816AH  (9)
  /SM816AI  (9)
  /SM816AJ  (9)
  /SM816AK  (9)
  /SM816AL  (9)
  /SM816AM  (9)
  /SM816AN  (9)
  /SM816AO  (9)
  /SM816AP  (9)
  /SM816AQ  (9)
  /SM816AR  (9)
  /SM816AS  (9)
  /SM816AT  (9)
  /SM816AU  (9)
  /SM816AV  (9)
  /SM816AW  (9)
  /SM816AX  (9)
  /SM816BA  (9)
  /SM816BB  (9)
  /SM816BC  (9)
  /SM816BD  (9)
  /SM816BE  (9)
  /SM816BF  (9)
  /SM816BG  (9)
  /SM816BH  (9)
  /SM816BI  (9)
  /SM816BJ  (9)
  /SM816BK  (9)
  /SM816BL  (9)
  /SM816BM  (9)
  /SM816BN  (9)
  /SM816BO  (9)
  /SM816BP  (9)
  /SM816BQ  (9)
  /SM816BR  (9)
  /SM816BS  (9)
  /SM816BT  (9)
  /SM816BU  (9)
  /SM816BV  (9)
  /SM816BW  (9)
  /SM816BX  (9)
  /SM819A   (9)
  /SM819B   (9)
  /SM819C   (9)
  /SM905A2  (9)
  /SM905B2  (9)
  /SM905C2  (9)
  /SM906A2  (9)
  /SM906B2  (9)
  /SM906C2  (9)
  /SM906D2  (9)
  /SM906E2  (9)
  /SM906F2  (9)
  /SM906G2  (9)
  /SM906H2  (9)
  /SM906I2  (9)
  /SM911    (9)
  /SM916B   (9)
  /SM916C   (9)
  /SM919    (9)
  /SM921A   (9)
  /SM921B   (9)
  /SM922A   (9)
  /SM922B   (9)
  /SM922C   (9)
  /SM922D   (9)
  /SM922E   (9)
  /SM922F   (9)
  /SM922G   (9)
  /SM922H   (9)
  /SM922I   (9)
  /SM922K   (9)
  /SM922L   (9)
  /SM922M   (9)
  /SM922N   (9)
  /SM922O   (9)
  /SM922P   (9)
  /SM922Q   (9)
  /SM922X   (9)
  /SM928AA  (9)
  /SM928BB  (9)
  /SM928CC  (9)
  /SM929    (9)
  /SM932D   (9)
  /MD101A   (9)
  /MD101B   (9)
  /MD101C   (9)
  /MD101D   (9)
  /MD101E   (9)
  /MD101F   (9)
  /MD101G   (9)
  /MD101H   (9)
  /MD101I   (9)
  /MD101J   (9)
  /MD102    (99)
  /MD103A   (9)
  /MD103B   (9)
  /MD103C   (9)
  /MD103D   (9)
  /MD103E   (9)
  /MD103F   (9)
  /MD104    (9)
  /MD105A   (9)
  /MD105B   (9)
  /MD105C   (9)
  /MD105D   (9)
  /MD105E   (9)
  /MD105F   (9)
  /MD105G   (9)
  /MD105H   (9)
  /MD105I   (9)
  /MD105J   (9)
  /MD105K   (9)
  /MD105L   (9)
  /MD105M   (9)
  /MD105N   (9)
  /MD106    (9)
  /MD107    (9)
  /MD108    (9)
  /MD109    (99)
  /MD110A   (9)
  /MD110B   (9)
  /MD110D   (9)
  /MD110C   (9)
  /MD110E   (9)
  /MD110F   (9)
  /MD110G   (9)
  /MD110H   (9)
  /MD111    (9)
  /MD112    (9)
  /MD112A   (9)
  /MD113    (9)
  /MD114    (9)
  /MD115B   (9)
  /MD115C   (9)
  /MD115D   (9)
  /MD115E   (9)
  /MD115F   (9)
  /MD115G   (9)
  /MD115H   (9)
  /MD115I   (9)
  /MD115J   (9)
  /MD115K   (9)
  /MD115L   (9)
  /MD115M   (9)
  /MD115N   (9)
  /MD115O   (9)
  /MD115P   (9)
  /MD115Q   (9)
  /MD115R   (9)
  /MD115S   (9)
  /MD115T   (9)
  /MD115U   (9)
  /MD115V   (9)
  /MD115W   (9)
  /MD115X   (9)
  /MD115Y   (9)
  /MD115XA  (9)
  /MD115XB  (9)
  /MD115XC  (9)
  /MD115XD  (9)
  /MD115XE  (9)
  /MD115XF  (9)
  /MD115XG  (9)
  /MD115XH  (9)
  /MD115XI  (9)
  /MD115XJ  (9)
  /MD115XK  (9)
  /MD117A   (9)
  /MD119A   (9)
  /MD119B   (9)
  /MD119C   (9)
  /MD119D   (9)
  /MD119E   (9)
  /MD119F   (9)
  /MD119G   (9)
  /MD119H   (9)
  /MD119I   (9)
  /MD119J   (9)
  /MD119K   (9)
  /MD119L   (9)
  /MD119M   (9)
  /MD119N   (9)
  /MD119O   (9)
  /MD119P   (9)
  /MD119Q   (9)
  /MD119R   (9)
  /MD119S   (9)
  /MD119T   (9)
  /MD119U   (9)
  /MD119V   (9)
  /MD119W   (9)
  /MD119X   (9)
  /MD119Y   (9)
  /MD119XA  (9)
  /MD119XB  (9)
  /MD119XC  (9)
  /MD119XD  (9)
  /MD119XE  (9)
  /MD119XF  (9)
  /MD119XG  (9)
  /MD119XH  (9)
  /MD119XI  (9)
  /MD119XJ  (9)
  /MD119XK  (9)
  /MD116    (99)
  /MD120    (99)
  /MD121    (9)
  /MD122A   (9)
  /MD122B   (9)
  /MD122C   (9)
  /MD123    (9)
  /MD124    (9)
  /MD125    (9)
  /MD126    (99)
  /MD127    (99)
  /MD128    (9)
  /MD129    (9)
  /MD130A   (9)
  /MD130B   (9)
 .
VALUE LABELS
   MV013   
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
      8 "50-54"
      9 "55-59"
     10 "60-64"
  /MV014   
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /MV015   
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /MV024   
      1 "Metropolitana"
      2 "Norte"
      3 "Nororiente"
      4 "Suroriente"
      5 "Central"
      6 "Suroccidente"
      7 "Noroccidente"
      8 "Petén"
  /MV025   
      1 "Urban"
      2 "Rural"
  /MV026   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /MV034$1 
      0 "Wife not in household"
  /MV034$2 
      0 "Wife not in household"
  /MV034$3 
      0 "Wife not in household"
  /MV034$4 
      0 "Wife not in household"
  /MV034$5 
      0 "Wife not in household"
  /MV034$6 
      0 "Wife not in household"
  /MV034$7 
      0 "Wife not in household"
  /MV034$8 
      0 "Wife not in household"
  /MV034A$1
      1 "Wife"
      2 "Partner"
  /MV034A$2
      1 "Wife"
      2 "Partner"
  /MV034A$3
      1 "Wife"
      2 "Partner"
  /MV034A$4
      1 "Wife"
      2 "Partner"
  /MV034A$5
      1 "Wife"
      2 "Partner"
  /MV034A$6
      1 "Wife"
      2 "Partner"
  /MV034A$7
      1 "Wife"
      2 "Partner"
  /MV034A$8
      1 "Wife"
      2 "Partner"
  /MV035   
      0 "No wives/partners"
  /MV803   
     95 "95+"
     96 "2+ visits"
     97 "Inconsistent"
  /MV101   
      1 "Metropolitana"
      2 "Norte"
      3 "Nororiente"
      4 "Suroriente"
      5 "Central"
      6 "Suroccidente"
      7 "Noroccidente"
      8 "Petén"
  /MV102   
      1 "Urban"
      2 "Rural"
  /MV103   
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /MV104   
     95 "Always"
     96 "Visitor"
     97 "Inconsistent"
     98 "Don't know"
  /MV105   
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /MV106   
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
  /MV107   
      0 "No years completed at level MV106"
  /MV130   
      0 "No religion"
      1 "Catholic"
      2 "Evangelical"
      3 "Protestant"
      4 "Indigenous spirituality"
      7 "Adventist"
      8 "Jehovah Witness"
     96 "Other"
  /MV131   
      1 "Maya"
      2 "Ladina/mestiza"
      3 "Garífuna"
      4 "Xinca"
      6 "Other"
      8 "DK, unsure"
  /MV133   
     97 "Inconsistent"
  /MV134   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /MV135   
      1 "Usual resident"
      2 "Visitor"
  /MV149   
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
  /MV150   
      1 "Head"
      2 "Husband"
      3 "Son"
      4 "Son-in-law"
      5 "Grandson"
      6 "Father"
      7 "Father-in-law"
      8 "Brother"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "Don't know"
  /MV151   
      1 "Male"
      2 "Female"
  /MV152   
     95 "95+"
     98 "Don't know"
  /MV155   
      0 "Cannot read at all"
      1 "Able to read only parts of sentence"
      2 "Able to read whole sentence"
      3 "No card with required language"
      4 "Blind/visually impaired"
  /MV156   
      0 "No"
      1 "Yes"
  /MV157   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /MV158   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /MV159   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /MV167   
      0 "None"
     90 "90+"
     97 "Inconsistent"
     98 "Don't know"
  /MV168   
      0 "No"
      1 "Yes"
  /MV190   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /MV213   
      0 "No"
      1 "Yes"
      8 "Unsure"
  /MV217   
      1 "During her period"
      2 "After period ended"
      3 "Middle of the cycle"
      4 "Before period begins"
      5 "At any time"
      6 "Other"
      8 "Don't know"
  /MV225   
      1 "Then"
      2 "Later"
      3 "Not at all"
  /MV246   
      0 "No"
      1 "Yes"
  /MV248   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV249   
      0 "Not present"
      1 "Present"
  /MV250   
      1 "Hospital, health facility"
      2 "Other"
      8 "Don't know"
  /MV251   
      1 "Cost too much"
      2 "Facility closed"
      3 "Too far/no transportation"
      4 "Don't trust facility/poor quality service"
      5 "No female provider"
      6 "Not the first child"
      7 "Mother did not think it necessary"
      8 "Respondent did not think it necessary"
      9 "Family did not think it necessary"
     96 "Other"
     98 "Don't know"
  /MV252   
      0 "Nothing to drink"
      2 "Less than usual/much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /MV301   
      0 "Knows no method"
      1 "Knows only folkloric method"
      2 "Knows only traditional method"
      3 "Knows modern method"
  /MV302   
      0 "Never used"
      1 "Used only folkloric method"
      2 "Used only traditional method"
      3 "Used modern method"
  /M304A$01
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$02
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$03
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$04
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$05
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$06
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$07
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$08
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$09
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$10
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$11
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$12
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$13
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$14
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$15
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$16
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$17
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$18
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$19
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$20
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /MV304$01
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$02
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$03
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$04
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$05
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$06
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$07
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$08
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$09
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$10
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$11
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$12
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$13
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$14
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$15
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$16
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$17
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$18
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$19
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$20
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV305$01
      0 "No"
      1 "Yes"
  /MV305$02
      0 "No"
      1 "Yes"
  /MV305$03
      0 "No"
      1 "Yes"
  /MV305$04
      0 "No"
      1 "Yes"
  /MV305$05
      0 "No"
      1 "Yes"
  /MV305$06
      0 "No"
      1 "Yes"
  /MV305$07
      0 "No"
      1 "Yes"
  /MV305$08
      0 "No"
      1 "Yes"
  /MV305$09
      0 "No"
      1 "Yes"
  /MV305$10
      0 "No"
      1 "Yes"
  /MV305$11
      0 "No"
      1 "Yes"
  /MV305$12
      0 "No"
      1 "Yes"
  /MV305$13
      0 "No"
      1 "Yes"
  /MV305$14
      0 "No"
      1 "Yes"
  /MV305$15
      0 "No"
      1 "Yes"
  /MV305$16
      0 "No"
      1 "Yes"
  /MV305$17
      0 "No"
      1 "Yes"
  /MV305$18
      0 "No"
      1 "Yes"
  /MV305$19
      0 "No"
      1 "Yes"
  /MV305$20
      0 "No"
      1 "Yes"
  /MV307$01
      0 "No"
      1 "Yes"
  /MV307$02
      0 "No"
      1 "Yes"
  /MV307$03
      0 "No"
      1 "Yes"
  /MV307$04
      0 "No"
      1 "Yes"
  /MV307$05
      0 "No"
      1 "Yes"
  /MV307$06
      0 "No"
      1 "Yes"
  /MV307$07
      0 "No"
      1 "Yes"
  /MV307$08
      0 "No"
      1 "Yes"
  /MV307$09
      0 "No"
      1 "Yes"
  /MV307$10
      0 "No"
      1 "Yes"
  /MV307$11
      0 "No"
      1 "Yes"
  /MV307$12
      0 "No"
      1 "Yes"
  /MV307$13
      0 "No"
      1 "Yes"
  /MV307$14
      0 "No"
      1 "Yes"
  /MV307$15
      0 "No"
      1 "Yes"
  /MV307$16
      0 "No"
      1 "Yes"
  /MV307$17
      0 "No"
      1 "Yes"
  /MV307$18
      0 "No"
      1 "Yes"
  /MV307$19
      0 "No"
      1 "Yes"
  /MV307$20
      0 "No"
      1 "Yes"
  /MV312   
      0 "Not using"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Implants/Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea (LAM)"
     14 "Female condom"
     15 "Foam or jelly"
     17 "Other modern method"
     18 "Fixed days (string)"
     19 "Foam/jelly/tablets/ovule/diaphragm"
     20 "Survey Specific method 4"
     98 "Don't know"
  /MV313   
      0 "No method"
      1 "Folkloric method"
      2 "Traditional method"
      3 "Modern method"
      8 "Don't know"
  /MV323A  
      1 "Vive"
      2 "Scudo"
      3 "No brand name"
      4 "Durex"
      5 "Trojan"
      6 "Tianjin Human"
      7 "Emoformo"
      8 "XL"
      9 "Troyano"
     10 "Latex"
     96 "Other"
     98 "Don't know"
  /MV325B  
   9999995 "Free"
   9999998 "Don't know"
  /MV372A  
      0 "Package not seen"
      1 "Package seen"
  /MV384A  
      0 "No"
      1 "Yes"
  /MV384B  
      0 "No"
      1 "Yes"
  /MV384C  
      0 "No"
      1 "Yes"
  /MV395   
      0 "No"
      1 "Yes"
      2 "Depends"
      8 "Don't know"
  /MV396   
      0 "No"
      1 "Yes"
      2 "Depends"
      8 "Don't know"
  /MV3A09B 
    998 "Don't know"
  /MV3B17  
     10 "PUBLIC SECTOR"
     11 "Third level (Hospital)"
     12 "Second level (health centers, maternity,mobile clinic,etc.)"
     13 "First level (health post, convergence center)"
     16 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital, clinic"
     22 "Private doctor"
     23 "Family protection association (APROFAM)"
     24 "Pharmacy"
     25 "Social Security (IGSS)"
     26 "Other private"
     30 "OTHER"
     31 "Traditional birth attendant"
     36 "Health promoter"
     37 "Health guardian"
     96 "Other"
     98 "Don't know"
  /MV3B25A 
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV3B25B 
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV463A  
      0 "No"
      1 "Yes"
  /MV463B  
      0 "No"
      1 "Yes"
  /MV463C  
      0 "No"
      1 "Yes"
  /MV463D  
      0 "No"
      1 "Yes"
  /MV463E  
      0 "No"
      1 "Yes"
  /MV463F  
      0 "No"
      1 "Yes"
  /MV463G  
      0 "No"
      1 "Yes"
  /MV463X  
      0 "No"
      1 "Yes"
  /MV463Z  
      0 "No"
      1 "Yes, smokes nothing"
  /MV464   
     80 "80+"
     98 "DK"
  /MV474   
      0 "No"
      1 "Yes"
  /MV474A  
      0 "No"
      1 "Yes"
  /MV474B  
      0 "No"
      1 "Yes"
  /MV474C  
      0 "No"
      1 "Yes"
  /MV474D  
      0 "No"
      1 "Yes"
  /MV474E  
      0 "No"
      1 "Yes"
  /MV474F  
      0 "No"
      1 "Yes"
  /MV474G  
      0 "No"
      1 "Yes"
  /MV474H  
      0 "No"
      1 "Yes"
  /MV474I  
      0 "No"
      1 "Yes"
  /MV474J  
      0 "No"
      1 "Yes"
  /MV474X  
      0 "No"
      1 "Yes"
  /MV474Z  
      0 "No"
      1 "Yes"
  /MV475   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV476   
      0 "No"
      1 "Yes, remain a secret"
      8 "Don't know/not sure/depends"
  /MV477   
      0 "None"
     90 "90+"
     98 "Don't know"
  /MV478   
      0 "None"
     90 "90+"
     98 "Don't know"
  /MV479   
     10 "PUBLIC SECTOR"
     20 "PRIVATE SECTOR"
     30 "OTHER"
     96 "Other"
  /MV480   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV481   
      0 "No"
      1 "Yes"
  /MV481A  
      0 "No"
      1 "Yes"
  /MV481B  
      0 "No"
      1 "Yes"
  /MV481C  
      0 "No"
      1 "Yes"
  /MV481D  
      0 "No"
      1 "Yes"
  /MV481E  
      0 "No"
      1 "Yes"
  /MV481F  
      0 "No"
      1 "Yes"
  /MV481G  
      0 "No"
      1 "Yes"
  /MV481H  
      0 "No"
      1 "Yes"
  /MV481X  
      0 "No"
      1 "Yes"
  /MV482A  
      0 "No"
      1 "Yes"
      8 "Unsure"
  /MV482B  
      0 "No"
      1 "Yes"
  /MV482C  
      0 "No"
      1 "Yes"
      8 "Unsure"
  /MV483   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV483A  
     95 "During childhood <5 years"
     98 "Don't know"
  /MV483B  
      1 "Traditional practitioner"
      2 "Health worker / professional"
     96 "Other"
     98 "Don't know"
  /MV483C  
      1 "Health facility"
      2 "Home of a health worker / professional"
      3 "Circumcision done at home"
      4 "Ritual site"
     96 "Other home / place"
     98 "Don't know"
  /MV501   
      0 "Never in union"
      1 "Married"
      2 "Living with partner"
      3 "Widowed"
      4 "Divorced"
      5 "No longer living together/separated"
  /MV502   
      0 "Never in union"
      1 "Currently in union/living with a woman"
      2 "Formerly in union/living with a woman"
  /MV503   
      1 "Once"
      2 "More than once"
  /MV504   
      1 "Living with him"
      2 "Staying elsewhere"
  /MV510   
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /MV513   
      0 "Never married"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25-29"
      7 "30+"
  /MV525   
      0 "Not had sex"
     96 "At first union"
     97 "Inconsistent"
     98 "Don't know"
  /MV527   
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV528   
     31 "31+ days"
     95 "Within last 4 weeks"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
  /MV529   
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV531   
      0 "Not had sex"
     97 "Inconsistent"
     98 "Don't know"
  /MV532   
      0 "No flag"
      1 "After interview"
      2 "After conception >= 1 year"
      3 "After conception < 1 year"
      4 "At marriage, but never married"
      5 "At marriage, but after conception"
      6 "After marriage"
  /MV535   
      0 "No"
      1 "Formerly married"
      2 "Formerly lived with a woman"
      3 "Both, formerly married and lived with a woman"
  /MV536   
      0 "Never had sex"
      1 "Active in last 4 weeks"
      3 "Not active in last 4 weeks"
  /MV541   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV602   
      1 "Have another"
      2 "Undecided"
      3 "No more"
      4 "Sterilized (respondent or partner(s))"
      5 "Declared infecund (respondent or partner(s))"
      6 "Never had sex"
      7 "Man declared infecund"
      8 "Man has no partner"
  /MV603   
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon, now"
    996 "Other, non-numeric"
    997 "Inconsistent"
    998 "Don't know"
  /MV604   
      0 "<12 months"
      1 "1 year"
      2 "2 years"
      3 "3 years"
      4 "4 years"
      5 "5 years"
      6 "6+ years"
      7 "Non-numeric"
      8 "Don't know"
  /MV605   
      1 "Wants within 2 years"
      2 "Wants after 2+ years"
      3 "Wants, unsure timing"
      4 "Undecided"
      5 "Wants no more"
      6 "Sterilized (respondent or partner(s))"
      7 "Declared infecund (respondent or partner(s))"
      8 "Never had sex"
  /MV613   
     96 "Non-numeric response"
     98 "Don't know"
  /MV614   
      6 "6+"
      7 "Non-numeric response"
  /MV616   
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon/now"
    995 "Can't get pregnant"
    996 "Other"
    998 "Don't know"
  /MV621   
      1 "Both want same"
      2 "Wife wants more"
      3 "Wife wants fewer"
      8 "Don't know"
  /MV627   
     96 "Other"
     98 "Don't know"
  /MV628   
     96 "Other"
     98 "Don't know"
  /MV629   
     96 "Other"
     98 "Don't know"
  /MV631   
      1 "Big problem"
      2 "Small problem"
      3 "No problem"
      4 "Says she can't get pregnant/not having sex"
  /MV633A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV634A  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV634B  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV634C  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV634D  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV714   
      0 "No"
      1 "Yes"
  /MV714A  
      0 "No"
      1 "Yes"
  /MV716   
      0 "Not working"
      1 "Armed forces officers"
      2 "Armed forces sub-officers"
      3 "Other members of armed forces"
      6 "Other occupations"
      7 "Student"
      8 "Retired"
     11 "CEOs, managers of public administration and members of the executive and legislative bodies"
     12 "Directors and business managers"
     13 "Directors and production and operations managers"
     14 "Managers of hotels, restaurants, shops and other services"
     21 "Sciences and engineering professionals"
     22 "Professionals of health"
     23 "Professionals of education"
     24 "Planning specialists in public administration and business"
     25 "Professionals of information technology and communications"
     26 "Professionals in law, social sciences and cultural"
     31 "Professionals (medium level) of science and engineering"
     32 "Professionals (medium level) of health"
     33 "Professionals (medium level) in financial and administrative operations"
     34 "Professionals (medium level) in legal, social, cultural and related"
     35 "Technicians of the information technology and communications"
     41 "Office clerks"
     42 "Customer services clerks"
     43 "Employees in accounting and materials registration"
     44 "Other administrative support staff"
     51 "Personal services workers"
     52 "Sellers"
     53 "Personal care workers"
     54 "Protective services workers"
     61 "Farmers and skilled farm workers, market oriented"
     62 "Skilled forestry workers, fishermen and hunters"
     63 "Agricultural, fishing, hunters and subsistence gatherers workers"
     71 "Building workers, excluding electricians"
     72 "Metal, mechanical construction and related workers"
     73 "Handicraft and graphic arts workers"
     74 "Electricity and electro-technology workers"
     75 "Food processing, clothing, woodworkers, other handicraft and related workers"
     81 "Stationary plant and machines workers"
     82 "Assemblers"
     83 "Drivers and mobile-plant operators"
     91 "Cleaners and helpers"
     92 "Agricultural, forestry and fishery laborers"
     93 "Labourers in mining, construction, manufacturing and transport"
     94 "Food preparation assistants"
     95 "Street vendors and related service"
     96 "Garbage collectors and other elementary workers"
  /MV717   
      0 "Not working"
      1 "Professional/technical/managerial"
      2 "Clerical"
      3 "Sales"
      4 "Agriculture - self employed"
      5 "Agriculture - employee"
      6 "Household and domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     96 "Other"
     98 "Don't know"
  /MV719   
      1 "For family member"
      2 "For someone else"
      3 "Self-employed"
  /MV721   
      1 "At home"
      2 "Away"
  /MV731   
      0 "No"
      1 "In the past year"
      2 "Currently working"
  /MV732   
      1 "All year"
      2 "Seasonal"
      3 "Occasional"
  /MV739   
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
  /MV740   
      0 "Own land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
  /MV741   
      0 "Not paid"
      1 "Cash only"
      2 "Cash and in-kind"
      3 "In-kind only"
  /MV743A  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Other"
      8 "Don't know/depends"
  /MV743B  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Other"
      8 "Don't know/depends"
  /MV743C  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743D  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743E  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743F  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Other"
      7 "Wife/partner has no earnings"
      8 "Don't know/depends"
  /MV743G  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV744A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV745A  
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /MV745B  
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /MV747A  
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV747B  
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV750   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV751   
      0 "No"
      1 "Yes"
  /MV754BP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754CP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754DP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754JP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754WP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV756   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV761   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV761B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV761C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV762AA 
      0 "No"
      1 "Yes"
  /MV762AB 
      0 "No"
      1 "Yes"
  /MV762AC 
      0 "No"
      1 "Yes"
  /MV762AD 
      0 "No"
      1 "Yes"
  /MV762AE 
      0 "No"
      1 "Yes"
  /MV762AF 
      0 "No"
      1 "Yes"
  /MV762AG 
      0 "No"
      1 "Yes"
  /MV762AH 
      0 "No"
      1 "Yes"
  /MV762AI 
      0 "No"
      1 "Yes"
  /MV762AJ 
      0 "No"
      1 "Yes"
  /MV762AK 
      0 "No"
      1 "Yes"
  /MV762AL 
      0 "No"
      1 "Yes"
  /MV762AM 
      0 "No"
      1 "Yes"
  /MV762AN 
      0 "No"
      1 "Yes"
  /MV762AO 
      0 "No"
      1 "Yes"
  /MV762AP 
      0 "No"
      1 "Yes"
  /MV762AQ 
      0 "No"
      1 "Yes"
  /MV762AR 
      0 "No"
      1 "Yes"
  /MV762AS 
      0 "No"
      1 "Yes"
  /MV762AT 
      0 "No"
      1 "Yes"
  /MV762AU 
      0 "No"
      1 "Yes"
  /MV762AV 
      0 "No"
      1 "Yes"
  /MV762AW 
      0 "No"
      1 "Yes"
  /MV762AX 
      0 "No"
      1 "Yes"
  /MV762AZ 
      0 "No"
      1 "Yes: don't know"
  /MV762BA 
      0 "No"
      1 "Yes"
  /MV762BB 
      0 "No"
      1 "Yes"
  /MV762BC 
      0 "No"
      1 "Yes"
  /MV762BD 
      0 "No"
      1 "Yes"
  /MV762BE 
      0 "No"
      1 "Yes"
  /MV762BF 
      0 "No"
      1 "Yes"
  /MV762BG 
      0 "No"
      1 "Yes"
  /MV762BH 
      0 "No"
      1 "Yes"
  /MV762BI 
      0 "No"
      1 "Yes"
  /MV762BJ 
      0 "No"
      1 "Yes"
  /MV762BK 
      0 "No"
      1 "Yes"
  /MV762BL 
      0 "No"
      1 "Yes"
  /MV762BM 
      0 "No"
      1 "Yes"
  /MV762BN 
      0 "No"
      1 "Yes"
  /MV762BO 
      0 "No"
      1 "Yes"
  /MV762BP 
      0 "No"
      1 "Yes"
  /MV762BQ 
      0 "No"
      1 "Yes"
  /MV762BR 
      0 "No"
      1 "Yes"
  /MV762BS 
      0 "No"
      1 "Yes"
  /MV762BT 
      0 "No"
      1 "Yes"
  /MV762BU 
      0 "No"
      1 "Yes"
  /MV762BV 
      0 "No"
      1 "Yes"
  /MV762BW 
      0 "No"
      1 "Yes"
  /MV762BX 
      0 "No"
      1 "Yes"
  /MV762BZ 
      0 "No"
      1 "Yes: don't know"
  /MV763A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV766A  
     95 "95+"
     98 "Don't know"
  /MV766B  
     95 "95+"
     98 "Don't know"
  /MV767A  
      1 "Spouse"
      2 "Girlfriend/fiancé not living with respondent"
      3 "Other friend"
      4 "Casual acquaintance"
      5 "Relative"
      6 "Commercial sex worker"
      7 "Live-in partner"
     96 "Other"
  /MV767B  
      1 "Spouse"
      2 "Girlfriend/fiancé not living with respondent"
      3 "Other friend"
      4 "Casual acquaintance"
      5 "Relative"
      6 "Commercial sex worker"
      7 "Live-in partner"
     96 "Other"
  /MV767C  
      1 "Spouse"
      2 "Girlfriend/fiancé not living with respondent"
      3 "Other friend"
      4 "Casual acquaintance"
      5 "Relative"
      6 "Commercial sex worker"
      7 "Live-in partner"
     96 "Other"
  /MV768A  
    101 "One day"
    199 "Days: number missing"
    201 "One week"
    299 "Weeks: number missing"
    301 "One month"
    399 "Months: number missing"
    401 "One year"
    499 "Years: number missing"
  /MV768B  
    101 "One day"
    199 "Days: number missing"
    201 "One week"
    299 "Weeks: number missing"
    301 "One month"
    399 "Months: number missing"
    401 "One year"
    499 "Years: number missing"
  /MV768C  
    101 "One day"
    199 "Days: number missing"
    201 "One week"
    299 "Weeks: number missing"
    301 "One month"
    399 "Months: number missing"
    401 "One year"
    499 "Years: number missing"
  /MV769   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV769A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV770   
      0 "No"
      1 "Yes"
  /MV770A  
      0 "No"
      1 "Yes"
  /MV770B  
      0 "No"
      1 "Yes"
  /MV770C  
      0 "No"
      1 "Yes"
  /MV770D  
      0 "No"
      1 "Yes"
  /MV770E  
      0 "No"
      1 "Yes"
  /MV770F  
      0 "No"
      1 "Yes"
  /MV770G  
      0 "No"
      1 "Yes"
  /MV770H  
      0 "No"
      1 "Yes"
  /MV770I  
      0 "No"
      1 "Yes"
  /MV770J  
      0 "No"
      1 "Yes"
  /MV770K  
      0 "No"
      1 "Yes"
  /MV770L  
      0 "No"
      1 "Yes"
  /MV770M  
      0 "No"
      1 "Yes"
  /MV770N  
      0 "No"
      1 "Yes"
  /MV770O  
      0 "No"
      1 "Yes"
  /MV770P  
      0 "No"
      1 "Yes"
  /MV770Q  
      0 "No"
      1 "Yes"
  /MV770R  
      0 "No"
      1 "Yes"
  /MV770S  
      0 "No"
      1 "Yes"
  /MV770T  
      0 "No"
      1 "Yes"
  /MV770U  
      0 "No"
      1 "Yes"
  /MV770V  
      0 "No"
      1 "Yes"
  /MV770W  
      0 "No"
      1 "Yes"
  /MV770X  
      0 "No"
      1 "Yes"
  /MV774A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV774B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV774C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV775   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV777   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV778   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV779   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV780   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV781   
      0 "No"
      1 "Yes"
  /MV783   
      0 "No"
      1 "Yes"
  /MV784A  
      0 "No"
      1 "Yes"
  /MV784B  
      0 "No"
      1 "Yes"
  /MV784C  
      0 "No"
      1 "Yes"
  /MV784D  
      0 "No"
      1 "Yes"
  /MV784E  
      0 "No"
      1 "Yes"
  /MV784F  
      0 "No"
      1 "Yes"
  /MV784G  
      0 "No"
      1 "Yes"
  /MV784H  
      0 "No"
      1 "Yes"
  /MV784I  
      0 "No"
      1 "Yes"
  /MV784J  
      0 "No"
      1 "Yes"
  /MV784K  
      0 "No"
      1 "Yes"
  /MV784L  
      0 "No"
      1 "Yes"
  /MV784M  
      0 "No"
      1 "Yes"
  /MV784N  
      0 "No"
      1 "Yes"
  /MV784O  
      0 "No"
      1 "Yes"
  /MV784P  
      0 "No"
      1 "Yes"
  /MV784Q  
      0 "No"
      1 "Yes"
  /MV784R  
      0 "No"
      1 "Yes"
  /MV784S  
      0 "No"
      1 "Yes"
  /MV784T  
      0 "No"
      1 "Yes"
  /MV784U  
      0 "No"
      1 "Yes"
  /MV784V  
      0 "No"
      1 "Yes"
  /MV784X  
      0 "No"
      1 "Yes"
  /MV785   
      0 "No"
      1 "Yes"
  /MV791   
      0 "No"
      1 "Yes"
  /MV793   
      0 "No"
      1 "Yes"
  /MV793A  
      0 "No"
      1 "Yes"
  /MV793B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV820   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV822   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV823   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV824   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV825   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV826   
      1 "Less than 12 months"
      2 "12-23 months"
      3 "2 years or more"
  /MV826A  
     95 "Two or more years"
     98 "Don't know"
  /MV827   
      1 "Asked for the test"
      2 "Offered and accepted"
      3 "Required"
  /MV828   
      0 "No"
      1 "Yes"
  /MV829   
     10 "PUBLIC SECTOR"
     11 "Government hospital (Third level)"
     12 "Second level (health centers, maternity, mobile clinic,etc.)"
     13 "First level (health post, convergence center)"
     16 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital, clinic"
     22 "Doctor's office"
     24 "Family protection association (APROFAM)"
     25 "Social Security (IGSS)"
     26 "Other private"
     95 "Correctional institution"
     96 "Other"
  /MV832B  
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV832C  
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV833A  
      0 "No"
      1 "Yes"
  /MV833B  
      0 "No"
      1 "Yes"
  /MV833C  
      0 "No"
      1 "Yes"
  /MV834A  
     95 "95+"
     98 "Don't know"
  /MV834B  
     95 "95+"
     98 "Don't know"
  /MV834C  
     95 "95+"
     98 "Don't know"
  /MV835A  
      0 "No"
      1 "Respondent drunk only"
      2 "Partner drunk only"
      3 "Both drunk"
      4 "Neither drunk but consumed alcohol"
  /MV835B  
      0 "No"
      1 "Respondent drunk only"
      2 "Partner drunk only"
      3 "Both drunk"
      4 "Neither drunk but consumed alcohol"
  /MV835C  
      0 "No"
      1 "Respondent drunk only"
      2 "Partner drunk only"
      3 "Both drunk"
      4 "Neither drunk but consumed alcohol"
  /MV836   
     95 "95+"
     98 "Don't know"
  /MV837   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV844   
      0 "No"
      1 "Yes"
      8 "Don't know anyone with AIDS"
  /MV845   
      0 "No"
      1 "Yes"
  /MV846   
      0 "No"
      1 "Yes"
  /MV847   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/no opinion"
  /MV848   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/no opinion"
  /MV849   
      0 "No"
      1 "Yes"
      8 "Don't know/depends"
  /MV851A  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851B  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851C  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851D  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851E  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851F  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851G  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851H  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851I  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851J  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851K  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851L  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV852A  
    101 "Days: 1"
    102 "Days: 2"
    199 "Days: number missing"
    201 "Weeks: 1"
    202 "Weeks: 2"
    299 "Weeks: number missing"
    301 "Months: 1"
    302 "Months: 2"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
  /MV852B  
    101 "Days: 1"
    104 "Days: 4"
    199 "Days: number missing"
    201 "Weeks: 1"
    202 "Weeks: 2"
    299 "Weeks: number missing"
    301 "Months: 1"
    302 "Months: 2"
    399 "Months: number missing"
    401 "Years: 1"
    402 "Years: 2"
    499 "Years: number missing"
  /MV852C  
    101 "Days: 1"
    108 "Days: 8"
    199 "Days: number missing"
    201 "Weeks: 1"
    204 "Weeks: 4"
    299 "Weeks: number missing"
    301 "Months: 1"
    302 "Months: 2"
    399 "Months: number missing"
    401 "Years: 1"
    402 "Years: 2"
    499 "Years: number missing"
  /MV853A  
     95 "95+"
     98 "Don't know"
  /MV853B  
     95 "95+"
     98 "Don't know"
  /MV853C  
     95 "95+"
     98 "Don't know"
  /MV854A  
      0 "No"
      1 "Yes"
  /MV854B  
      0 "No"
      1 "Yes"
  /SMDEPTO 
      1 "Guatemala"
      2 "El Progreso"
      3 "Sacatepéquez"
      4 "Chimaltenango"
      5 "Escuintla"
      6 "Santa Rosa"
      7 "Sololá"
      8 "Totonicapán"
      9 "Quetzaltenango"
     10 "Suchitepéquez"
     11 "Retalhuleu"
     12 "San Marcos"
     13 "Huehuetenango"
     14 "Quiché"
     15 "Baja Verapaz"
     16 "Alta Verapaz"
     17 "Petén"
     18 "Izabal"
     19 "Zacapa"
     20 "Chiquimula"
     21 "Jalapa"
     22 "Jutiapa"
  /SMDEPTO2
      1 "Guatemala municipio"
      2 "Guatemala resto"
      3 "El Progreso"
      4 "Sacatepéquez"
      5 "Chimaltenango"
      6 "Escuintla"
      7 "Santa Rosa"
      8 "Sololá"
      9 "Totonicapán"
     10 "Quetzaltenango"
     11 "Suchitepéquez"
     12 "Retalhuleu"
     13 "San Marcos"
     14 "Huehuetenango"
     15 "Quiché"
     16 "Baja Verapaz"
     17 "Alta Verapaz"
     18 "Petén"
     19 "Izabal"
     20 "Zacapa"
     21 "Chiquimula"
     22 "Jalapa"
     23 "Jutiapa"
  /SMKEYER2
      0 "Not assigned"
  /SMILANG 
      1 "Spanish"
      2 "Kaqchikel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
     96 "Other"
  /SMQLANG 
      1 "Spanish"
      2 "Kaqchikel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
  /SMTRANS 
      0 "No"
      1 "Yes"
  /MV044   
      0 "Man not selected"
      1 "Man selected and interviewed"
      2 "Man selected, but privacy not possible"
      3 "Man selected, but not interviewed"
  /SMEDUC  
      0 "No education/pre-primary"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      6 "Alphabetization"
      8 "Don't know"
  /SMETID  
      0 "Not indian"
      1 "Indian"
  /SMETOB  
      0 "Not indian"
      1 "Indian"
  /SM105   
      1 "Pre-primary"
      2 "Primary"
      3 "Secondary"
      4 "Higher/university"
      5 "Alphabetization"
      8 "DK"
  /SM106   
      0 "< 1 year completed"
     98 "DK"
  /SM114   
      1 "Spanish"
      2 "Kaqchikel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
     11 "Achi"
     12 "Akateko"
     13 "Awakateko"
     14 "Chalchiteko"
     15 "Chuj"
     16 "Itza'"
     17 "Ixil"
     18 "Jakalteko (popti')"
     19 "Mopan"
     20 "Sakapulteko"
     21 "Sipakapense"
     22 "Tektiteko"
     23 "Uspanteko"
     96 "Other"
  /SM115   
      1 "Spanish"
      2 "Kaqchikel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
     11 "Achi"
     12 "Akateko"
     13 "Awakateko"
     14 "Chalchiteko"
     15 "Chuj"
     16 "Itza'"
     17 "Ixil"
     18 "Jakalteko (popti')"
     19 "Mopan"
     20 "Sakapulteko"
     21 "Sipakapense"
     22 "Tektiteko"
     23 "Uspanteko"
     96 "Other"
  /SM116   
      0 "No"
      1 "Yes"
  /SM117A  
      0 "No"
      1 "Yes"
  /SM117B  
      0 "No"
      1 "Yes"
  /SM117C  
      0 "No"
      1 "Yes"
  /SM117D  
      0 "No"
      1 "Yes"
  /SM117E  
      0 "No"
      1 "Yes"
  /SM117F  
      0 "No"
      1 "Yes"
  /SM117G  
      0 "No"
      1 "Yes"
  /SM117H  
      0 "No"
      1 "Yes"
  /SM117I  
      0 "No"
      1 "Yes"
  /SM117J  
      0 "No"
      1 "Yes"
  /SM117K  
      0 "No"
      1 "Yes"
  /SM117L  
      0 "No"
      1 "Yes"
  /SM117M  
      0 "No"
      1 "Yes"
  /SM117N  
      0 "No"
      1 "Yes"
  /SM117O  
      0 "No"
      1 "Yes"
  /SM117P  
      0 "No"
      1 "Yes"
  /SM117Q  
      0 "No"
      1 "Yes"
  /SM117R  
      0 "No"
      1 "Yes"
  /SM117S  
      0 "No"
      1 "Yes"
  /SM117T  
      0 "No"
      1 "Yes"
  /SM117U  
      0 "No"
      1 "Yes"
  /SM117V  
      0 "No"
      1 "Yes"
  /SM117W  
      0 "No"
      1 "Yes"
  /SM117X  
      0 "No"
      1 "Yes"
  /SM119   
      2 "Kaqchikel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
     11 "Achi"
     12 "Akateka"
     13 "Awakateka"
     14 "Chalchiteka"
     15 "Chuj"
     16 "Itza'"
     17 "Ixil"
     18 "Jakalteka (popti')"
     19 "Mopan"
     20 "Sakapulteka"
     21 "Sipakapense"
     22 "Tektiteka"
     23 "Uspanteka"
     96 "Other"
  /SM120   
      0 "Not indian"
      1 "Indian"
  /SM219   
      1 "Hospital/health institution"
      2 "Home/traditional birth attendant"
      6 "Other"
      8 "Don't know"
  /SM222   
      1 "Before period begins"
      2 "During her period"
      3 "After period ended"
      4 "Middle of the cycle"
      5 "Days in string with white color"
      6 "Days in string with brown color"
     96 "Other"
     98 "DK"
  /SM303D  
      0 "No"
      1 "Yes"
  /SM308L  
      0 "No"
      1 "Yes"
  /SM308M  
      0 "No"
      1 "Yes"
  /SM308N  
      0 "No"
      1 "Yes"
  /SM308O  
      0 "No"
      1 "Yes"
  /SM308P  
      0 "No"
      1 "Yes"
  /SM308Q  
      0 "No"
      1 "Yes"
  /SM308R  
      0 "No"
      1 "Yes"
  /SM308S  
      0 "No"
      1 "Yes"
  /SM308T  
      0 "No"
      1 "Yes"
  /SM423   
      0 "No"
      1 "Yes"
      8 "DK"
  /SM433   
     11 "Public hospital"
     12 "Health center"
     13 "Health center type a"
     14 "Health center type b"
     15 "Health stand (open)"
     16 "Health stand (close)"
     17 "Health stand strengthened (PSF)"
     18 "Convergence center"
     19 "Maternal/child care center (CAIMI)"
     20 "Outpatient care center (CENAPA)"
     21 "Permanent care center (CAP)"
     22 "Maternity"
     23 "Mobile clinic"
     24 "Minimum emergency center (CUM)"
     25 "Peripheral clinic"
     26 "Neurological rehabilitation center (CRN)"
     27 "Minimum unit"
     36 "Other public place"
     41 "Private clinic/hospital"
     42 "Doctor's office"
     43 "APROFAM"
     44 "Pharmacy"
     45 "IGSS"
     46 "Other private place"
     51 "Healer/midwife/traditional birth attendant"
     56 "Health promoter"
     57 "Health guardian"
     96 "Other"
     98 "DK"
  /SM616A  
      0 "No"
      1 "Yes - listening"
      2 "Yes - not listening"
  /SM616B  
      0 "No"
      1 "Yes - listening"
      2 "Yes - not listening"
  /SM616C  
      0 "No"
      1 "Yes - listening"
      2 "Yes - not listening"
  /SM616D  
      0 "No"
      1 "Yes - listening"
      2 "Yes - not listening"
  /SM708K  
      0 "No"
      1 "Yes"
  /SM708L  
      0 "No"
      1 "Yes"
  /SM708M  
      0 "No"
      1 "Yes"
  /SM708N  
      0 "No"
      1 "Yes"
  /SM708O  
      0 "No"
      1 "Yes"
  /SM708P  
      0 "No"
      1 "Yes"
  /SM708Q  
      0 "No"
      1 "Yes"
  /SM708R  
      0 "No"
      1 "Yes"
  /SM708S  
      0 "No"
      1 "Yes"
  /SM708T  
      0 "No"
      1 "Yes"
  /SM708X  
      0 "No"
      1 "Yes"
  /SM708JJ 
      0 "No"
      1 "Yes"
  /SM711   
      0 "No"
      1 "Yes"
  /SM726   
      0 "No"
      1 "Yes"
      8 "DK"
  /SM727   
      0 "No"
      1 "Yes"
      8 "DK"
  /SM728   
     11 "Public hospital"
     12 "Health center"
     13 "Health center type a"
     14 "Health center type b"
     19 "Maternal/child care center (CAIMI)"
     20 "Outpatient care center (CENAPA)"
     21 "Permanent care center (CAP)"
     22 "Maternity"
     23 "Mobile clinic"
     24 "Minimum emergency center (CUM)"
     25 "Peripheral clinic"
     26 "Neurological rehabilitation center (CRN)"
     27 "Minimum unit"
     36 "Other public place"
     41 "Private clinic/hospital"
     42 "Doctor's office"
     43 "APROFAM"
     45 "IGSS"
     46 "Other private place"
     55 "Correctional institution"
     96 "Other"
  /SM730K  
      0 "No"
      1 "Yes"
  /SM730L  
      0 "No"
      1 "Yes"
  /SM730M  
      0 "No"
      1 "Yes"
  /SM730N  
      0 "No"
      1 "Yes"
  /SM730O  
      0 "No"
      1 "Yes"
  /SM730P  
      0 "No"
      1 "Yes"
  /SM730Q  
      0 "No"
      1 "Yes"
  /SM730R  
      0 "No"
      1 "Yes"
  /SM730S  
      0 "No"
      1 "Yes"
  /SM730T  
      0 "No"
      1 "Yes"
  /SM730X  
      0 "No"
      1 "Yes"
  /SM730JJ 
      0 "No"
      1 "Yes"
  /SM737   
      0 "No"
      1 "Yes"
      8 "DK/don't respond"
  /SM738   
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    998 "DK"
  /SM739   
      0 "No"
      1 "Yes"
      8 "DK/don't respond"
  /SM807   
      1 "Health center"
      2 "Private clinic/professional"
      3 "Ritual place"
      6 "Other home/place"
      8 "DK"
  /SM812   
      0 "No"
      1 "Yes"
  /SM813   
     98 "DK/don't remember"
  /SM814   
      0 "No"
      1 "Yes"
  /SM815   
     98 "DK/don't remember"
  /SM816AA 
      0 "No"
      1 "Yes"
  /SM816AB 
      0 "No"
      1 "Yes"
  /SM816AC 
      0 "No"
      1 "Yes"
  /SM816AD 
      0 "No"
      1 "Yes"
  /SM816AE 
      0 "No"
      1 "Yes"
  /SM816AF 
      0 "No"
      1 "Yes"
  /SM816AG 
      0 "No"
      1 "Yes"
  /SM816AH 
      0 "No"
      1 "Yes"
  /SM816AI 
      0 "No"
      1 "Yes"
  /SM816AJ 
      0 "No"
      1 "Yes"
  /SM816AK 
      0 "No"
      1 "Yes"
  /SM816AL 
      0 "No"
      1 "Yes"
  /SM816AM 
      0 "No"
      1 "Yes"
  /SM816AN 
      0 "No"
      1 "Yes"
  /SM816AO 
      0 "No"
      1 "Yes"
  /SM816AP 
      0 "No"
      1 "Yes"
  /SM816AQ 
      0 "No"
      1 "Yes"
  /SM816AR 
      0 "No"
      1 "Yes"
  /SM816AS 
      0 "No"
      1 "Yes"
  /SM816AT 
      0 "No"
      1 "Yes"
  /SM816AU 
      0 "No"
      1 "Yes"
  /SM816AV 
      0 "No"
      1 "Yes"
  /SM816AW 
      0 "No"
      1 "Yes"
  /SM816AX 
      0 "No"
      1 "Yes"
  /SM816BA 
      0 "No"
      1 "Yes"
  /SM816BB 
      0 "No"
      1 "Yes"
  /SM816BC 
      0 "No"
      1 "Yes"
  /SM816BD 
      0 "No"
      1 "Yes"
  /SM816BE 
      0 "No"
      1 "Yes"
  /SM816BF 
      0 "No"
      1 "Yes"
  /SM816BG 
      0 "No"
      1 "Yes"
  /SM816BH 
      0 "No"
      1 "Yes"
  /SM816BI 
      0 "No"
      1 "Yes"
  /SM816BJ 
      0 "No"
      1 "Yes"
  /SM816BK 
      0 "No"
      1 "Yes"
  /SM816BL 
      0 "No"
      1 "Yes"
  /SM816BM 
      0 "No"
      1 "Yes"
  /SM816BN 
      0 "No"
      1 "Yes"
  /SM816BO 
      0 "No"
      1 "Yes"
  /SM816BP 
      0 "No"
      1 "Yes"
  /SM816BQ 
      0 "No"
      1 "Yes"
  /SM816BR 
      0 "No"
      1 "Yes"
  /SM816BS 
      0 "No"
      1 "Yes"
  /SM816BT 
      0 "No"
      1 "Yes"
  /SM816BU 
      0 "No"
      1 "Yes"
  /SM816BV 
      0 "No"
      1 "Yes"
  /SM816BW 
      0 "No"
      1 "Yes"
  /SM816BX 
      0 "No"
      1 "Yes"
  /SM819A  
      0 "No"
      1 "Yes"
  /SM819B  
      0 "No"
      1 "Yes"
  /SM819C  
      0 "No"
      1 "Yes"
  /SM905A2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM905B2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM905C2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906A2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906B2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906C2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906D2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906E2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906F2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906G2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906H2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM906I2 
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      4 "Yes, but not in the last 12 months"
  /SM911   
      0 "Not at all in last 12 months"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
      8 "Don't know"
  /SM916B  
      0 "Never"
      1 "0-11 months ago"
      2 "12+ months ago"
      3 "Yes, but don't remember when"
      4 "Yes, but frequency in last 12 months missing"
  /SM916C  
      0 "Never"
      1 "0-11 months ago"
      2 "12+ months ago"
      3 "Yes, but don't remember when"
      4 "Yes, but frequency in last 12 months missing"
  /SM919   
      0 "Not at all"
      1 "Often"
      2 "Sometimes"
      3 "Rarely"
  /SM921A  
      0 "No"
      1 "Yes"
      3 "Refused to answer/no response"
  /SM921B  
      0 "No"
      1 "Yes"
      3 "Refused to answer/no response"
  /SM922A  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922B  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922C  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922D  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922E  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922F  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922G  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922H  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922I  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922K  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922L  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922M  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922N  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922O  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922P  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922Q  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM922X  
      0 "No"
      1 "Yes"
      3 "Refuse to answer/don't respond"
  /SM928AA 
      0 "No"
      1 "Yes"
  /SM928BB 
      0 "No"
      1 "Yes"
  /SM928CC 
      0 "No"
      1 "Yes"
  /SM929   
      0 "No"
      1 "Yes"
  /SM932D  
      0 "No"
      1 "Yes, once"
      2 "Yes, more than once"
  /MD101A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101I  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD101J  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD103A  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD103B  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD103C  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD103D  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD103E  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD103F  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD104   
      0 "No"
      1 "Yes"
  /MD105A  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105B  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105C  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105D  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105E  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105F  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105G  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105H  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105I  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105J  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105K  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105L  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105M  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD105N  
      0 "Never"
      1 "Often"
      2 "Sometimes"
      3 "Yes, but not in the last 12 months"
      4 "Yes, but frequency in last 12 months missing"
  /MD106   
      0 "No"
      1 "Yes"
  /MD107   
      0 "No"
      1 "Yes"
  /MD108   
      0 "No"
      1 "Yes"
  /MD109   
      0 "Less than 1 year ago"
     95 "Before union"
     96 "After separation/divorce"
     98 "Don't know"
  /MD110A  
      0 "No"
      1 "Yes"
  /MD110B  
      0 "No"
      1 "Yes"
  /MD110D  
      0 "No"
      1 "Yes"
  /MD110C  
      0 "No"
      1 "Yes"
  /MD110E  
      0 "No"
      1 "Yes"
  /MD110F  
      0 "No"
      1 "Yes"
  /MD110G  
      0 "No"
      1 "Yes"
  /MD110H  
      0 "No"
      1 "Yes"
  /MD111   
      0 "No"
      1 "Yes"
  /MD112   
      0 "No"
      1 "Yes"
  /MD112A  
      0 "Not at all in last 12 months"
      1 "Often"
      2 "Sometimes"
      8 "Don't know"
  /MD113   
      0 "No"
      1 "Yes"
  /MD114   
      0 "Never"
      1 "Often"
      2 "Sometimes"
  /MD115B  
      0 "No"
      1 "Yes"
  /MD115C  
      0 "No"
      1 "Yes"
  /MD115D  
      0 "No"
      1 "Yes"
  /MD115E  
      0 "No"
      1 "Yes"
  /MD115F  
      0 "No"
      1 "Yes"
  /MD115G  
      0 "No"
      1 "Yes"
  /MD115H  
      0 "No"
      1 "Yes"
  /MD115I  
      0 "No"
      1 "Yes"
  /MD115J  
      0 "No"
      1 "Yes"
  /MD115K  
      0 "No"
      1 "Yes"
  /MD115L  
      0 "No"
      1 "Yes"
  /MD115M  
      0 "No"
      1 "Yes"
  /MD115N  
      0 "No"
      1 "Yes"
  /MD115O  
      0 "No"
      1 "Yes"
  /MD115P  
      0 "No"
      1 "Yes"
  /MD115Q  
      0 "No"
      1 "Yes"
  /MD115R  
      0 "No"
      1 "Yes"
  /MD115S  
      0 "No"
      1 "Yes"
  /MD115T  
      0 "No"
      1 "Yes"
  /MD115U  
      0 "No"
      1 "Yes"
  /MD115V  
      0 "No"
      1 "Yes"
  /MD115W  
      0 "No"
      1 "Yes"
  /MD115X  
      0 "No"
      1 "Yes"
  /MD115Y  
      0 "Someone physically hurt respondent"
      1 "None of these people ever physically hurt respondent"
      6 "No response to question"
  /MD115XA 
      0 "No"
      1 "Yes"
  /MD115XB 
      0 "No"
      1 "Yes"
  /MD115XC 
      0 "No"
      1 "Yes"
  /MD115XD 
      0 "No"
      1 "Yes"
  /MD115XE 
      0 "No"
      1 "Yes"
  /MD115XF 
      0 "No"
      1 "Yes"
  /MD115XG 
      0 "No"
      1 "Yes"
  /MD115XH 
      0 "No"
      1 "Yes"
  /MD115XI 
      0 "No"
      1 "Yes"
  /MD115XJ 
      0 "No"
      1 "Yes"
  /MD115XK 
      0 "No"
      1 "Yes"
  /MD117A  
      0 "Not at all"
      1 "Often"
      2 "Sometimes"
  /MD119A  
      0 "No"
      1 "Yes"
  /MD119B  
      0 "No"
      1 "Yes"
  /MD119C  
      0 "No"
      1 "Yes"
  /MD119D  
      0 "No"
      1 "Yes"
  /MD119E  
      0 "No"
      1 "Yes"
  /MD119F  
      0 "No"
      1 "Yes"
  /MD119G  
      0 "No"
      1 "Yes"
  /MD119H  
      0 "No"
      1 "Yes"
  /MD119I  
      0 "No"
      1 "Yes"
  /MD119J  
      0 "No"
      1 "Yes"
  /MD119K  
      0 "No"
      1 "Yes"
  /MD119L  
      0 "No"
      1 "Yes"
  /MD119M  
      0 "No"
      1 "Yes"
  /MD119N  
      0 "No"
      1 "Yes"
  /MD119O  
      0 "No"
      1 "Yes"
  /MD119P  
      0 "No"
      1 "Yes"
  /MD119Q  
      0 "No"
      1 "Yes"
  /MD119R  
      0 "No"
      1 "Yes"
  /MD119S  
      0 "No"
      1 "Yes"
  /MD119T  
      0 "No"
      1 "Yes"
  /MD119U  
      0 "No"
      1 "Yes"
  /MD119V  
      0 "No"
      1 "Yes"
  /MD119W  
      0 "No"
      1 "Yes"
  /MD119X  
      0 "No"
      1 "Yes"
  /MD119Y  
      0 "Sought help from someone"
      1 "No help was sought"
  /MD119XA 
      0 "No"
      1 "Yes"
  /MD119XB 
      0 "No"
      1 "Yes"
  /MD119XC 
      0 "No"
      1 "Yes"
  /MD119XD 
      0 "No"
      1 "Yes"
  /MD119XE 
      0 "No"
      1 "Yes"
  /MD119XF 
      0 "No"
      1 "Yes"
  /MD119XG 
      0 "No"
      1 "Yes"
  /MD119XH 
      0 "No"
      1 "Yes"
  /MD119XI 
      0 "No"
      1 "Yes"
  /MD119XJ 
      0 "No"
      1 "Yes"
  /MD119XK 
      0 "No"
      1 "Yes"
  /MD116   
      0 "No one else ever physically hurt respondent"
      1 "BLANK (Wife/partner skipped for this question)"
      2 "Mother"
      3 "Father"
      4 "Daughter"
      5 "Son"
      6 "Sister"
      7 "Brother"
      8 "Other female relatives"
      9 "Other male relatives"
     10 "Former partner"
     11 "Current girlfriend"
     12 "Former girlfriend"
     13 "Step-mother"
     14 "Step-father"
     15 "Mother-in-law"
     16 "Father-in-law"
     17 "Other female in-laws"
     18 "Other male in-laws"
     19 "Female friend, acquaintance"
     20 "Male friend, acquaintance"
     21 "Neighbor"
     22 "Teacher"
     23 "Employer"
     27 "Stranger"
     28 "Other female relative/in-law"
     29 "Other male relative/in-law"
     30 "Friend"
     31 "Police"
     95 "No response (D115Y=6)"
     96 "Other"
  /MD120   
      1 "Don't know where to go to"
      2 "No use"
      3 "Part of life"
      4 "Afraid of divorce"
      5 "Afraid of further beatings"
      6 "Afraid of getting the person in trouble"
      7 "Embarrassed"
      8 "Don't want to disgrace family"
      9 "No money"
     96 "Other"
  /MD121   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MD122A  
      0 "No"
      1 "Yes, once"
      2 "Yes, more than once"
  /MD122B  
      0 "No"
      1 "Yes, once"
      2 "Yes, more than once"
  /MD122C  
      0 "No"
      1 "Yes, once"
      2 "Yes, more than once"
  /MD123   
      1 "Wanted"
      2 "Forced"
      6 "Refused to answer/no response"
  /MD124   
      0 "No"
      1 "Yes"
      6 "Refused to answer/no response"
  /MD125   
      0 "No"
      1 "Yes"
      6 "Refused to answer/no response"
  /MD126   
     98 "Don't know"
  /MD127   
      1 "Current wife/partner"
      2 "Former wife/partner"
      3 "Current/former girlfriend"
      4 "Father/step father"
      5 "Brother/step brother"
      6 "Other relative"
      7 "In-law"
      8 "Own friend/acquaintance"
      9 "Family friend"
     10 "Teacher"
     11 "Employer/someone at work"
     12 "Police/soldier"
     13 "Priest/religious leader"
     14 "Stranger"
     93 "Don't respond"
     96 "Other"
  /MD128   
      0 "No"
      1 "Yes"
  /MD129   
      0 "Never afraid"
      1 "Most of the time afraid"
      2 "Sometimes afraid"
  /MD130A  
      0 "Never"
      1 "0-11 months ago"
      2 "12+ months ago"
      3 "Yes, but don't remember when"
      4 "Yes, but frequency in last 12 months missing"
  /MD130B  
      0 "Never"
      1 "0-11 months ago"
      2 "12+ months ago"
      3 "Yes, but don't remember when"
      4 "Yes, but frequency in last 12 months missing"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\GU71\GUMR71FL.sav'.
