DATA LIST FILE='C:\COUNTRIES\GU71\GUPR71FL.DAT' RECORDS=1
  /
  HHID        1-12   (A)
  HVIDX      13-14  
  HV000      15-17   (A)
  HV001      18-25  
  HV002      26-29  
  HV003      30-32  
  HV004      33-36  
  HV005      37-44  
  HV006      45-46  
  HV007      47-50  
  HV008      51-54  
  HV009      55-56  
  HV010      57-58  
  HV011      59-60  
  HV012      61-62  
  HV013      63-64  
  HV014      65-66  
  HV015      67-67  
  HV016      68-69  
  HV017      70-70  
  HV018      71-73  
  HV019      74-75  
  HV020      76-76  
  HV021      77-80  
  HV022      81-84  
  HV023      85-86  
  HV024      87-88  
  HV025      89-89  
  HV026      90-90  
  HV027      91-91  
  HV028      92-99  
  HV030     100-102 
  HV031     103-105 
  HV032     106-107 
  HV035     108-109 
  HV040     110-113 
  HV041     114-115 
  HV042     116-116 
  HV044     117-117 
  HV201     118-119 
  HV202     120-121 
  HV204     122-124 
  HV205     125-126 
  HV206     127-127 
  HV207     128-128 
  HV208     129-129 
  HV209     130-130 
  HV210     131-131 
  HV211     132-132 
  HV212     133-133 
  HV213     134-135 
  HV214     136-137 
  HV215     138-139 
  HV216     140-141 
  HV217     142-142 
  HV218     143-144 
  HV219     145-145 
  HV220     146-147 
  HV221     148-148 
  HV225     149-149 
  HV226     150-151 
  HV227     152-152 
  HV228     153-153 
  HV230A    154-154 
  HV230B    155-155 
  HV232     156-156 
  HV232B    157-157 
  HV232C    158-158 
  HV232D    159-159 
  HV232E    160-160 
  HV232Y    161-161 
  HV234     162-164 
  HV234A    165-165 
  HV235     166-166 
  HV236     167-167 
  HV237     168-168 
  HV237A    169-169 
  HV237B    170-170 
  HV237C    171-171 
  HV237D    172-172 
  HV237E    173-173 
  HV237F    174-174 
  HV237G    175-175 
  HV237H    176-176 
  HV237I    177-177 
  HV237J    178-178 
  HV237K    179-179 
  HV237X    180-180 
  HV237Z    181-181 
  HV238     182-183 
  HV239     184-184 
  HV240     185-185 
  HV241     186-186 
  HV242     187-187 
  HV243A    188-188 
  HV243B    189-189 
  HV243C    190-190 
  HV243D    191-191 
  HV244     192-192 
  HV245     193-195 
  HV246     196-196 
  HV246A    197-198 
  HV246B    199-200 
  HV246C    201-202 
  HV246D    203-204 
  HV246E    205-206 
  HV246F    207-208 
  HV246G    209-210 
  HV246H    211-212 
  HV246I    213-214 
  HV246J    215-216 
  HV246K    217-218 
  HV247     219-219 
  HV252     220-220 
  HV253     221-221 
  HV253A    222-222 
  HV253B    223-223 
  HV253C    224-224 
  HV253D    225-225 
  HV253E    226-226 
  HV253F    227-227 
  HV253G    228-228 
  HV253H    229-229 
  HV253X    230-230 
  HV253Z    231-231 
  HV270     232-232 
  HV271     233-240 
  HML1      241-242 
  HML1A     243-243 
  HML2      244-245 
  CHL0      246-247 
  SHDEPTO   248-249 
  SHDEPTO2  250-251 
  SHSTARTH  252-253 
  SHSTARTM  254-255 
  SHILANG   256-257 
  SHQLANG   258-259 
  SHTRANS   260-260 
  SHNUMDV   261-262 
  SH109B    263-263 
  SH109H    264-264 
  SH109I    265-265 
  SH109J    266-266 
  SH109K    267-267 
  SH109L    268-268 
  SH119U    269-269 
  SH119N    270-272 
  SH123     273-273 
  SH124     274-274 
  SH125     275-275 
  SH126     276-276 
  SH127     277-277 
  SH128     278-278 
  SH132H    279-280 
  SH132M    281-282 
  SH200H    283-284 
  SH200M    285-286 
  SH252A    287-289 
  SH252B    290-292 
  SH253A    293-294 
  SH253B    295-296 
  SH253C    297-298 
  SH254H    299-300 
  SH254M    301-302 
  HV101     303-304 
  HV102     305-305 
  HV103     306-306 
  HV104     307-307 
  HV105     308-309 
  HV106     310-310 
  HV107     311-312 
  HV108     313-314 
  HV109     315-315 
  HV110     316-316 
  HV111     317-317 
  HV112     318-319 
  HV113     320-320 
  HV114     321-322 
  HV115     323-323 
  HV116     324-324 
  HV117     325-325 
  HV118     326-326 
  HV120     327-327 
  HV121     328-328 
  HV122     329-329 
  HV123     330-331 
  HV124     332-333 
  HV125     334-334 
  HV126     335-335 
  HV127     336-337 
  HV128     338-339 
  HV129     340-340 
  HV140     341-341 
  IDXH4     342-343 
  SHEDUC    344-344 
  SH16      345-345 
  SH17A     346-346 
  SH17B     347-348 
  SH18      349-349 
  SH19A     350-350 
  SH19B     351-352 
  SH205     353-353 
  SH209H    354-355 
  SH209M    356-357 
  SH215     358-358 
  SH216     359-359 
  SH217H    360-361 
  SH217M    362-363 
  SH218     364-364 
  SH219     365-367 
  SH220     368-368 
  SH221     369-369 
  SH222H    370-371 
  SH222M    372-373 
  SHETID    374-374 
  SHETOB    375-375 
  SH229     376-376 
  SH232H    377-378 
  SH232M    379-380 
  SH241     381-381 
  SH242     382-382 
  SH243H    383-384 
  SH243M    385-386 
  SH244     387-387 
  SH245     388-390 
  SH246     391-391 
  SH247     392-392 
  SH248H    393-394 
  SH248M    395-396 
  SH250D    397-398 
  SH250M    399-400 
  SH250Y    401-404 
  HA0       405-406 
  HA1       407-408 
  HA2       409-412 
  HA3       413-416 
  HA4       417-420 
  HA5       421-424 
  HA6       425-429 
  HA11      430-433 
  HA12      434-438 
  HA12A     439-443 
  HA12B     444-448 
  HA13      449-449 
  HA32      450-453 
  HA33      454-454 
  HA35      455-456 
  HA40      457-460 
  HA41      461-464 
  HA50      465-465 
  HA51      466-467 
  HA52      468-468 
  HA53      469-471 
  HA54      472-472 
  HA55      473-473 
  HA56      474-476 
  HA57      477-477 
  HA58      478-478 
  HA60      479-479 
  HA61      480-480 
  HA62      481-485  (A)
  HA63      486-486 
  HA64      487-487 
  HA65      488-488 
  HA66      489-489 
  HA67      490-491 
  HA68      492-492 
  HA69      493-500 
  HA70      501-503 
  HC0       504-505 
  HC1       506-507 
  HC2       508-511 
  HC3       512-515 
  HC4       516-519 
  HC5       520-523 
  HC6       524-528 
  HC7       529-532 
  HC8       533-536 
  HC9       537-541 
  HC10      542-545 
  HC11      546-549 
  HC12      550-554 
  HC13      555-555 
  HC15      556-556 
  HC16      557-558 
  HC17      559-560 
  HC18      561-562 
  HC19      563-566 
  HC27      567-567 
  HC30      568-569 
  HC31      570-573 
  HC32      574-577 
  HC33      578-578 
  HC51      579-580 
  HC52      581-581 
  HC53      582-584 
  HC55      585-585 
  HC56      586-588 
  HC57      589-589 
  HC58      590-590 
  HC60      591-593 
  HC61      594-594 
  HC62      595-596 
  HC63      597-599 
  HC64      600-601 
  HC68      602-602 
  HC70      603-606 
  HC71      607-610 
  HC72      611-614 
  HC73      615-618 
 .
VARIABLE LABELS
   HHID     "Case Identification"
  /HVIDX    "Line number"
  /HV000    "Country code and phase"
  /HV001    "Cluster number"
  /HV002    "Household number"
  /HV003    "Respondent's line number (answering Household questionnaire)"
  /HV004    "Ultimate area unit"
  /HV005    "Household sample weight (6 decimals)"
  /HV006    "Month of interview"
  /HV007    "Year of interview"
  /HV008    "Date of interview (CMC)"
  /HV009    "Number of household members"
  /HV010    "Number of eligible women in household"
  /HV011    "Number of eligible men in household"
  /HV012    "Number of de jure members"
  /HV013    "Number of de facto members"
  /HV014    "Number of children 5 and under (de jure)"
  /HV015    "Result of household interview"
  /HV016    "Day of interview"
  /HV017    "Number of visits"
  /HV018    "Interviewer identification"
  /HV019    "Keyer identification"
  /HV020    "Ever-married sample"
  /HV021    "Primary sampling unit"
  /HV022    "Sample strata for sampling errors"
  /HV023    "Stratification used in sample design"
  /HV024    "Region"
  /HV025    "Type of place of residence"
  /HV026    "NA - Place of residence"
  /HV027    "Household selected for male interview"
  /HV028    "Household weight for male subsample (6 decimals)"
  /HV030    "Field supervisor"
  /HV031    "Field editor"
  /HV032    "Office editor"
  /HV035    "Number of eligible children for height and weight"
  /HV040    "Cluster altitude in meters"
  /HV041    "Total adults measured"
  /HV042    "Household selected for hemoglobin"
  /HV044    "Household selected for Domestic Violence module"
  /HV201    "Source of drinking water"
  /HV202    "NA - Source of non-drinking water"
  /HV204    "Time to get to water source (minutes)"
  /HV205    "Type of toilet facility"
  /HV206    "Has electricity"
  /HV207    "Has radio"
  /HV208    "Has television"
  /HV209    "Has refrigerator"
  /HV210    "Has bicycle"
  /HV211    "Has motorcycle/scooter"
  /HV212    "Has car/truck"
  /HV213    "Main floor material"
  /HV214    "Main wall material"
  /HV215    "Main roof material"
  /HV216    "Number of rooms used for sleeping"
  /HV217    "Relationship structure"
  /HV218    "Line number of head of household"
  /HV219    "Sex of head of household"
  /HV220    "Age of head of household"
  /HV221    "Has telephone (land-line)"
  /HV225    "Share toilet with other households"
  /HV226    "Type of cooking fuel"
  /HV227    "NA - Has mosquito bed net for sleeping"
  /HV228    "NA - Children under 5 slept under mosquito bed net last night"
  /HV230A   "Place where household members wash their hands"
  /HV230B   "Presence of water at hand washing place"
  /HV232    "Items present: Soap or detergent"
  /HV232B   "Items present: Ash, mud, sand"
  /HV232C   "NA - Items present: CS"
  /HV232D   "NA - Items present: CS"
  /HV232E   "NA - Items present: CS"
  /HV232Y   "Items present: None"
  /HV234    "NA - Result of salt test for iodine (PPM)"
  /HV234A   "NA - Result of salt test for iodine"
  /HV235    "Location of source for water"
  /HV236    "NA - Person fetching water"
  /HV237    "Anything done to water to make safe to drink"
  /HV237A   "Water usually treated by: boil"
  /HV237B   "Water usually treated by: add bleach/chlorine"
  /HV237C   "Water usually treated by: strain through a cloth"
  /HV237D   "Water usually treated by: use water filter"
  /HV237E   "Water usually treated by: solar disinfection"
  /HV237F   "Water usually treated by: let it stand and settle"
  /HV237G   "NA - Water usually treated by: CS"
  /HV237H   "NA - Water usually treated by: CS"
  /HV237I   "NA - Water usually treated by: CS"
  /HV237J   "NA - Water usually treated by: CS"
  /HV237K   "NA - Water usually treated by: CS"
  /HV237X   "Water usually treated by: other"
  /HV237Z   "Water usually treated by: don't know"
  /HV238    "Number of households sharing toilet"
  /HV239    "NA - Food cooked on stove or open fire"
  /HV240    "NA - Household has a chimney, hood or neither"
  /HV241    "Food cooked in the house/ separate building/ outdoors"
  /HV242    "Household has separate room used as kitchen"
  /HV243A   "Has mobile telephone"
  /HV243B   "Has watch"
  /HV243C   "Has animal-drawn cart"
  /HV243D   "Has boat with a motor"
  /HV244    "Owns land usable for agriculture"
  /HV245    "Hectares of agricultural land (1 decimal)"
  /HV246    "Owns livestock, herds or farm animals"
  /HV246A   "NA - Owns cattle"
  /HV246B   "Owns cows/ bulls/calves"
  /HV246C   "Owns horses/ donkeys/ mules"
  /HV246D   "Owns goats/sheep"
  /HV246E   "NA - Owns sheep"
  /HV246F   "Owns chickens/poultry"
  /HV246G   "Owns pigs"
  /HV246H   "NA - Owns CS"
  /HV246I   "NA - Owns CS"
  /HV246J   "NA - Owns CS"
  /HV246K   "NA - Owns CS"
  /HV247    "NA - Has bank account"
  /HV252    "NA - Frequency household members smoke inside the house"
  /HV253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
  /HV253A   "NA - Dwelling sprayed by: government worker/program"
  /HV253B   "NA - Dwelling sprayed by: private company"
  /HV253C   "NA - Dwelling sprayed by: NGO"
  /HV253D   "NA - Dwelling sprayed by: CS"
  /HV253E   "NA - Dwelling sprayed by: CS"
  /HV253F   "NA - Dwelling sprayed by: CS"
  /HV253G   "NA - Dwelling sprayed by: CS"
  /HV253H   "NA - Dwelling sprayed by: CS"
  /HV253X   "NA - Dwelling sprayed by: other"
  /HV253Z   "NA - Dwelling sprayed by: don't know"
  /HV270    "Wealth index"
  /HV271    "Wealth index factor score (5 decimals)"
  /HML1     "NA - Number of mosquito bed nets"
  /HML1A    "NA - Number of mosquito bed nets with specific information"
  /HML2     "NA - Number of children under mosquito bed net previous night"
  /CHL0     "NA - Number of de-jure children 5-14 for child labor module"
  /SHDEPTO  "Department"
  /SHDEPTO2 "Department"
  /SHSTARTH "Time interview started (hour)"
  /SHSTARTM "Time interview started (minutes)"
  /SHILANG  "Interview language"
  /SHQLANG  "Questionnaire language"
  /SHTRANS  "Translator used"
  /SHNUMDV  "Line number of person eligible for domestic violence"
  /SH109B   "Solar energy"
  /SH109H   "Washing machine"
  /SH109I   "Dryer"
  /SH109J   "Microwave oven"
  /SH109K   "Computer"
  /SH109L   "Internet"
  /SH119U   "Agricultural land (unit)"
  /SH119N   "Agricultural land (number) (1 decimal)"
  /SH123    "Ran out of food in the last 30 days"
  /SH124    "Times ran out of food in the last 30 days"
  /SH125    "Any household member has slept with hunger in the last 30 days"
  /SH126    "Time any household member has slept with hunger in the last 30 days"
  /SH127    "Any household member has spent a whole day and night without eating in the last 30 days"
  /SH128    "Times any household member has spent a whole day and night without eating in the last 30 days"
  /SH132H   "Time interview ended (hour)"
  /SH132M   "Time interview ended (minutes)"
  /SH200H   "Time biomarker interview started (hour)"
  /SH200M   "Time biomarker interview started (minutes)"
  /SH252A   "Anthropometrist code"
  /SH252B   "Assistant code"
  /SH253A   "Scale number"
  /SH253B   "Measuring ruler number"
  /SH253C   "Hemocue number"
  /SH254H   "Time interview ended (hour)"
  /SH254M   "Time interview ended (minutes)"
  /HV101    "Relationship to head"
  /HV102    "Usual resident"
  /HV103    "Slept last night"
  /HV104    "Sex of household member"
  /HV105    "Age of household members"
  /HV106    "Highest educational level attained"
  /HV107    "Highest year of education completed"
  /HV108    "Education completed in single years"
  /HV109    "Educational attainment"
  /HV110    "NA - Member still in school"
  /HV111    "Mother alive"
  /HV112    "Mother's line number"
  /HV113    "Father alive"
  /HV114    "Father's line number"
  /HV115    "Current marital status"
  /HV116    "Currently, formerly, never married"
  /HV117    "Eligibility for female interview"
  /HV118    "Eligibility for male interview"
  /HV120    "Children eligibility for height/weight and hemoglobin"
  /HV121    "Member attended school during current school year"
  /HV122    "Educational level during current school year"
  /HV123    "Grade of education during current school year"
  /HV124    "Education in single years - current school year"
  /HV125    "NA - Member attended school during previous school year"
  /HV126    "NA - Educational level during previous school year"
  /HV127    "NA - Grade of education during previous school year"
  /HV128    "NA - Education in single years - previous school year"
  /HV129    "NA - School attendance status"
  /HV140    "NA - Member has a birth certificate"
  /IDXH4    "Index to Household Schedule"
  /SHEDUC   "Highest education level attended"
  /SH16     "Ever attended school"
  /SH17A    "Highest education level attended"
  /SH17B    "Highest grade completed"
  /SH18     "Attended school during this school year"
  /SH19A    "Current level attended"
  /SH19B    "Current grade"
  /SH205    "Child status"
  /SH209H   "Time of measurement (hour)"
  /SH209M   "Time of measurement (minutes)"
  /SH215    "Hand used in sample (1)"
  /SH216    "Finger used in sample (1)"
  /SH217H   "Time of hemoglobin measurement (1) (hour)"
  /SH217M   "Time of hemoglobin measurement (1) (minutes)"
  /SH218    "Test repeated"
  /SH219    "Hemoglobin level 2 (g/dl - 1 decimal)"
  /SH220    "Hand used in sample (2)"
  /SH221    "Finger used in sample (2)"
  /SH222H   "Time of measurement (hour)"
  /SH222M   "Time of measurement (minutes)"
  /SHETID   "Ethnicity of child's mother by autoidentification"
  /SHETOB   "Ethnicity of child's mother by observation"
  /SH229    "Woman status"
  /SH232H   "Time of measurement (hour)"
  /SH232M   "Time of measurement (minutes)"
  /SH241    "Hand used in sample (1)"
  /SH242    "Finger used in sample (1)"
  /SH243H   "Time of hemoglobin measurement (hour)"
  /SH243M   "Time of hemoglobin measurement (minutes)"
  /SH244    "Test repeated"
  /SH245    "Hemoglobin level 2 (g/dl - 1 decimal)"
  /SH246    "Hand used in sample (2)"
  /SH247    "Finger used in sample (2)"
  /SH248H   "Time of measurement (hour)"
  /SH248M   "Time of measurement (minutes)"
  /SH250D   "Day of measurement"
  /SH250M   "Month of measurement"
  /SH250Y   "Year of measurement"
  /HA0      "Index to Household Schedule"
  /HA1      "Woman's age in years"
  /HA2      "Woman's weight in kilograms (1 decimal)"
  /HA3      "Woman's height in centimeters (1 decimal)"
  /HA4      "Height/Age percentile"
  /HA5      "Height/Age standard deviation"
  /HA6      "Height/Age percent ref. median"
  /HA11     "Weight/Height standard deviation (DHS)"
  /HA12     "Weight/Height percent ref. median (DHS)"
  /HA12A    "Weight/Height percent ref. median (Fog)"
  /HA12B    "Weight/Height percent ref. median (WHO)"
  /HA13     "Result of measurement - height/weight"
  /HA32     "Date of birth (CMC)"
  /HA33     "Completeness of HA32 information"
  /HA35     "Smoking (cigarettes in last 24 hours)"
  /HA40     "Body Mass Index"
  /HA41     "Rohrer's index"
  /HA50     "Under age 18"
  /HA51     "Line number of parent/caretaker"
  /HA52     "Read consent statement - hemoglobin"
  /HA53     "Hemoglobin level (g/dl - 1 decimal)"
  /HA54     "Currently pregnant"
  /HA55     "Result of measurement - hemoglobin"
  /HA56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /HA57     "Anemia level"
  /HA58     "NA - Agrees to referral - anemia"
  /HA60     "Marital status"
  /HA61     "NA - Read consent statement - HIV"
  /HA62     "NA - Bar code for HIV blood sample"
  /HA63     "NA - Result of measurement - HIV"
  /HA64     "NA - Consent for additional tests"
  /HA65     "Result of woman's individual interview"
  /HA66     "Woman's highest educational level"
  /HA67     "Woman's highest year of education"
  /HA68     "Woman's highest educational level (for preliminary and final report)"
  /HA69     "NA - HIV weight (6 decimals)"
  /HA70     "NA - Interviewer that took blood for HIV testing"
  /HC0      "Index to Household Schedule"
  /HC1      "Child's age in months"
  /HC2      "Child's weight in kilograms (1 decimal)"
  /HC3      "Child's height in centimeters (1 decimal)"
  /HC4      "Height/Age percentile"
  /HC5      "Height/Age standard deviation"
  /HC6      "Height/Age percent of ref. median"
  /HC7      "Weight/Age percentile"
  /HC8      "Weight/Age standard deviation"
  /HC9      "Weight/Age percent of ref. median"
  /HC10     "Weight/Height percentile"
  /HC11     "Weight/Height standard deviation"
  /HC12     "Weight/Height percent of ref. median"
  /HC13     "Result of measurement - height/weight"
  /HC15     "Height: lying or standing"
  /HC16     "Day of birth"
  /HC17     "Date measured (day)"
  /HC18     "Date measured (month)"
  /HC19     "Date measured (year)"
  /HC27     "Sex"
  /HC30     "Month of birth"
  /HC31     "Year of birth"
  /HC32     "Date of birth (CMC)"
  /HC33     "Completeness of HC32 information"
  /HC51     "Line number of parent/caretaker"
  /HC52     "Read consent statement - hemoglobin"
  /HC53     "Hemoglobin level (g/dl - 1 decimal)"
  /HC55     "Result of measurement - hemoglobin"
  /HC56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HC57     "Anemia level"
  /HC58     "NA - Agrees to referral - anemia"
  /HC60     "Mother's line number (woman's questionnaire)"
  /HC61     "Mother's highest educational level"
  /HC62     "Mother's highest year of education"
  /HC63     "Preceding birth interval (months)"
  /HC64     "Birth order number"
  /HC68     "Mother's highest educational level (for preliminary and final report)"
  /HC70     "Height/Age standard deviation (new WHO)"
  /HC71     "Weight/Age standard deviation (new WHO)"
  /HC72     "Weight/Height standard deviation (new WHO)"
  /HC73     "BMI standard deviation (new WHO)"
 .
MISSING VALUE
   HV017    (9)
  /HV018    (999)
  /HV026    (9)
  /HV030    (999)
  /HV040    (9999)
  /HV201    (99)
  /HV202    (99)
  /HV204    (999)
  /HV205    (99)
  /HV206    (9)
  /HV207    (9)
  /HV208    (9)
  /HV209    (9)
  /HV210    (9)
  /HV211    (9)
  /HV212    (9)
  /HV213    (99)
  /HV214    (99)
  /HV215    (99)
  /HV216    (99)
  /HV219    (9)
  /HV220    (99)
  /HV221    (9)
  /HV225    (9)
  /HV226    (99)
  /HV227    (9)
  /HV228    (9)
  /HV230A   (9)
  /HV230B   (9)
  /HV232    (9)
  /HV232B   (9)
  /HV232C   (9)
  /HV232D   (9)
  /HV232E   (9)
  /HV232Y   (9)
  /HV234    (999)
  /HV234A   (9)
  /HV235    (9)
  /HV236    (9)
  /HV237    (9)
  /HV237A   (9)
  /HV237B   (9)
  /HV237C   (9)
  /HV237D   (9)
  /HV237E   (9)
  /HV237F   (9)
  /HV237G   (9)
  /HV237H   (9)
  /HV237I   (9)
  /HV237J   (9)
  /HV237K   (9)
  /HV237X   (9)
  /HV237Z   (9)
  /HV238    (99)
  /HV239    (9)
  /HV240    (9)
  /HV241    (9)
  /HV242    (9)
  /HV243A   (9)
  /HV243B   (9)
  /HV243C   (9)
  /HV243D   (9)
  /HV244    (9)
  /HV245    (999)
  /HV246    (9)
  /HV246A   (99)
  /HV246B   (99)
  /HV246C   (99)
  /HV246D   (99)
  /HV246E   (99)
  /HV246F   (99)
  /HV246G   (99)
  /HV246H   (99)
  /HV246I   (99)
  /HV246J   (99)
  /HV246K   (99)
  /HV247    (9)
  /HV252    (9)
  /HV253    (9)
  /HV253A   (9)
  /HV253B   (9)
  /HV253C   (9)
  /HV253D   (9)
  /HV253E   (9)
  /HV253F   (9)
  /HV253G   (9)
  /HV253H   (9)
  /HV253X   (9)
  /HV253Z   (9)
  /HML1     (99)
  /HML2     (99)
  /SHSTARTH (99)
  /SHSTARTM (99)
  /SHILANG  (99)
  /SHQLANG  (99)
  /SH109B   (9)
  /SH109H   (9)
  /SH109I   (9)
  /SH109J   (9)
  /SH109K   (9)
  /SH109L   (9)
  /SH119N   (999)
  /SH123    (9)
  /SH124    (9)
  /SH125    (9)
  /SH126    (9)
  /SH127    (9)
  /SH128    (9)
  /SH132H   (99)
  /SH132M   (99)
  /SH200H   (99)
  /SH200M   (99)
  /SH252A   (999)
  /SH252B   (999)
  /SH253A   (66)
  /SH253B   (66)
  /SH253C   (66)
  /SH254H   (99)
  /SH254M   (99)
  /HV101    (99)
  /HV102    (9)
  /HV103    (9)
  /HV104    (9)
  /HV105    (99)
  /HV106    (9)
  /HV107    (99)
  /HV108    (99)
  /HV109    (9)
  /HV110    (9)
  /HV111    (9)
  /HV112    (99)
  /HV113    (9)
  /HV114    (99)
  /HV115    (9)
  /HV116    (9)
  /HV121    (9)
  /HV122    (9)
  /HV123    (99)
  /HV124    (99)
  /HV125    (9)
  /HV126    (9)
  /HV127    (99)
  /HV128    (99)
  /HV129    (9)
  /HV140    (9)
  /SHEDUC   (9)
  /SH16     (9)
  /SH17A    (9)
  /SH17B    (99)
  /SH18     (9)
  /SH19A    (9)
  /SH19B    (99)
  /SH205    (9)
  /SH209H   (99)
  /SH209M   (99)
  /SH215    (9)
  /SH216    (9)
  /SH217H   (99)
  /SH217M   (99)
  /SH218    (9)
  /SH219    (999)
  /SH220    (9)
  /SH221    (9)
  /SH222H   (99)
  /SH222M   (99)
  /SHETID   (9)
  /SHETOB   (9)
  /SH229    (9)
  /SH232H   (99)
  /SH232M   (99)
  /SH241    (9)
  /SH242    (9)
  /SH243H   (99)
  /SH243M   (99)
  /SH244    (9)
  /SH245    (999)
  /SH246    (9)
  /SH247    (9)
  /SH248H   (99)
  /SH248M   (99)
  /SH250D   (99)
  /SH250M   (99)
  /SH250Y   (9999)
  /HA2      (9999)
  /HA3      (9999)
  /HA4      (9999)
  /HA5      (9999)
  /HA6      (99999)
  /HA11     (9999)
  /HA12     (99999)
  /HA12A    (99999)
  /HA12B    (99999)
  /HA13     (9)
  /HA35     (99)
  /HA40     (9999)
  /HA41     (9999)
  /HA50     (9)
  /HA51     (99)
  /HA52     (9)
  /HA53     (999)
  /HA54     (9)
  /HA55     (9)
  /HA56     (999)
  /HA57     (9)
  /HA58     (9)
  /HA60     (9)
  /HA61     (9)
  /HA63     (9)
  /HA64     (9)
  /HA66     (9)
  /HA67     (99)
  /HA68     (9)
  /HA70     (999)
  /HC2      (9999)
  /HC3      (9999)
  /HC4      (9999)
  /HC5      (9999)
  /HC6      (99999)
  /HC7      (9999)
  /HC8      (9999)
  /HC9      (99999)
  /HC10     (9999)
  /HC11     (9999)
  /HC12     (99999)
  /HC13     (9)
  /HC15     (9)
  /HC16     (99)
  /HC27     (9)
  /HC30     (99)
  /HC31     (9999)
  /HC51     (99)
  /HC52     (9)
  /HC53     (999)
  /HC55     (9)
  /HC56     (999)
  /HC57     (9)
  /HC58     (9)
  /HC60     (999)
  /HC61     (9)
  /HC62     (99)
  /HC63     (999)
  /HC64     (99)
  /HC68     (9)
  /HC70     (9999)
  /HC71     (9999)
  /HC72     (9999)
  /HC73     (9999)
 .
VALUE LABELS
   HV003   
      0 "Incomplete household"
  /HV015   
      1 "Completed"
      2 "No Household member/no competent member at home"
      3 "Entire Household absent for extended period of time"
      4 "Postponed"
      5 "Refused"
      6 "Dwelling vacant or address not a dwelling"
      7 "Dwelling destroyed"
      8 "Dwelling not found"
      9 "Other"
  /HV020   
      0 "All woman sample"
      1 "Ever married sample"
  /HV024   
      1 "Metropolitana"
      2 "Norte"
      3 "Nororiente"
      4 "Suroriente"
      5 "Central"
      6 "Suroccidente"
      7 "Noroccidente"
      8 "Petén"
  /HV025   
      1 "Urban"
      2 "Rural"
  /HV026   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /HV027   
      0 "Not selected"
      1 "Men's survey"
      2 "Husband's survey"
  /HV042   
      0 "Not selected"
      1 "Selected"
  /HV044   
      0 "Household not selected"
      1 "Household selected"
  /HV201   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     14 "Other piped"
     20 "TUBE WELL WATER"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Public fountain/tank"
     32 "Mechanical or manual well"
     40 "SURFACE WATER"
     41 "River/irrigation channel"
     42 "Lake or stream"
     43 "Protected spring"
     44 "Unprotected spring"
     51 "Rainwater"
     61 "Tanker truck"
     71 "Bottled water"
     96 "Other"
  /HV202   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     96 "Other"
  /HV204   
    996 "On premises"
    998 "Don't know"
  /HV205   
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to somewhere else"
     14 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Latrine"
     23 "Open latrine"
     30 "NO FACILITY"
     31 "No facility"
     96 "Other"
  /HV206   
      0 "No"
      1 "Yes"
  /HV207   
      0 "No"
      1 "Yes"
  /HV208   
      0 "No"
      1 "Yes"
  /HV209   
      0 "No"
      1 "Yes"
  /HV210   
      0 "No"
      1 "Yes"
  /HV211   
      0 "No"
      1 "Yes"
  /HV212   
      0 "No"
      1 "Yes"
  /HV213   
     10 "NATURAL"
     11 "Dirt/sand"
     20 "RUDIMENTARY"
     21 "Wood planks"
     22 "Palm/bamboo"
     23 "Mud stones"
     30 "FINISHED"
     31 "Polished wood"
     32 "Vinyl or asphalt strips"
     33 "Cement tiles (mosaic)"
     34 "Ceramic tiles"
     35 "Cement"
     96 "Other"
  /HV214   
     10 "NATURAL"
     11 "No walls"
     12 "Cane, palm tree, trunks"
     13 "Mud"
     20 "RUDIMENTARY"
     21 "Palm, bamboo"
     22 "Interwoven sticks or reeds and mud ('Bajareque')"
     23 "Sheet"
     24 "Adobe"
     25 "Wood planks"
     26 "Waste material"
     30 "FINISHED"
     31 "Cement"
     32 "Stone with lime/cement"
     33 "Bricks"
     34 "Cement block"
     35 "Covered adobe"
     96 "Other"
  /HV215   
     10 "NATURAL"
     11 "No walls"
     12 "Straw, palm"
     20 "RUDIMENTARY"
     21 "Rustic mat"
     23 "Wood panel"
     24 "Cardboard"
     30 "FINISHED"
     31 "Tile (Mud/ceramic/concrete)"
     32 "Slab"
     33 "Metal"
     34 "Cement fiber"
     96 "Other"
  /HV217   
      0 "No adults"
      1 "One adult"
      2 "Two adults, opposite sex"
      3 "Two adults, same sex"
      4 "Three+ related adults"
      5 "Unrelated adults"
  /HV219   
      1 "Male"
      2 "Female"
  /HV220   
     95 "95+"
     98 "Don't know"
  /HV221   
      0 "No"
      1 "Yes"
  /HV225   
      0 "No"
      1 "Yes"
  /HV226   
      1 "Electricity"
      2 "LPG"
      3 "Natural gas/Biogas"
      4 "Biogas"
      5 "Kerosene"
      6 "Coal, lignite"
      7 "Charcoal"
      8 "Wood"
      9 "Straw/shrubs/grass"
     10 "Agricultural crop"
     11 "Animal dung"
     95 "No food cooked in house"
     96 "Other"
  /HV227   
      0 "No"
      1 "Yes"
  /HV228   
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /HV230A  
      1 "Observed"
      2 "Not observed: not in dwelling"
      3 "Not observed: no permission to see"
      4 "Not observed: other reason"
  /HV230B  
      0 "Water not available"
      1 "Water is available"
  /HV232   
      0 "No"
      1 "Yes"
  /HV232B  
      0 "No"
      1 "Yes"
  /HV232C  
      0 "No"
      1 "Yes"
  /HV232D  
      0 "No"
      1 "Yes"
  /HV232E  
      0 "No"
      1 "Yes"
  /HV232Y  
      0 "No"
      1 "Yes: no cleansing agent observed"
  /HV234   
      0 "0 PPM (no iodine)"
      7 "Below 15 PPM"
     15 "15 PPM and above"
     30 "30 PPM"
    994 "Salt not tested"
    995 "No salt in household"
  /HV234A  
      0 "No iodine"
      1 "Iodine present"
      3 "No salt in household"
      6 "Salt not tested"
  /HV235   
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /HV236   
      1 "Adult woman"
      2 "Adult man"
      3 "Female child under 15 years old"
      4 "Male child under 15 years old"
      6 "Other"
  /HV237   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237I  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237J  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237K  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237Z  
      0 "No"
      1 "Yes: don't know what is done to water"
      8 "Don't know"
  /HV238   
     95 "10 or more households"
     98 "Don't know"
  /HV239   
      1 "Open fire"
      2 "Open stove"
      3 "Closed stove with chimney"
      6 "Other"
  /HV240   
      0 "Neither chimney or hood"
      1 "Chimney"
      2 "Hood"
  /HV241   
      1 "In the house"
      2 "In a separate building"
      3 "Outdoors"
      6 "Other"
  /HV242   
      0 "No"
      1 "Yes"
  /HV243A  
      0 "No"
      1 "Yes"
  /HV243B  
      0 "No"
      1 "Yes"
  /HV243C  
      0 "No"
      1 "Yes"
  /HV243D  
      0 "No"
      1 "Yes"
  /HV244   
      0 "No"
      1 "Yes"
      8 "Don't know/don't respond"
  /HV245   
    373 "37 or more"
    998 "Unknown"
  /HV246   
      0 "No"
      1 "Yes"
  /HV246A  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246B  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246C  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246D  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246E  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246F  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246G  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246H  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246I  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246J  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246K  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV247   
      0 "No"
      1 "Yes"
  /HV252   
      0 "Never"
      1 "Daily"
      2 "Weekly"
      3 "Monthly"
      4 "Less than monthly"
  /HV253   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253Z  
      0 "No"
      1 "Yes: don't know who sprayed the dwelling"
      8 "Don't know if it was sprayed"
  /HV270   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /HML1    
     98 "Don't know"
  /SHDEPTO 
      1 "Guatemala"
      2 "El Progreso"
      3 "Sacatepéquez"
      4 "Chimaltenango"
      5 "Escuintla"
      6 "Santa Rosa"
      7 "Sololá"
      8 "Totonicapán"
      9 "Quetzaltenango"
     10 "Suchitepéquez"
     11 "Retalhuleu"
     12 "San Marcos"
     13 "Huehuetenango"
     14 "Quiché"
     15 "Baja Verapaz"
     16 "Alta Verapaz"
     17 "Petén"
     18 "Izabal"
     19 "Zacapa"
     20 "Chiquimula"
     21 "Jalapa"
     22 "Jutiapa"
  /SHDEPTO2
      1 "Guatemala municipio"
      2 "Guatemala resto"
      3 "El Progreso"
      4 "Sacatepéquez"
      5 "Chimaltenango"
      6 "Escuintla"
      7 "Santa Rosa"
      8 "Sololá"
      9 "Totonicapán"
     10 "Quetzaltenango"
     11 "Suchitepéquez"
     12 "Retalhuleu"
     13 "San Marcos"
     14 "Huehuetenango"
     15 "Quiché"
     16 "Baja Verapaz"
     17 "Alta Verapaz"
     18 "Petén"
     19 "Izabal"
     20 "Zacapa"
     21 "Chiquimula"
     22 "Jalapa"
     23 "Jutiapa"
  /SHSTARTH
     97 "Inconsistent"
  /SHSTARTM
     97 "Inconsistent"
  /SHILANG 
      1 "Spanish"
      2 "Kaqchiquel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
     96 "Other"
  /SHQLANG 
      1 "Spanish"
      2 "Kaqchiquel"
      3 "Q'eqchi'"
      4 "K'iche'"
      5 "Mam"
      6 "Poqomchi'"
      7 "Tzu'utujil"
      8 "Q'anjob'al"
      9 "Ch'orti'"
     10 "Poqomam"
  /SHTRANS 
      0 "No"
      1 "Yes"
  /SH109B  
      0 "No"
      1 "Yes"
  /SH109H  
      0 "No"
      1 "Yes"
  /SH109I  
      0 "No"
      1 "Yes"
  /SH109J  
      0 "No"
      1 "Yes"
  /SH109K  
      0 "No"
      1 "Yes"
  /SH109L  
      0 "No"
      1 "Yes"
  /SH119U  
      1 "Rope ('Cuerdas')"
      2 "Yard"
      9 "Special answers"
  /SH119N  
    995 "95 or more"
    998 "DK"
  /SH123   
      0 "No"
      1 "Sí"
      8 "DK/not sure"
  /SH124   
      1 "Few times (1 or 2 times)"
      2 "Sometimes (3 to 10 times)"
      3 "Often (more than 10 times)"
  /SH125   
      0 "No"
      1 "Yes"
      8 "Dk/not sure"
  /SH126   
      1 "Few times (1 or 2 times)"
      2 "Sometimes (3 to 10 times)"
      3 "Often (more than 10 times)"
  /SH127   
      0 "No"
      1 "Yes"
      8 "DK/not sure"
  /SH128   
      1 "Few times (1 or 2 times)"
      2 "Sometimes (3 to 10 times)"
      3 "Often (more than 10 times)"
  /HV101   
      1 "Head"
      2 "Wife or husband"
      3 "Son/daughter"
      4 "Son/daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother/sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     13 "Niece/nephew by blood"
     14 "Niece/nephew by marriage"
     15 "Grand parents"
     98 "Don't know"
  /HV102   
      0 "No"
      1 "Yes"
  /HV103   
      0 "No"
      1 "Yes"
  /HV104   
      1 "Male"
      2 "Female"
  /HV105   
     95 "95+"
     98 "Don't know"
  /HV106   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV107   
     98 "Don't know"
  /HV108   
     97 "Inconsistent"
     98 "Don't know"
  /HV109   
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
  /HV110   
      0 "No"
      1 "Yes"
  /HV111   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV112   
      0 "Mother not in household"
  /HV113   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV114   
      0 "Father not in household"
  /HV115   
      0 "Never married"
      1 "Married"
      2 "Living together"
      3 "Widowed"
      4 "Divorced"
      5 "Not living together"
  /HV116   
      0 "Never married"
      1 "Currently married"
      2 "Formerly/ever married"
  /HV117   
      0 "Not eligible"
      1 "Eligible"
  /HV118   
      0 "Not eligible"
      1 "Eligible"
  /HV120   
      0 "Not eligible"
      1 "Eligible"
  /HV121   
      0 "No"
      1 "Currently attending"
      2 "Attended at some time"
  /HV122   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV123   
     98 "Don't know"
  /HV124   
     97 "Inconsistent"
     98 "Don't know"
  /HV125   
      0 "No"
      1 "Yes"
  /HV126   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV127   
     98 "Don't know"
  /HV128   
     97 "Inconsistent"
     98 "Don't know"
  /HV129   
      0 "Never attended"
      1 "Entered school"
      2 "Advanced"
      3 "Repeating"
      4 "Dropout"
      5 "Left school 2+ years ago"
      8 "Don't know"
  /HV140   
      0 "Neither certificate or registered"
      1 "Has certificate"
      2 "Registered"
      8 "Don't know"
  /SHEDUC  
      0 "No education/pre-primary"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      6 "Alphabetization"
      8 "Don't know"
  /SH16    
      0 "No"
      1 "Yes"
  /SH17A   
      1 "Pre-primary"
      2 "Primary"
      3 "Secondary"
      4 "Higher/university"
      5 "Alphabetization"
      8 "DK"
  /SH17B   
      0 "< 1 year completed"
     98 "DK"
  /SH18    
      0 "No"
      1 "Yes"
  /SH19A   
      1 "Pre-primary"
      2 "Primary"
      3 "Secondary"
      4 "Higher/university"
      5 "Alphabetization"
      8 "DK"
  /SH19B   
     98 "DK"
  /SH205   
      1 "Measured"
      2 "Sick"
      3 "Not present"
      4 "Child refuse"
      5 "Mother refuse"
      6 "Other"
  /SH215   
      1 "Right"
      2 "Left"
  /SH216   
      1 "Thumb"
      2 "Index"
      3 "Middle"
      4 "Ring"
      5 "Little"
  /SH218   
      0 "No"
      1 "Yes, repeated"
  /SH219   
    994 "Not present/other"
    995 "Refused"
  /SH220   
      1 "Right"
      2 "Left"
  /SH221   
      1 "Thumb"
      2 "Index"
      3 "Middle"
      4 "Ring"
      5 "Little"
  /SHETID  
      0 "Not indian"
      1 "Indian"
      4 "Mother is not de facto"
      5 "Incomplete interview"
      6 "Mother not at home"
      7 "Undetermined ethnicity"
  /SHETOB  
      0 "Not indian"
      1 "Indian"
      4 "Mother is not de facto"
      5 "Incomplete interview"
      6 "Mother not at home"
      7 "Undetermined ethnicity"
  /SH229   
      1 "Measured"
      2 "Sick"
      3 "Not present"
      4 "Refuse"
      5 "Pregnant"
      6 "Other"
  /SH241   
      1 "Right"
      2 "Left"
  /SH242   
      1 "Thumb"
      2 "Index"
      3 "Middle"
      4 "Ring"
      5 "Little"
  /SH244   
      0 "No"
      1 "Yes, repeated"
  /SH245   
    994 "Not present"
    995 "Refused"
  /SH246   
      1 "Right"
      2 "Left"
  /SH247   
      1 "Thumb"
      2 "Index"
      3 "Middle"
      4 "Ring"
      5 "Little"
  /HA2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HA3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HA4     
   9998 "Flagged cases"
  /HA5     
   9998 "Flagged cases"
  /HA6     
   99998 "Flagged cases"
  /HA11    
   9998 "Flagged cases"
  /HA12    
   99998 "Flagged cases"
  /HA12A   
   99998 "Flagged cases"
  /HA12B   
   99998 "Flagged cases"
  /HA13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "Pregnant"
      8 "Sick"
  /HA33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HA35    
      0 "Doesn't smoke"
     80 "80+"
     94 "Smokes pipes, cigars, etc"
  /HA40    
   9998 "Flagged cases"
  /HA41    
   9998 "Flagged cases"
  /HA50    
      1 "Under age 18"
      2 "Age 18 or older"
  /HA51    
      0 "Not in household"
  /HA52    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Adult/parent not present"
      5 "Minor not present"
  /HA53    
    994 "Not present/other"
    995 "Refused"
  /HA54    
      0 "No/don't know"
      1 "Yes"
  /HA55    
      0 "Measured"
      3 "Not present/other"
      4 "Refused"
  /HA56    
    997 "Inconsistent"
  /HA57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HA58    
      0 "No"
      1 "Yes"
  /HA60    
      1 "Never in union"
      2 "Other"
  /HA61    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /HA62    
   99992 "Woman's interview incomplete or woman is not de-facto"
   99993 "Sample damaged/insufficient/not found in lab"
   99994 "Not present"
   99995 "Refused"
   99996 "Other"
   '?    ' "Missing"
  /HA63    
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /HA64    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HA65    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /HA66    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HA67    
     98 "Don't know"
  /HA68    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Secondary"
      4 "Higher"
      8 "Don't know"
  /HC2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HC3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HC4     
   9998 "Flagged cases"
  /HC5     
   9998 "Flagged cases"
  /HC6     
   99998 "Flagged cases"
  /HC7     
   9998 "Flagged cases"
  /HC8     
   9998 "Flagged cases"
  /HC9     
   99998 "Flagged cases"
  /HC10    
   9998 "Flagged cases"
  /HC11    
   9998 "Flagged cases"
  /HC12    
   99998 "Flagged cases"
  /HC13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HC15    
      0 "Not measured"
      1 "Lying"
      2 "Standing"
  /HC16    
     97 "Inconsistent"
     98 "Don't know"
  /HC27    
      1 "Male"
      2 "Female"
  /HC30    
     97 "Inconsistent"
     98 "Don't know"
  /HC31    
   9997 "Inconsistent"
   9998 "Don't know"
  /HC33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HC51    
      0 "Not in household"
  /HC52    
      1 "Granted"
      2 "Refused"
      3 "Not present/other"
  /HC53    
    994 "Not present/other"
    995 "Refused"
  /HC55    
      0 "Measured"
      3 "Not present/other"
      4 "Refused"
  /HC56    
    997 "Inconsistent"
  /HC57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HC58    
      0 "No"
      1 "Yes"
  /HC60    
    993 "Mother not de facto"
    994 "Incomplete woman's interview"
    995 "Not in household"
  /HC61    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HC62    
     98 "Don't know"
  /HC68    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Secondary"
      4 "Higher"
      8 "Don't know"
  /HC70    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC71    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC72    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC73    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\GU71\GUPR71FL.sav'.
