infix using "C:\COUNTRIES\CO72\COPR72FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "NA - Number of eligible children for height and weight"
label variable hv040    "NA - Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "NA - Household selected for hemoglobin"
label variable hv044    "Household selected for Domestic Violence module"
label variable hv045a   "NA - Language of questionnaire"
label variable hv045b   "NA - Language of interview"
label variable hv045c   "NA - Native language of respondent"
label variable hv046    "NA - Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "NA - Number of visits for biomarker"
label variable hv807d   "NA - Day of biomarker visit"
label variable hv807m   "NA - Month of biomarker visit"
label variable hv807y   "NA - Year of biomarker visit"
label variable hv807c   "NA - Date of biomarker (CMC)"
label variable hv807a   "NA - Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "NA - Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Has mosquito bed net for sleeping"
label variable hv228    "NA - Children under 5 slept under mosquito bed net last night"
label variable hv230a   "NA - Place where household members wash their hands"
label variable hv230b   "NA - Presence of water at hand washing place"
label variable hv232    "NA - Items present: Soap or detergent"
label variable hv232b   "NA - Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "NA - Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "NA - Result of salt test for iodine"
label variable hv235    "NA - Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "NA - Anything done to water to make safe to drink"
label variable hv237a   "NA - Water usually treated by: boil"
label variable hv237b   "NA - Water usually treated by: add bleach/chlorine"
label variable hv237c   "NA - Water usually treated by: strain through a cloth"
label variable hv237d   "NA - Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "NA - Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "NA - Water usually treated by: other"
label variable hv237z   "NA - Water usually treated by: don't know"
label variable hv238    "NA - Number of households sharing toilet"
label variable hv238a   "NA - Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "NA - Food cooked in the house/ separate building/ outdoors"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "NA - Has watch"
label variable hv243c   "NA - Has animal-drawn cart"
label variable hv243d   "NA - Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "NA - Owns land usable for agriculture"
label variable hv245    "NA - Hectares of agricultural land (1 decimal)"
label variable hv246    "NA - Owns livestock, herds or farm animals"
label variable hv246a   "NA - Owns cattle"
label variable hv246b   "NA - Owns cows/ bulls"
label variable hv246c   "NA - Owns horses/ donkeys/ mules"
label variable hv246d   "NA - Owns goats"
label variable hv246e   "NA - Owns sheep"
label variable hv246f   "NA - Owns chickens/poultry"
label variable hv246g   "NA - Owns CS"
label variable hv246h   "NA - Owns CS"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "NA - Has bank account"
label variable hv252    "NA - Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "NA - Number of mosquito bed nets"
label variable hml1a    "NA - Number of mosquito bed nets with specific information"
label variable hml2     "NA - Number of children under mosquito bed net previous night"
label variable shdepto  "Department"
label variable shmunip  "Municipality"
label variable sharea   "Area"
label variable shaream  "Area Ministry of health"
label variable shsubreg "Subregions"
label variable sh63     "Type of family"
label variable sh64     "Number of HH members deceased last year"
label variable sh68ab   "Socio-economic strata"
label variable sh68b    "Access to natural gas"
label variable sh68c    "Access to piped water"
label variable sh68d    "Access to sewer"
label variable sh68e    "Access to garbage collection"
label variable sh71     "Water for drinking from same source"
label variable sh74     "Number of toilets"
label variable sh75     "Is toilet shared with other households"
label variable sh76     "Location of toilet"
label variable sh77     "Has shower"
label variable sh79f    "Has a washing machine"
label variable sh79g    "Has a microwave oven"
label variable sh79l    "Has internet access"
label variable sh80     "Share telephone line"
label variable sh81     "How is garbage disposed"
label variable sh85     "Dwelling type"
label variable sh86     "Ownership of dwelling unit"
label variable sh87     "Number of HH members hospitalized last year"
label variable sh94     "Any household member lives abroad"
label variable sh94a    "Sons living abroad"
label variable sh94b    "Daughters living abroad"
label variable sh94c    "Partner living abroad"
label variable sh94d    "Father living abroad"
label variable sh94e    "Mother living abroad"
label variable sh94f    "Brothers/sisters living abroad"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level attained"
label variable hv107    "Highest year of education completed"
label variable hv108    "Education completed in single years"
label variable hv109    "Educational attainment"
label variable hv110    "Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never married"
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "Member attended school during previous school year"
label variable hv126    "Educational level during previous school year"
label variable hv127    "Grade of education during previous school year"
label variable hv128    "Education in single years - previous school year"
label variable hv129    "School attendance status"
label variable hv140    "Member has a birth certificate"
label variable idxh4    "Index to household schedule"
label variable sh09     "Ethnicity"
label variable sh12     "Where mother lives"
label variable sh13     "Place where mother lives"
label variable sh14     "Have ever had children (women 50+)"
label variable sh15aa   "Daughters living in country"
label variable sh15ab   "Sons living in country"
label variable sh15ba   "Daughters living abroad"
label variable sh15bb   "Sons living abroad"
label variable sh15ca   "Daughters deceased"
label variable sh15cb   "Sons deceased"
label variable sh16aa   "Daughters living in Venezuela"
label variable sh16ab   "Sons living in Venezuela"
label variable sh16ba   "Daughters living in United States"
label variable sh16bb   "Sons living in United States"
label variable sh16ca   "Daughters living in Spain"
label variable sh16cb   "Sons living in Spain"
label variable sh16da   "Daughters living in Ecuador"
label variable sh16db   "Sons living in Ecuador"
label variable sh16ea   "Daughters living in Panama"
label variable sh16eb   "Sons living in Panama"
label variable sh16fa   "Daughters living in Canada"
label variable sh16fb   "Sons living in Canada"
label variable sh16ga   "Daughters living in other country"
label variable sh16gb   "Sons living in other country"
label variable sh20     "Place where child was registered"
label variable sh21     "Reason child wasn't registered"
label variable sh22     "Places lived since January 2010"
label variable sh23m    "Month came to live place of interview"
label variable sh23y    "Year came to live place of interview"
label variable sh24     "Place lived before came to place of interview"
label variable sh25     "Type of place of previous residence"
label variable sh26     "Reason left previous place of residence"
label variable sh27     "Number of family members migrated with HH member"
label variable sh28a    "Did HH member came with: partner"
label variable sh28b    "Did HH member came with: children"
label variable sh28c    "Did HH member came with: parents/in-laws"
label variable sh28d    "Did HH member came with: brothers/sisters"
label variable sh28x    "Did HH member came with: others"
label variable sh28     "Place where HH member lived five years ago"
label variable sh30     "Spouse's line number"
label variable sh31     "Occupation last week"
label variable sh32     "Member of and ARL"
label variable sh33     "Has any income (work, rent, subsidies, transferences, in kind, etc)"
label variable sh34     "Contributes to a retirement plan"
label variable sh35     "Ever attended a day care for little children"
label variable sh36     "Institution child currently attend"
label variable sh37     "Reason quit attending institution"
label variable sh38     "Reason not attending any institution"
label variable sh39     "Member knows how to read and write"
label variable sh41a    "Level of school completed"
label variable sh41b    "Grade of school completed"
label variable sh44a    "Current level of school attending"
label variable sh44b    "Current grade of school attending"
label variable sh46a    "Level of school attended previous year"
label variable sh46b    "Grade of school attended previous year"
label variable sh47     "Reason never attended or not currently attending school"
label variable sh48     "Occupation last week"
label variable sh49     "Last week helped with housework"
label variable sh50     "Member of a health security system"
label variable sh51     "Autoevaluation of own health"
label variable sh52     "Have visited a doctor last year"
label variable sh53a    "Has difficulty to: hear voice or sounds"
label variable sh53b    "Has difficulty to: talk, communicate"
label variable sh53c    "Has difficulty to: see close, far, around"
label variable sh53d    "Has difficulty to: move around/walk/climb stairs"
label variable sh53e    "Has difficulty to: hold, use arms/hands"
label variable sh53f    "Has difficulty to: understand, remember, take decisions"
label variable sh53g    "Has difficulty to: eat, put on clothes, take shower"
label variable sh53h    "Has difficulty to: relate/interact with others"
label variable sh53i    "Has difficulty to: do daily chores with no cardio/respiratory conditions"
label variable sh54     "Difficulty that affects the most"
label variable sh55     "Origin of difficulty that most affect HH member"
label variable sh56a    "For difficulty permanently use: technical devices"
label variable sh56b    "For difficulty permanently use: medicine, therapies"
label variable sh56c    "For difficulty permanently use: help from others"
label variable sh56x    "For difficulty permanently use: others"
label variable sh57a    "Person who helps HH member: father"
label variable sh57b    "Person who helps HH member: mother"
label variable sh57c    "Person who helps HH member: sons"
label variable sh57d    "Person who helps HH member: daughters"
label variable sh57e    "Person who helps HH member: brothers"
label variable sh57f    "Person who helps HH member: sisters"
label variable sh57g    "Person who helps HH member: partner"
label variable sh57h    "Person who helps HH member: grand-father"
label variable sh57i    "Person who helps HH member: grand-mother"
label variable sh57j    "Person who helps HH member: other male relatives"
label variable sh57k    "Person who helps HH member: other female relatives"
label variable sh57l    "Person who helps HH member: non relative not paid"
label variable sh57m    "Person who helps HH member: non relative paid not qualified"
label variable sh57n    "Person who helps HH member: paid qualified individual"
label variable sh57o    "Person who helps HH member: need help but don't have anyone"
label variable sh58a    "Problem with health service: no equipment and instruments"
label variable sh58b    "Problem with health service: rehabilitation not available"
label variable sh58c    "Problem with health service: health personnel not available"
label variable sh58d    "Problem with health service: place not handicap compliant"
label variable sh58e    "Problem with health service: far away"
label variable sh58f    "Problem with health service: transportation is difficult"
label variable sh58g    "Problem with health service: service denied"
label variable sh58h    "Problem with health service: lack of information on documents needed"
label variable sh58i    "Problem with health service: too many requirements"
label variable sh58j    "Problem with health service: cost too much"
label variable sh58k    "Problem with health service: difficult to obtain medicine or devices"
label variable sh58l    "Problem with health service: difficult to get appointments/authorizations or rem"
label variable sh58m    "Problem with health service: haven't been to a consultation/consult with private"
label variable sh58x    "Problem with health service: other"
label variable sh58y    "Problem with health service: no difficulty at all"
label variable sh60     "Eligibility for cytology questionnaire (women 50-69 years old)"
label variable sh62     "Eligibility for the aging questionnaire (60+ years old)"
label variable shperwgt "Weight for household members (6 decimals)"
label variable ha0      "NA - Index to Household Schedule"
label variable ha1      "NA - Woman's age in years"
label variable ha2      "NA - Woman's weight in kilograms (1 decimal)"
label variable ha3      "NA - Woman's height in centimeters (1 decimal)"
label variable ha4      "NA - Height/Age percentile"
label variable ha5      "NA - Height/Age standard deviation"
label variable ha6      "NA - Height/Age percent ref. median"
label variable ha11     "NA - Weight/Height standard deviation (DHS)"
label variable ha12     "NA - Weight/Height percent ref. median (DHS)"
label variable ha12a    "NA - Weight/Height percent ref. median (Fog)"
label variable ha12b    "NA - Weight/Height percent ref. median (WHO)"
label variable ha13     "NA - Result of measurement - height/weight"
label variable ha21     "NA - Fieldworker measurer code"
label variable ha32     "NA - Date of birth (CMC)"
label variable ha33     "NA - Completeness of HA32 information"
label variable ha35     "NA - Smoking (cigarettes in last 24 hours)"
label variable ha40     "NA - Body Mass Index"
label variable ha41     "NA - Rohrer's index"
label variable ha50     "NA - Under age 18"
label variable ha51     "NA - Line number of parent/caretaker"
label variable ha52     "NA - Read consent statement - hemoglobin"
label variable ha53     "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "NA - Currently pregnant"
label variable ha55     "NA - Result of measurement - hemoglobin"
label variable ha56     "NA - Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57     "NA - Anemia level"
label variable ha58     "NA - Agrees to referral - anemia"
label variable ha60     "NA - Marital status"
label variable ha61     "NA - Read consent statement - HIV"
label variable ha62     "NA - Bar code for HIV blood sample"
label variable ha63     "NA - Result of measurement - HIV"
label variable ha64     "NA - Consent for additional tests"
label variable ha65     "NA - Result of woman's individual interview"
label variable ha66     "NA - Woman's highest educational level"
label variable ha67     "NA - Woman's highest year of education"
label variable ha68     "NA - Woman's highest educational level (for preliminary and final report)"
label variable ha69     "NA - HIV weight (6 decimals)"
label variable ha70     "NA - Interviewer that took blood for HIV testing"
label variable hc0      "NA - Index to Household Schedule"
label variable hc1      "NA - Child's age in months"
label variable hc1a     "NA - Child's age in days"
label variable hc2      "NA - Child's weight in kilograms (1 decimal)"
label variable hc3      "NA - Child's height in centimeters (1 decimal)"
label variable hc4      "NA - Height/Age percentile"
label variable hc5      "NA - Height/Age standard deviation"
label variable hc6      "NA - Height/Age percent of ref. median"
label variable hc7      "NA - Weight/Age percentile"
label variable hc8      "NA - Weight/Age standard deviation"
label variable hc9      "NA - Weight/Age percent of ref. median"
label variable hc10     "NA - Weight/Height percentile"
label variable hc11     "NA - Weight/Height standard deviation"
label variable hc12     "NA - Weight/Height percent of ref. median"
label variable hc13     "NA - Result of measurement - height/weight"
label variable hc15     "NA - Height: lying or standing"
label variable hc16     "NA - Day of birth"
label variable hc17     "NA - Date measured (day)"
label variable hc18     "NA - Date measured (month)"
label variable hc19     "NA - Date measured (year)"
label variable hc20     "NA - Century Day Code (CDC) of measurement"
label variable hc21     "NA - Fieldworker measurer code"
label variable hc27     "NA - Sex"
label variable hc30     "NA - Month of birth"
label variable hc31     "NA - Year of birth"
label variable hc32     "NA - Date of birth (CMC)"
label variable hc32a    "NA - Century Day Code (CDC) of birth"
label variable hc33     "NA - Completeness of HC32 information"
label variable hc51     "NA - Line number of parent/caretaker"
label variable hc52     "NA - Read consent statement - hemoglobin"
label variable hc53     "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "NA - Result of measurement - hemoglobin"
label variable hc56     "NA - Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "NA - Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "NA - Mother's line number (woman's questionnaire)"
label variable hc61     "NA - Mother's highest educational level"
label variable hc62     "NA - Mother's highest year of education"
label variable hc63     "NA - Preceding birth interval (months)"
label variable hc64     "NA - Birth order number"
label variable hc68     "NA - Mother's highest educational level (for preliminary and final report)"
label variable hc70     "NA - Height/Age standard deviation (new WHO)"
label variable hc71     "NA - Weight/Age standard deviation (new WHO)"
label variable hc72     "NA - Weight/Height standard deviation (new WHO)"
label variable hc73     "NA - BMI standard deviation (new WHO)"
label variable shidx8   "Column number"
label variable sh87o    "Line number in HH schedule"
label variable sh88a    "Type of problem: illness"
label variable sh88b    "Type of problem: accident"
label variable sh88c    "Type of problem: dental"
label variable sh88d    "Type of problem: domestic violence"
label variable sh88x    "Type of problem: other"
label variable sh89     "Stop activities as a result of problem"
label variable sh90     "Number of days incapacitated"
label variable sh91     "Treatment for health problem"
label variable sh92     "Main reason didn't look for medical attention"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Not a household anymore"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
 99999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV024   
     1 "Atlantica"
     2 "Oriental"
     3 "Central"
     4 "Pacifica"
     5 "Bogota"
     6 "Orinoquia/Amazonia"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
 99999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV045A  
     1 "English"
     2 "Language 2"
     3 "Language 3"
     4 "Language 4"
     5 "Language 5"
     6 "Language 6"
;
label define HV045B  
     1 "English"
     2 "Language 2"
     3 "Language 3"
     4 "Language 4"
     5 "Language 5"
     6 "Language 6"
;
label define HV045C  
     1 "English"
     2 "Language 2"
     3 "Language 3"
     4 "Language 4"
     5 "Language 5"
     6 "Language 6"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    11 "Piped water from utility company"
    12 "Piped water from rural system"
    13 "Public tap"
    21 "Open well with sump pump"
    22 "Open well without sump pump"
    42 "River/stream/spring"
    51 "Rain water"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    11 "Piped water from utility company"
    12 "Piped water from rural system"
    13 "Public tap"
    21 "Open well with sump pump"
    22 "Open well without sump pump"
    42 "River/stream/spring"
    51 "Rain water"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    11 "Toilet connected to sewer"
    12 "Toilet connected to septic well"
    13 "Toilet connected to plot/yard"
    21 "Traditional pit toilet"
    22 "Traditional toilet to sea/river (low tide)"
    31 "No toilet facility"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/Sand"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Cement/gravel"
    30 "FINISHED"
    31 "Rug, carpet"
    32 "Polished wood, parquet"
    33 "Marble"
    34 "Ceramic tiles, vinyl, bricks"
    96 "OTHER"
;
label define HV214   
    11 "Bamboo(guadua), straw, other plants"
    12 "Bamboo without plaster"
    21 "Adobe (mud bricks)"
    22 "Bamboo with mud plaster"
    23 "Planks"
    24 "Zinc, canvas, plastics"
    31 "Bricks/polished wood/pre-manufactured material"
    32 "Prefabricated material"
    95 "Without walls"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    20 "RUDIMENTARY"
    30 "FINISHED"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
     3 "Male transgender"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Natural gas"
     2 "Propane gas"
     3 "Kerosene, oil, cocinol, diesel, gasoline, alcohol"
     4 "Electricity"
     5 "Firewood, charcoal"
     6 "Mineral coal"
     7 "Disposable material"
    95 "Do not cook"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed, fixed place"
     2 "Observed, mobile place"
     3 "Not observed: not in dwelling"
     4 "Not observed: no permission to see"
     5 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than once a month"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHDEPTO 
    91 "Amazonas"
     5 "Antioquia"
    81 "Arauca"
     8 "Atl?ntico"
    11 "Bogot?"
    13 "Bol?var"
    15 "Boyac?"
    17 "Caldas"
    18 "Caquet?"
    85 "Casanare"
    19 "Cauca"
    20 "Cesar"
    27 "Choc?"
    23 "C?rdoba"
    25 "Cundinamarca"
    94 "Guain?a"
    95 "Guaviare"
    41 "Huila"
    44 "La Guajira"
    47 "Magdalena"
    50 "Meta"
    52 "Nari?o"
    54 "Norte de Santander"
    86 "Putumayo"
    63 "Quind?o"
    66 "Risaralda"
    88 "San Andr?s y Providencia"
    68 "Santander"
    70 "Sucre"
    73 "Tolima"
    76 "Valle"
    97 "Vaup?s"
    99 "Vichada"
;
label define SHAREA  
     1 "City urban area"
     2 "Small village"
     3 "Disperse population"
;
label define SHSUBREG
     1 "Guajira, Cesar, Magdalena"
     2 "Barranquilla A. M."
     3 "Atlantico, San Andres, Bolivar Norte"
     4 "Bolivar Sur, Sucre, Cordoba"
     5 "Santanderes"
     6 "Boyaca, Cmarca, Meta"
     7 "Medellin A.M."
     8 "Antioquia sin Medellin"
     9 "Caldas, Risaralda, Quindio"
    10 "Tolima, Huila, Caqueta"
    11 "Cali A.M."
    12 "Valle sin Cali ni Litoral"
    13 "Cauca y Nari?o sin Litoral"
    14 "Litoral Pacifico"
    15 "Bogota"
    16 "Orinoquia y Amazonia"
;
label define SH63    
     1 "Unipersonal"
     2 "Nuclear complete"
     3 "Nuclear incomplete"
     4 "Couple with no children"
     5 "Expanded complete"
     6 "Expanded incomplete"
     7 "Expanded couple with no children"
     8 "Expanded: HH head and other relatives"
     9 "Compounded: Head/other relatives and no relatives"
    10 "Household with no permanent members"
;
label define SH64    
     0 "None"
;
label define SH68AB  
     0 "Electric bill with no strata, illegal connection"
     8 "No electric bill, Don't know"
;
label define SH68B   
     0 "No"
     1 "Yes"
;
label define SH68C   
     0 "No"
     1 "Yes"
;
label define SH68D   
     0 "No"
     1 "Yes"
;
label define SH68E   
     0 "No"
     1 "Yes"
;
label define SH71    
     0 "No"
     1 "Yes"
;
label define SH74    
     6 "6+"
;
label define SH75    
     1 "Used exclusively by household members"
     2 "Shared with persons from other households"
;
label define SH76    
     1 "Inside dwelling"
     2 "Within plot but outside dwelling"
     6 "Other"
;
label define SH77    
     0 "No"
     1 "Yes"
;
label define SH79F   
     0 "No"
     1 "Yes"
;
label define SH79G   
     0 "No"
     1 "Yes"
;
label define SH79L   
     0 "No"
     1 "Yes"
;
label define SH80    
     1 "Exclusive use"
     2 "Shared with others"
;
label define SH81    
     1 "Garbage collection system"
     2 "Burn"
     3 "Bury underground"
     4 "Throw to river/creek/stream/lake"
     5 "Throw to backyard/plot/open space"
     6 "Collected by informal systems"
    96 "Other"
;
label define SH85    
     1 "Owned house"
     2 "Rented house/other"
     3 "Owned apartment"
     4 "Rented apartment/other"
     5 "Room in house used for renting"
     6 "Room in other type of structure"
     7 "Indigenous dwelling"
    96 "Other (tents, wagons, natural refuge, under bridges)"
;
label define SH86    
     1 "Owned and paid off"
     2 "Owned still paying for it"
     3 "Renting/sub-renting"
     4 "Legal usufruct"
     5 "De-facto possession (no title)"
     6 "Dwelling pawned"
     7 "collective ownership"
    96 "Other"
;
label define SH94    
     0 "No"
     1 "Yes"
;
label define SH94A   
     0 "None"
;
label define SH94B   
     0 "None"
;
label define SH94C   
     0 "No"
     1 "Yes"
;
label define SH94D   
     0 "No"
     1 "Yes"
;
label define SH94E   
     0 "No"
     1 "Yes"
;
label define SH94F   
     0 "None"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    15 "Sister brother-in-law"
    16 "In-house maid"
    17 "Related to house maid"
    18 "Tenant"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
     3 "Male transgender"
     4 "Female transgender"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     8 "Don't know"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
     8 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     6 "Other"
     8 "Don't know"
;
label define SH09    
     1 "Indigenous"
     2 "Gypsy (ROM)"
     3 "Raizal from archipelago (San Andres)"
     4 "Palanquero from San Basilio"
     5 "Black/Mulato/Afro-Colombian/Afro-descendant"
     6 "None of the above"
;
label define SH12    
     1 "In country"
     2 "Abroad"
     8 "Don't know"
;
label define SH13    
     1 "Venezuela"
     2 "United States"
     3 "Spain"
     4 "Ecuador"
     5 "Panama"
     6 "Canada"
     7 "Chile"
     9 "Brazil"
    12 "Italy"
    15 "Peru"
    96 "Other"
;
label define SH14    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH15AA  
    98 "Don't know"
;
label define SH15AB  
    98 "Don't know"
;
label define SH15BA  
    98 "Don't know"
;
label define SH15BB  
    98 "Don't know"
;
label define SH15CA  
    98 "Don't know"
;
label define SH15CB  
    98 "Don't know"
;
label define SH16AA  
    98 "Don't know"
;
label define SH16AB  
    98 "Don't know"
;
label define SH16BA  
    98 "Don't know"
;
label define SH16BB  
    98 "Don't know"
;
label define SH16CA  
    98 "Don't know"
;
label define SH16CB  
    98 "Don't know"
;
label define SH16DA  
    98 "Don't know"
;
label define SH16DB  
    98 "Don't know"
;
label define SH16EA  
    98 "Don't know"
;
label define SH16EB  
    98 "Don't know"
;
label define SH16FA  
    98 "Don't know"
;
label define SH16FB  
    98 "Don't know"
;
label define SH16GA  
    98 "Don't know"
;
label define SH16GB  
    98 "Don't know"
;
label define SH20    
     0 "Wasn't registered"
     1 "Registry office"
     2 "Notary"
     6 "Other"
     8 "Don't know"
;
label define SH21    
     1 "Cost too much"
     2 "Registry place far away"
     3 "Father abandoned child"
     4 "Parents don't have documentation"
     5 "Lack of time"
     6 "Mother recovering from delivery"
     7 "Problems at registry office"
     8 "Child too small"
    10 "Don't have birth certificate"
    11 "Don't know where to register child"
    12 "Don't know how to register child"
    96 "Other"
;
label define SH22    
     1 "Just one place"
     2 "More than one place"
;
label define SH24    
     1 "Other city in the same state"
     2 "Other state"
     3 "Abroad"
     4 "Same city different urban/rural area"
;
label define SH25    
     1 "Urban city"
     2 "Town"
     3 "Rural"
;
label define SH26    
     1 "Violence by insurgents"
     2 "Natural disasters"
     3 "Seeking improve income"
     4 "Education"
     5 "Health"
     6 "Family reasons"
    96 "Other"
;
label define SH27    
     0 "None"
;
label define SH28A   
     0 "No"
     1 "Yes"
;
label define SH28B   
     0 "No"
     1 "Yes"
;
label define SH28C   
     0 "No"
     1 "Yes"
;
label define SH28D   
     0 "No"
     1 "Yes"
;
label define SH28X   
     0 "No"
     1 "Yes"
;
label define SH28    
     1 "Other city in the same state"
     2 "Other state"
     3 "Abroad"
     4 "Same city different urban/rural area"
;
label define SH30    
     0 "Not a household member"
;
label define SH31    
     1 "Working"
     2 "Didn't work, has a job"
     3 "Looking for work"
     4 "Studying"
     5 "Housework"
     6 "Retired"
     7 "Receive rents"
     8 "Permanently incapacitated"
     9 "Didn't do anything"
    96 "Other"
    98 "Don't know"
;
label define SH32    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH33    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH34    
     0 "No"
     1 "Yes"
     3 "Already retired"
     8 "Don't know"
;
label define SH35    
     0 "No"
     1 "Yes, currently attending"
     2 "Yes, attended in the past"
;
label define SH36    
     1 "HCB"
     2 "Family institution - ICBF"
     3 "Child institution/breastfeeding, preschool"
     4 "Social preschool"
     5 "Child development institution"
     6 "Family mode institute"
     7 "Daily program"
     8 "Preschool - public"
     9 "Preschool - private"
    96 "Other"
    98 "Don't know"
;
label define SH37    
     1 "Don't have money"
     2 "Too far"
     3 "Child not in preschool age"
     4 "Change of residence"
     5 "Currently in school"
     6 "Doesn't like how child is treated"
     7 "There is no institution or program"
     8 "Child is too small"
     9 "Take care of child at home"
    96 "Other"
;
label define SH38    
     1 "No institution near home"
     2 "Somebody else takes care of he/she at home"
     3 "Too young to attend"
     4 "Currently in school"
     5 "Couldn't find place (quota)"
     6 "Don't accept child"
     7 "Child doesn't meet requirements"
    96 "Other"
;
label define SH39    
     0 "No"
     1 "Yes"
;
label define SH41A   
     1 "Preschool"
     2 "Primary"
     3 "Secondary (high school)"
     4 "Middle academy or classic (basic high school)"
     5 "Middle technical (technical high school)"
     6 "Technical professional (after high school)"
     7 "Technological"
     8 "Professional (towards bachelor degree)"
     9 "Post-graduate training"
    10 "Master's degree studies"
    11 "PHD"
    98 "Don't know"
;
label define SH41B   
    98 "Don't know"
;
label define SH44A   
     1 "Preschool"
     2 "Primary"
     3 "Secondary (high school)"
     4 "Middle academy or classic (basic high school)"
     5 "Middle technical (technical high school)"
     6 "Technical professional (after high school)"
     7 "Technological"
     8 "Professional (towards bachelor degree)"
     9 "Post-graduate training"
    10 "Master's degree studies"
    11 "PHD"
    98 "Don't know"
;
label define SH44B   
    98 "Don't know"
;
label define SH46A   
     1 "Preschool"
     2 "Primary"
     3 "Secondary (high school)"
     4 "Middle academy or classic (basic high school)"
     5 "Middle technical (technical high school)"
     6 "Technical professional (after high school)"
     7 "Technological"
     8 "Professional (towards bachelor degree)"
     9 "Post-graduate training"
    10 "Master's degree studies"
    11 "PHD"
    98 "Don't know"
;
label define SH46B   
    98 "Don't know"
;
label define SH47    
     1 "Got pregnant"
     2 "Take care of children"
     3 "Family needed help"
     4 "Couldn't pay tuition"
     5 "Too young to be in school"
     6 "Serving in military"
     7 "Had to earn money"
     8 "Graduated/enough study"
     9 "Didn't pass university acceptance tests"
    10 "Didn't want to study"
    11 "No school/too far away"
    12 "Disabled/handicap"
    13 "Parents opposed"
    96 "Other"
    98 "Don't know"
;
label define SH48    
     1 "Yes, for HH member who is a relative"
     2 "Yes, for HH member who isn't a relative"
     3 "Yes, for a relative not a HH member"
     4 "Yes, for a non-relative not a HH member"
     5 "Self-employed"
     6 "Didn't work"
     8 "Don't know"
;
label define SH49    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH50    
     1 "EPS (with contribution)"
     2 "EPS (subsidy)"
     3 "With exception"
     4 "Special (Army/police, ECOPETROL, public universities, educational system)"
     5 "Not affiliated"
     8 "Don't know"
;
label define SH51    
     1 "Excellent"
     2 "Very good"
     3 "Good"
     4 "Regular"
     5 "Not good (bad)"
;
label define SH52    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH53A   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53B   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53C   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53D   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53E   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53F   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53G   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53H   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH53I   
     1 "No, can't do it"
     2 "Yes, can do with a lot of difficulty"
     3 "Yes, can do with some difficulty"
     4 "Yes, can do with no difficulty"
     8 "Don't know"
;
label define SH54    
     1 "Hear voice or sounds"
     2 "Talk, communicate"
     3 "See, close, far, around"
     4 "Move around/walk/climb stairs"
     5 "Hold, use arms/hands"
     6 "Understand, remember, take decisions"
     7 "Eat, put on clothes, take shower"
     8 "Relate/interact with others"
     9 "Do daily chores with no cardio/respiratory conditions"
;
label define SH55    
     1 "Born with it"
     2 "Illness"
     3 "Accident"
     4 "Age related reasons"
     5 "As a result of violence"
     6 "Other"
     8 "Don't know"
;
label define SH56A   
     0 "No"
     1 "Yes"
;
label define SH56B   
     0 "No"
     1 "Yes"
;
label define SH56C   
     0 "No"
     1 "Yes"
;
label define SH56X   
     0 "No"
     1 "Yes"
;
label define SH57A   
     0 "No"
     1 "Yes"
;
label define SH57B   
     0 "No"
     1 "Yes"
;
label define SH57C   
     0 "No"
     1 "Yes"
;
label define SH57D   
     0 "No"
     1 "Yes"
;
label define SH57E   
     0 "No"
     1 "Yes"
;
label define SH57F   
     0 "No"
     1 "Yes"
;
label define SH57G   
     0 "No"
     1 "Yes"
;
label define SH57H   
     0 "No"
     1 "Yes"
;
label define SH57I   
     0 "No"
     1 "Yes"
;
label define SH57J   
     0 "No"
     1 "Yes"
;
label define SH57K   
     0 "No"
     1 "Yes"
;
label define SH57L   
     0 "No"
     1 "Yes"
;
label define SH57M   
     0 "No"
     1 "Yes"
;
label define SH57N   
     0 "No"
     1 "Yes"
;
label define SH57O   
     0 "No"
     1 "Yes"
;
label define SH58A   
     0 "No"
     1 "Yes"
;
label define SH58B   
     0 "No"
     1 "Yes"
;
label define SH58C   
     0 "No"
     1 "Yes"
;
label define SH58D   
     0 "No"
     1 "Yes"
;
label define SH58E   
     0 "No"
     1 "Yes"
;
label define SH58F   
     0 "No"
     1 "Yes"
;
label define SH58G   
     0 "No"
     1 "Yes"
;
label define SH58H   
     0 "No"
     1 "Yes"
;
label define SH58I   
     0 "No"
     1 "Yes"
;
label define SH58J   
     0 "No"
     1 "Yes"
;
label define SH58K   
     0 "No"
     1 "Yes"
;
label define SH58L   
     0 "No"
     1 "Yes"
;
label define SH58M   
     0 "No"
     1 "Yes"
;
label define SH58X   
     0 "No"
     1 "Yes"
;
label define SH58Y   
     0 "No"
     1 "Yes"
;
label define SH60    
     0 "Not eligible"
     1 "Eligible"
;
label define SH62    
     0 "Not eligible"
     1 "Eligible"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   997 "Inconsistent"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "Labels to be populated according to country"
     8 "Don't know"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "Labels to be populated according to country"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define SH88A   
     1 "Yes"
     0 "No"
;
label define SH88B   
     1 "Yes"
     0 "No"
;
label define SH88C   
     1 "Yes"
     0 "No"
;
label define SH88D   
     1 "Yes"
     0 "No"
;
label define SH88X   
     1 "Yes"
     0 "No"
;
label define SH89    
     1 "Yes"
     0 "No"
;
label define SH91    
     1 "General doctor, specialist, dentist, therapist health institute"
     2 "Pharmacy/drugstore"
     3 "Home made remedies"
     4 "Self-medication"
     5 "Nothing"
     6 "Other"
;
label define SH92    
     1 "Related to personal reasons"
     2 "Access to health services"
     3 "Related to cost (service/transport)"
     4 "Paper work needed"
     5 "Lack of knowledge"
     6 "Opposition by partner/parents"
     7 "Not affiliated to the social security system"
     8 "Didn't know the service was provided by insurance"
     9 "Didn't want others to know"
    96 "Other"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values shdepto  SHDEPTO 
label values sharea   SHAREA  
label values shsubreg SHSUBREG
label values sh63     SH63    
label values sh64     SH64    
label values sh68ab   SH68AB  
label values sh68b    SH68B   
label values sh68c    SH68C   
label values sh68d    SH68D   
label values sh68e    SH68E   
label values sh71     SH71    
label values sh74     SH74    
label values sh75     SH75    
label values sh76     SH76    
label values sh77     SH77    
label values sh79f    SH79F   
label values sh79g    SH79G   
label values sh79l    SH79L   
label values sh80     SH80    
label values sh81     SH81    
label values sh85     SH85    
label values sh86     SH86    
label values sh94     SH94    
label values sh94a    SH94A   
label values sh94b    SH94B   
label values sh94c    SH94C   
label values sh94d    SH94D   
label values sh94e    SH94E   
label values sh94f    SH94F   
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv140    HV140   
label values sh09     SH09    
label values sh12     SH12    
label values sh13     SH13    
label values sh14     SH14    
label values sh15aa   SH15AA  
label values sh15ab   SH15AB  
label values sh15ba   SH15BA  
label values sh15bb   SH15BB  
label values sh15ca   SH15CA  
label values sh15cb   SH15CB  
label values sh16aa   SH16AA  
label values sh16ab   SH16AB  
label values sh16ba   SH16BA  
label values sh16bb   SH16BB  
label values sh16ca   SH16CA  
label values sh16cb   SH16CB  
label values sh16da   SH16DA  
label values sh16db   SH16DB  
label values sh16ea   SH16EA  
label values sh16eb   SH16EB  
label values sh16fa   SH16FA  
label values sh16fb   SH16FB  
label values sh16ga   SH16GA  
label values sh16gb   SH16GB  
label values sh20     SH20    
label values sh21     SH21    
label values sh22     SH22    
label values sh24     SH24    
label values sh25     SH25    
label values sh26     SH26    
label values sh27     SH27    
label values sh28a    SH28A   
label values sh28b    SH28B   
label values sh28c    SH28C   
label values sh28d    SH28D   
label values sh28x    SH28X   
label values sh28     SH28    
label values sh30     SH30    
label values sh31     SH31    
label values sh32     SH32    
label values sh33     SH33    
label values sh34     SH34    
label values sh35     SH35    
label values sh36     SH36    
label values sh37     SH37    
label values sh38     SH38    
label values sh39     SH39    
label values sh41a    SH41A   
label values sh41b    SH41B   
label values sh44a    SH44A   
label values sh44b    SH44B   
label values sh46a    SH46A   
label values sh46b    SH46B   
label values sh47     SH47    
label values sh48     SH48    
label values sh49     SH49    
label values sh50     SH50    
label values sh51     SH51    
label values sh52     SH52    
label values sh53a    SH53A   
label values sh53b    SH53B   
label values sh53c    SH53C   
label values sh53d    SH53D   
label values sh53e    SH53E   
label values sh53f    SH53F   
label values sh53g    SH53G   
label values sh53h    SH53H   
label values sh53i    SH53I   
label values sh54     SH54    
label values sh55     SH55    
label values sh56a    SH56A   
label values sh56b    SH56B   
label values sh56c    SH56C   
label values sh56x    SH56X   
label values sh57a    SH57A   
label values sh57b    SH57B   
label values sh57c    SH57C   
label values sh57d    SH57D   
label values sh57e    SH57E   
label values sh57f    SH57F   
label values sh57g    SH57G   
label values sh57h    SH57H   
label values sh57i    SH57I   
label values sh57j    SH57J   
label values sh57k    SH57K   
label values sh57l    SH57L   
label values sh57m    SH57M   
label values sh57n    SH57N   
label values sh57o    SH57O   
label values sh58a    SH58A   
label values sh58b    SH58B   
label values sh58c    SH58C   
label values sh58d    SH58D   
label values sh58e    SH58E   
label values sh58f    SH58F   
label values sh58g    SH58G   
label values sh58h    SH58H   
label values sh58i    SH58I   
label values sh58j    SH58J   
label values sh58k    SH58K   
label values sh58l    SH58L   
label values sh58m    SH58M   
label values sh58x    SH58X   
label values sh58y    SH58Y   
label values sh60     SH60    
label values sh62     SH62    
label values ha2      HA2     
label values ha3      HA3     
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha53     HA53    
label values ha54     HA54    
label values ha55     HA55    
label values ha56     HA56    
label values ha57     HA57    
label values ha58     HA58    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha64     HA64    
label values ha65     HA65    
label values ha66     HA66    
label values ha67     HA67    
label values ha68     HA68    
label values hc2      HC2     
label values hc3      HC3     
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values sh88a    SH88A   
label values sh88b    SH88B   
label values sh88c    SH88C   
label values sh88d    SH88D   
label values sh88x    SH88X   
label values sh89     SH89    
label values sh91     SH91    
label values sh92     SH92    
